### ISSUE TITLE
pipeline.run() sync argument is the same as pipeline.submit()

### ISSUE THREAD

**Issue by jeffkayne** [googleapis/python-aiplatform#1006]
Hello, there seems to be a simple bug in the google.cloud.aiplatform.pipeline_jobs.PipelineJob.run(service_account=service_account, sync=False) method. The sync argument doesn't do anything here: when it is set to False it still launches a synchronous run. It's also not clear to me the need for having a .submit() method and a .run() method that essentially do the same thing.

Thanks,
Jeff

**Comment by ji-yaqi** [comment]
Hi @jeffkayne, the setup of `google.cloud.aiplatform.pipeline_jobs.PipelineJob.run(sync=False)` is the same as `google.cloud.aiplatform.pipeline_jobs.PipelineJob.submit()`. Both of them launch a job that's running in the background. 

The reason to keep both is not to break the existing user's code. Hope that explains.

**Comment by jeffkayne** [comment]
Hi @ji-yaqi, thanks for the response. I see, the difference is therefore receiving asynchronous logs in the case of PipelineJob.run(sync=False) vs the script ending in PipelineJob.submit()
