### ISSUE TITLE
metadata create_artifact support

### ISSUE THREAD

**Issue by erik-voiceflow** [googleapis/python-aiplatform#1009]
It appears as though none of the **MetadataServiceClient** (by way of **MetadataServiceClientTransport**) methods are implemented yet, all returning MethodNotImplemented. 

https://github.com/googleapis/python-aiplatform/blob/a8149233bcd857e75700c6ec7d29c0aabf1687c1/google/cloud/aiplatform_v1beta1/services/metadata_service/transports/base.py#:~:text=def%20create_artifact

Is there an idea of when this feature will become available? Perhaps I am understanding incorrectly? 

Are there currently any workarounds other than just straight calling the underlying API endpoint?

Thanks in advance for any help!

**Comment by andrewferlitsch** [comment]
Currently ML Metadata is exposed at the GAPIC API layer, but not yet at the SDK level. For GAPIC, it is working:

https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/ml_ops/stage4/get_started_with_vertex_ml_metadata.ipynb

**Comment by morgandu** [comment]
Hi,

Is there a particular reason you are looking at the `transports/`? 

I believe the method you are looking for is implemented in the `client.py`

https://github.com/googleapis/python-aiplatform/blob/a8149233bcd857e75700c6ec7d29c0aabf1687c1/google/cloud/aiplatform_v1/services/metadata_service/client.py#L865

**Comment by erik-voiceflow** [comment]
> Hi,
> 
> Is there a particular reason you are looking at the `transports/`?
> 
> I believe the method you are looking for is implemented in the `client.py`
> 
> https://github.com/googleapis/python-aiplatform/blob/a8149233bcd857e75700c6ec7d29c0aabf1687c1/google/cloud/aiplatform_v1/services/metadata_service/client.py#L865

Am I wrong or does this method just call the equivalent transports method?

https://github.com/googleapis/python-aiplatform/blob/a8149233bcd857e75700c6ec7d29c0aabf1687c1/google/cloud/aiplatform_v1/services/metadata_service/client.py#L947

https://github.com/googleapis/python-aiplatform/blob/a8149233bcd857e75700c6ec7d29c0aabf1687c1/google/cloud/aiplatform_v1/services/metadata_service/client.py#L956

**Comment by morgandu** [comment]
It is, thought the correct equivalent transports method is implemented in the `grpc.py`, https://github.com/googleapis/python-aiplatform/blob/a8149233bcd857e75700c6ec7d29c0aabf1687c1/google/cloud/aiplatform_v1/services/metadata_service/transports/grpc.py#L374, not the `base.py` where you see the `raise NotImplementedError()`. 

Here is where you can find which class is used for the `self._transport`
https://github.com/googleapis/python-aiplatform/blob/a8149233bcd857e75700c6ec7d29c0aabf1687c1/google/cloud/aiplatform_v1/services/metadata_service/client.py#L494
->
https://github.com/googleapis/python-aiplatform/blob/a8149233bcd857e75700c6ec7d29c0aabf1687c1/google/cloud/aiplatform_v1/services/metadata_service/client.py#L75
