### ISSUE TITLE
Model Versioning using Vertex AI Model

### ISSUE THREAD

**Issue by dineshvelmuruga** [googleapis/python-aiplatform#1017]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
How do I register the model and load the different versions of the model using Vertex AI model.

For instance, I have trained scikit-learn model and I want to register it as v1(automatically as v1). After sometime, I have retrained my model with new features and I want to register my model with new version(automatically as v2).

Now I want to load my model like aiplatform.Model.load_model("model_name", "model_version") (not the current feature)

How Can I do this using Vertex AI Models
 Now I want to load my model like aiplatform.Model.load_model("model_name", "model_version") (not the current feature)
Now I want to load my model like aiplatform.Model.load_model("model_name", "model_version") (not the current feature)

**Comment by ageron** [comment]
It looks like this Python library does not support model versioning yet. However, you could use the [REST API](https://cloud.google.com/ai-platform/prediction/docs/reference/rest/v1/projects.models.versions), it supports model version.

@kweinmeister : is adding model versioning to this library on the roadmap? Thanks.

**Comment by samgoodman** [comment]
Hey @dineshvelmuruga, the SDK will support model versioning by the end of June. I will update this thread with update as they're available.

**Comment by samgoodman** [comment]
Hello! Model versioning support in the Vertex SDK launched today as part of release google-cloud-aiplatform 1.15. https://pypi.org/project/google-cloud-aiplatform/1.15.0/
