### ISSUE TITLE
Upload custom metrics to Tensorboard instance - Vertex AI Experiments

### ISSUE THREAD

**Issue by dineshvelmuruga** [googleapis/python-aiplatform#1018]
**Is your feature request related to a problem? Please describe.**
I have a scikit-learn model and I want to log and visualize experiment run metrics, params and artifacts in Tensorboard instance.
 **Describe the solution you'd like**
Export the experiment run metrics of models other than tensorflow and visualize it in tensorboard.

**Comment by morgandu** [comment]
Hi,

We have a notebook to show case Tensorboard instance, have you checked it out? https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/community/tensorboard

**Comment by morgandu** [comment]
Close this issue, feel free to reopen it the provided notebook link does not address your question.
