### ISSUE TITLE
Error: Failed timestamp transformation.

### ISSUE THREAD

**Issue by Muennighoff** [googleapis/python-aiplatform#1034]
I have a dataset with a timestamp column of form `2005-01-13 09:00:00`

which is not in your default timestamps: https://cloud.google.com/vertex-ai/docs/datasets/data-types-tabular#timestamp

I set all column transforms to auto.

When I train it works just fine, I don't know what it does with the column.
When I batch predict using that model on part of the dataset it errors out on that column with: `Error: Failed timestamp transformation.`

**Comment by Muennighoff** [comment]
Getting the same even on columns like `1989-07-31` even though it should be in your default timestamps. Model training works just fine & batch prediction fails...

**Comment by geraint0923** [comment]
@Muennighoff Thanks for reaching out. This is a bug in the Vertex Batch Prediction, the fix is currently being rolled out to prod, will ramp up to 100% by next Wednesday(March 9, 2022).

**Comment by Muennighoff** [comment]
Great, looking forward to that 👍

**Comment by Muennighoff** [comment]
It's working now; thanks!
