### ISSUE TITLE
Flake8 linting is incompatible with the black formatting

### ISSUE THREAD

**Issue by Ark-kun** [googleapis/python-aiplatform#1087]
Black formats
```
machine_spec = {
    "machine_type": "n1-standard-2",
}
```
to
```
"machine_spec = {"machine_type": "n1-standard-2",}
```
But Flake8 fails with error:
```
nox > python -m pip install flake8 black==19.10b0
nox > black --check docs google tests noxfile.py setup.py
All done! ✨ 🍰 ✨
669 files would be left unchanged.
nox > flake8 google tests
tests/system/aiplatform/test_project_id_inference.py:41:65: E231 missing whitespace after ','
nox > Command flake8 google tests failed with exit code 1
nox > Session lint failed.
```

See the log: https://source.cloud.google.com/results/invocations/4fc606fe-ddd0-4edc-ad78-66c695279171/targets/cloud-devrel%2Fclient-libraries%2Fpython%2Fgoogleapis%2Fpython-aiplatform%2Fpresubmit%2Fpresubmit/log

**Comment by morgandu** [comment]
can you remove the ',' and try `black` then `flake` again?

**Comment by Ark-kun** [comment]
This understandably works.
However my point still stands - the presubmit tests should only include one style test. Otherwise conflicts are inevitable.

BTW, the repo uses an old version of black. People with new version of black installed have their contributions fail presubmits.

**Comment by parthea** [comment]
This will be fixed in https://github.com/googleapis/synthtool/pull/1379
