### ISSUE TITLE
Vertex AI Prediction request timeouts

### ISSUE THREAD

**Issue by joonvena** [googleapis/python-aiplatform#1158]
Timeout parameter for the predictions introduced in the 1.12.0 version doesn't seem to work. I'm trying to get prediction from endpoint I have the timeout setting configured:

```
...
response = endpoint.predict(instances=instances, timeout=700.0)
return response
```

But after 60 seconds it will timeout even when the timeout is defined. Actual prediction will continue to run and finishes succesfully.

**Comment by sasha-gitg** [comment]
The 60s timeout is a Prediction service's internal time out.

**Comment by joonvena** [comment]
Do you happen to know if this is mentioned somewhere in the documentation?

**Comment by sasha-gitg** [comment]
Confirmed that it is not.
