### ISSUE TITLE
Fetch model monitoring anomalies API sample not working

### ISSUE THREAD

**Issue by entrpn** [googleapis/python-aiplatform#1184]
#### Environment details

  - OS type and version: GCP Workbench Notebook, Tensorflow 2.3 image
  - Python version: 3.7.10
  - pip version: 21.3 from /opt/conda/lib/python3.7/site-packages/pip (python 3.7)
  - `google-cloud-aiplatform` version: 1.7.0

#### Steps to reproduce

  1. Copy code from https://github.com/googleapis/python-aiplatform/blob/main/samples/generated_samples/aiplatform_generated_aiplatform_v1beta1_job_service_search_model_deployment_monitoring_stats_anomalies_sync.py to jupyter notebook cell.
  2. Update `model_deployment_monitoring_job` and `deployed_model_id`. 
  3. Run code.

#### Code example

```python
from google.cloud import aiplatform_v1
def sample_search_model_deployment_monitoring_stats_anomalies():
    # Create a client
    client = aiplatform_v1.JobServiceClient()

    # Initialize request argument(s)
    request = aiplatform_v1.SearchModelDeploymentMonitoringStatsAnomaliesRequest(
        model_deployment_monitoring_job="projects/redacted/locations/us-central1/modelDeploymentMonitoringJobs/redacted",
        deployed_model_id="redacted",
    )

    # Make the request
    page_result = client.search_model_deployment_monitoring_stats_anomalies(request=request)

    # Handle the response
    for response in page_result:
        print(response)
```

#### Stack trace
```
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "Received http2 header with status: 404"
	debug_error_string = "{"created":"@1650993259.299325271","description":"Error received from peer ipv4:173.194.202.95:443","file":"src/core/lib/surface/call.cc","file_line":905,"grpc_message":"Received http2 header with status: 404","grpc_status":12}"
>
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by parthea** [comment]
@dizcology, Please could you take a look?

**Comment by dizcology** [comment]
@entrpn These generated samples might require some modification to work.  In this particular case you need to include a regional endpoint in the instantiation of `client` here: https://github.com/googleapis/python-aiplatform/blob/main/samples/generated_samples/aiplatform_generated_aiplatform_v1beta1_job_service_search_model_deployment_monitoring_stats_anomalies_sync.py#L32

Please replace that line with something similar to this: 

```
client = aiplatform.gapic.DatasetServiceClient(client_options={"api_endpoint": "us-central1-aiplatform.googleapis.com"})
```
