### ISSUE TITLE
Support Setting name of the model when uploading the model

### ISSUE THREAD

**Issue by munagekar** [googleapis/python-aiplatform#1205]
Currently when a model is uploaded with the python sdk a random id is assigned as the name. This random id as the name is not human readable. While display_name can be used to make it human readable, display_name is mutable and not necessarily unique. 

Based on schema it is possible to specify a name. I would like the python sdk to support adding a name explicitly instead of the random id when uploading a model, to get a unique human readable name.

REF: https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.models

**Comment by samgoodman** [comment]
Hey @munagekar, would you mind sharing a code snippet of what you're running to upload models?

All the model class upload methods have a display_name parameter that sets a human-readable model name. Training jobs that producs models also have a model_display_name. If those aren't set, then a name will be generated for your model.

**Comment by munagekar** [comment]
In my understanding the display_name need not be unique. It is possible to create another model which has the display_name. So what I wanted to do was to set the name value myself instead of a random integer string.

Reading Model Name
```python
from google.cloud import aiplatform
filter_str = f'labels.managed_by="mlp" AND labels.ml_project="detector"'
models = aiplatform.Model.list(filter_str, project="xxx", location="us-west1")
>>> models[0].display_name
'test'
>>> models[0].name
'2xxxxxxxxxxxxxxxxxx'
```

I want to be able to set models[0].name itself from the python-sdk instead of having '2xxxxxxxxxxxxxxxxxx'.

The code that I use to upload is as follows:
```python
        model = aiplatform.models.Model.upload(
            serving_container_image_uri=self.container_spec.image,
            serving_container_predict_route=self.container_spec.predict_route,
            serving_container_health_route=self.container_spec.health_route,
            serving_container_ports=[self.container_spec.port],
            project=self.project.gcp_project_name,
            location=self.project.location,
            labels=self.labels,
            display_name=self.name,
            sync=True,
        )
```

I was wondering if the upload model could take `name` as an additional parameter, which I could then pass in to the protobuf when making the RPC to vertex-ai, instead of having the model name as a random integer string. After inspecting the api code and proto definitions I felt it would be possible to do so.

**Comment by samgoodman** [comment]
Hey @munagekar, thanks for the reply.
`Model.name` isn't actually an argument for a human readable model name, its an argument for a fully-qualified resource name, the presence of which indicates an existing model resource and the absence of which indicates a model that needs a resource assigned to it.

Including `name` in your model object is akin to saying "this is where my model lives in GCP". If you pass a Model with a name to `ModelService.Update` via a gRPC API (or [a PATCH REST request](https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.models/patch)), you're telling the backend using your Model representation "this is where to find the model resource to update".

Excluding `name` from your model object is akin to saying "this model resource doesn't exist yet". `ModelService.Upload` (or [a POST REST request](https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.models/upload)) will create the model resource (and corresponding resource name) for your model.

**Comment by samgoodman** [comment]
Actually, as luck may have it, support for custom model IDs is something that will be exposed in future ModelService.Upload versions. Once backend support is generally available, this feature will be added.

**Comment by samgoodman** [comment]
Hello! Custom model ID support in the Vertex SDK launched today as part of release google-cloud-aiplatform 1.15. https://pypi.org/project/google-cloud-aiplatform/1.15.0/
