### ISSUE TITLE
get_run functionality?

### ISSUE THREAD

**Issue by aronchick** [googleapis/python-aiplatform#1219]
In KFP, there's a simple way to get the run information for the pipeline - e.g.

```
    client = kfp.Client(host="http://ml-pipeline:8888")
    run_info = client.get_run(run_id=run_id)
```

There does not appear to be equivalent functionality in Vertex.

**Comment by sasha-gitg** [comment]
The analogous functionality would be:

```Python
job = aiplatform.PipelineJob.get(resource_name=run_id)
```

That will default to the `google.auth.default` project and credentials and `us-central1` location. To set those:

```Python
job = aiplatform.PipelineJob.get(resource_name=run_id, project=project, location=location, credentials=credentials)
```
