### ISSUE TITLE
Investigate why isinstance() doesn't work in test_value_converter.py

### ISSUE THREAD

**Issue by telpirion** [googleapis/python-aiplatform#136]
When using `isinstance()` to compare an object to a class in the `test_value_converter.py` file, the assertion fails with this message:

```
E       AssertionError: assert False
E        +  where False = isinstance(test_str: "Omnia Gallia est divisa"\ntest_int64: 3\ntest_bool: true\n, SomeMessage)
```

**Comment by Ark-kun** [comment]
`expected_type = SomeMessage(input_dict)` does not seem to be a type. It's a message instance.

Have you tried `assert isinstance(actual_from_value_output, SomeMessage)`?

Also
https://github.com/grpc/grpc/issues/18139#issuecomment-466503081

**Comment by telpirion** [comment]
@Ark-kun Yes, I tried that. Inside the test, the type of `SomeMessage` is `test_value_converter.SomeMessage` while `isinstance()` returns just `SomeMessage`.
