### ISSUE TITLE
Should use "tabular" in schema types.

### ISSUE THREAD

**Issue by dizcology** [googleapis/python-aiplatform#141]
This file (and maybe others too) refers to "tables", when it should be "tabular": https://github.com/googleapis/python-aiplatform/blob/master/google/cloud/aiplatform/v1beta1/schema/trainingjob/definition_v1beta1/types/automl_tables.py

**Comment by telpirion** [comment]
Taking this will represent a breaking change. Also, source files still include 'tables' in the file name. Closing as "won't fix" for now.
