### ISSUE TITLE
Vertex AI endpoint doesn't scale up / down

### ISSUE THREAD

**Issue by jgonzalezvargas** [googleapis/python-aiplatform#1413]
I've been deploying some custom trained models to Vertex AI, but lately, the feature to auto-scale has not been working properly on the later endpoints. Basically, despite the traffic, the endpoint doesn't auto-scale.

I have an older endpoint which works as intended, so I deployed the same model to a different endpoint with the same configuration (same machine specs, same GPU, min 1 machine, max 3 machines, 60% threshold to auto-scale), created it's own task queue and then proceeded to send the same requests to both endpoints at the same time.

The older endpoint worked as intended, scaling up and down depending on the incoming traffic. The newer one, on the other hand, stayed stuck at one machine the entire time.

I can _force it_ to scale up if I lower the threshold to 15-20%, and _it does_ scale up as the requests come in. However, it does not scale down once it has finished processing the requests and it stays with all the machines on even when there has not been any traffic for hours.

So, what may be preventing the newer endpoint to scale up as the traffic increases, given that the older endpoint does scale up and down as intended with the same traffic? And perhaps more importantly, what prevents it to scale down in the cases it does scale up?

Thanks in advance!

**Comment by samgoodman** [comment]
Hey @jgonzalezvargas, I'm working to find the backend owner for this right now.

**Comment by rosiezou** [comment]
Assigning this issue to @dizcology for triaging. I tried to find the internal code owner for the endpoint service but didn't have much luck.

**Comment by dizcology** [comment]
Closing this issue since it is quite old. @jgonzalezvargas please feel free to reopen this if you are still experiencing issues with auto scaling.

**Comment by matt-reltio** [comment]
We have seen similar dysfunction in GCP Vertex autoscaling. (scales up, doesn't scale down until manually discovered and endpoint redeployed)
