### ISSUE TITLE
batch_prediction_job.iter_outputs() tries to pull data from incorrect BigQuery dataset

### ISSUE THREAD

**Issue by ivanmkc** [googleapis/python-aiplatform#1431]
batch_prediction_job.iter_outputs() tries to pull from `python-docs-samples-tests:hierarchical_forecasting_20220613183814.predictions_2022_06_13T19_32_06_427Z_686` and fails but clicking on the link to the batch prediction job, the actual location of the destination data should be ` python-docs-samples-tests.hierarchical_forecasting_20220613183814.errors_validation_2022_06_13T19_32_06_427Z_686`

Code:
```
batch_prediction_job = model.batch_predict(
    job_display_name=f"hierarchical_forecasting_{TIMESTAMP}",
    gcs_source=DATASET_TEST_URI,
    instances_format="csv",
    bigquery_destination_prefix=batch_predict_bq_output_uri_prefix,
    predictions_format="bigquery",
    generate_explanation=True,
    sync=True,
)

batch_prediction_job.wait()

for row in batch_prediction_job.iter_outputs():
    print(row)

```

Output:
```
Creating BatchPredictionJob
BatchPredictionJob created. Resource name: projects/1012616486416/locations/us-central1/batchPredictionJobs/8014454878946459648
To use this BatchPredictionJob in another session:
bpj = aiplatform.BatchPredictionJob('projects/1012616486416/locations/us-central1/batchPredictionJobs/8014454878946459648')
View Batch Prediction Job:
https://console.cloud.google.com/ai/platform/locations/us-central1/batch-predictions/8014454878946459648?project=1012616486416


NotFound: 404 GET https://bigquery.googleapis.com/bigquery/v2/projects/python-docs-samples-tests/datasets/hierarchical_forecasting_20220613183814/tables/predictions_2022_06_13T19_32_06_427Z_686?prettyPrint=false: Not found: Table python-docs-samples-tests:hierarchical_forecasting_20220613183814.predictions_2022_06_13T19_32_06_427Z_686
```

#### Environment details

  - OS type and version: Mac OS 12.4 (21F79)
  - Python version: `python --version`
  ```
  Python 3.8.13
  ```
  - pip version: `pip --version`
  ```
  pip 21.1.3 from /Users/ivanmkc/Documents/code/vertex-ai-samples/env/lib/python3.8/site-packages/pip (python 3.8)
  ```
  - `google-cloud-aiplatform` version: `pip show google-cloud-aiplatform`: 
```
Name: google-cloud-aiplatform
Version: 1.13.1
Summary: Vertex AI API client library
Home-page: https://github.com/googleapis/python-aiplatform
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /Users/ivanmkc/Documents/code/vertex-ai-samples/env/lib/python3.8/site-packages
Requires: google-cloud-bigquery, google-api-core, packaging, proto-plus, google-cloud-resource-manager, google-cloud-storage
Required-by: 
```

**Comment by rosiezou** [comment]
@ivanmkc  I was able to partially reproduce the error case that you saw, except in my experiments, the batch prediction job create function errored out immediately when the data path was invalid. I then took a look at the actual error file from the experiment that you ran, and it looks like it was actually an auth issue, which should have caused a failure even before `iter_outputs` can get called. It'll be helpful if you could provide code/datasets to reproduce this exact bug. Please re-assign the issue to me after that.

**Comment by ivanmkc** [comment]
I'm not sure I have the exact code anymore. Will reopen when I see it again. I would just caution that the SDK should pull the link from the backend instead of generating it on the client-side.
