### ISSUE TITLE
`aiplatform.datasets._Dataset.list()` doesn't show any datasets. 

### ISSUE THREAD

**Issue by ivanmkc** [googleapis/python-aiplatform#1451]
The reason is the lack of any `_supported_metadata_schema_uris`s for this base class, so the following filter returns nothing:

```
        dataset_subclass_filter = (
            lambda gapic_obj: gapic_obj.metadata_schema_uri
            in cls._supported_metadata_schema_uris
        )
```        

This may be a bug or by design.

One could argue that this is a method on a private class and shouldn't be called. Will defer to SDK team.

**Comment by sasha-gitg** [comment]
This is intended. `_Dataset` is not meant to be used directly. Feel free to reopen as a FR to list all Datasets.
