### ISSUE TITLE
aiplatform.ExperimentRun can't be instantiated when it belongs to a pipeline run 

### ISSUE THREAD

**Issue by jasonbrancazio** [googleapis/python-aiplatform#1504]
DESCRIPTION
I tried associating a PipelineJob with an experiment today for the first time. I used the submit() method of my aiplatform.PipelineJob with the experiment_name argument set to my experiment name. The pipeline artifacts appeared in a row in Vertex AI Experiments. I observed that the experiment run name was set to my pipeline run name. Nice!

However, I hit the following error trying to then instantiate an ExperimentRun class with the python client library, so I could delete the experiment run:
aiplatform.ExperimentRun(experiment=my_experiment_name,run_name=my_pipeline_run_name) 

The error I received was:
404 Resource not found.; GetContext is unable to find context resource with name: projects/my_project_id/locations/us-central1/metadataStores/default/contexts/my_experiment_name-my_pipeline_run_name

(Project, experiment and run names have been changed to preserve privacy.)

I went to the UI to try to delete the experiment run, and was informed "Run cannot be deleted because it belongs to a pipeline run".

So I deleted the pipeline, wondering if the platform would also delete the experiment run associated with the pipeline run. It did not. The entry in Vertex AI Experiments remains, and I can't find the way to delete it.

Is this a bug? If not, how can I delete experiment runs that are associated with pipeline runs so they no longer show up in Vertex AI Experiments?

STEPS TO REPRODUCE
Run all the steps in the example notebook except "Cleaning Up":
https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/experiments/comparing_pipeline_runs.ipynb

Insert this code as the first line under the cleaning up header, and run it:
run_0 = vertex_ai.ExperimentRun(experiment=EXPERIMENT_NAME,run_name=pipeline_experiments_df.run_name[0])

You will see an error in the format I described above.

SIDE NOTE
In the comparing pipeline runs example notebook, the pip3 install refers to @sasha-gitg's version of the python-aiplatform repo, which likely is no longer intended:
!pip3 install {USER_FLAG} --force-reinstall git+https://github.com/sasha-gitg/python-aiplatform@main -q

SIDE NOTE 2
The href to open the comparing pipeline runs example notebook in Vertex AI Workbench does not work, because it does not refer to the raw version of the github notebook. It should be
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/GoogleCloudPlatform/vertex-ai-samples/main/notebooks/official/experiments/comparing_pipeline_runs.ipynb">

**Comment by sararob** [comment]
Hi Jason, thanks for raising these issues.

1) On the `ExperimentRun` context error you got, we're looking into it and I'll reply here when we have an update.
2) Right now there's no way to delete the metadata resources associated with an `Experiment` or `ExperimentRun`, but we're planning on adding an API for that in Q3
3) I'll make sure the notebook issues you found get fixed.

**Comment by jasonbrancazio** [comment]
Thanks for the reply, @sararob!

The code below accomplishes the goal that drove me to try to instantiate an ExperimentRun in the first place, and gets around the cloud console's "Run cannot be deleted because it belongs to a pipeline run" message. 

However, it uses a protected class, and leads to an odd experience for a pipeline that is associated with an experiment: After deleting the experiment run, where you would have seen a link in the cloud console to the associated experiment run, you see an endlessly spinning circle.

```
def delete_pipeline_run(pipeline_run_name: str):
    """
    Delete a pipeline run from the default metadata store.

    Args:
        pipeline_run_name: The pipeline run name, which is the job_id parameter of an
          aiplatform.PipelineJob
    """
    pipeline_run = _Context(resource_name=pipeline_run_name)
    if pipeline_run.schema_title == 'system.PipelineRun':
        pipeline_run.delete()
        print(f"Deleted experiment {pipeline_run} from Metadata Store")
```

As an aside, why is _Context a protected class, but Execution and Artifact are not? Perhaps it's a good idea to expose Context as a class users can work with, for example, like this:

```
def clear_metadata_store():
    """
    Completely wipe the metadata store.
    """
    _ = [a.delete() for a in Artifact.list()]
    _ = [e.delete() for e in Execution.list()]
    _ = [c.delete() for c in _Context.list()]
```

**Comment by sararob** [comment]
Thanks for the details. I wasn't able to repro the spinning circle issue you encountered. Could you let me know the steps you went through that led to that? In the meantime, until we add the delete API, could you try the following to delete a pipeline run:

1. Delete the pipeline run via the pipelines UI
2. Delete the pipeline run context from metadata with the approach you used in `delete_pipeline_run`

We're in the process of making the `_Context` class public, see https://github.com/googleapis/python-aiplatform/pull/1519

Re: your initial question about trying to instantiate an `ExperimentRun`, when you associated the pipeline run to an Experiment via `PipelineJob.submit(experiment=...)`, that created an `Experiment` context for it but not an `ExperimentRun` context: https://github.com/googleapis/python-aiplatform/blob/f93d19c7e530b49f9792a80334746400e8ada2bf/google/cloud/aiplatform/pipeline_jobs.py#L376

But I can see how this could be confusing when you're viewing Experiment resources. We're discussing this and will keep you posted. Thanks again for the feedback!

**Comment by sararob** [comment]
Update: to clear up confusion around ExperimentRun and Pipeline run resources associated to an Experiment we've updated the Experiments UI. Now when you're viewing the runs associated with an Experiment, there's a new column in the table labeled "Type" which will tell you whether the given run is an Experiment run or Pipeline run.

I'm going to close this but feel free to re-open if you're still running into issues.
