### ISSUE TITLE
Where are the new CPR sample notebooks?

### ISSUE THREAD

**Issue by lanhwang** [googleapis/python-aiplatform#1532]
Hi I am trying to follow the sample notebooks in the CPR branch to deploy custom models. But I saw there is new commit saying `samples: Removed CPR samples for merging into the main branch.` Where can I find new sample notebooks? Thanks.

**Comment by abcdefgs0324** [comment]
We have moved to https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/community/prediction/custom_prediction_routines.

**Comment by lanhwang** [comment]
Thank you!
