### ISSUE TITLE
Dataset without import_schema_uri crashing console

### ISSUE THREAD

**Issue by vitalii-bulyzhyn** [googleapis/python-aiplatform#1555]
#### Environment details

  - OS type and version: MacOS Monterrey v12.0
  - Python version: Python 3.9.12
  - pip version: pip 21.3.1
  - `google-cloud-aiplatform` version: Version: 1.15.1

#### Steps to reproduce

  1. Init ai platform 
  2. Create dataset without import_schema_uri
  3. Go to console and open dataset that you've just created

#### Code example

```python
        aiplatform.init(
            project='project',
            location='us-central1',
            credentials=credentials,
            staging_bucket='gs://bucket',
            experiment='experiment',
            experiment_description='Experiment description'
        )

        working_dataset = aiplatform.ImageDataset.create(
                display_name="bugdataset"
            )
```

#### Output
```
Creating ImageDataset
Create ImageDataset backing LRO: projects/***/locations/us-central1/datasets/***/operations/***
ImageDataset created. Resource name: projects/***/locations/us-central1/datasets/***
To use this ImageDataset in another session:
ds = aiplatform.ImageDataset('projects/***/locations/us-central1/datasets/***')
<google.cloud.aiplatform.datasets.image_dataset.ImageDataset object at 0x16dd0ce20> 
resource name: projects/***/locations/us-central1/datasets/***
```

#### Console

1. If you go to see datasets in console, you will see that dataset is created:
<img width="1512" alt="Screenshot 2022-07-29 at 10 39 01" src="https://user-images.githubusercontent.com/46309116/181794954-542901ff-adea-435b-9f65-2a50e6d623b1.png">

2. Try to open created dataset, and will see next:
<img width="1512" alt="Screenshot 2022-07-29 at 10 40 27" src="https://user-images.githubusercontent.com/46309116/181795167-29d21eb1-4974-4a28-a69f-f39944835f50.png">

**Comment by rosiezou** [comment]
@vitalii-bulyzhyn accessing datasets in the Chrome developer console isn't an intended use case for Vertex AI datasets as far as I'm aware. Could you clarify which resources you were trying to view from the console? Were you trying to access the dataset from Cloud Shell instead? If you were, please refer to the Cloud Shell documentation [here](https://cloud.google.com/shell).

**Comment by vitalii-bulyzhyn** [comment]
@rosiezou if it's no intended use case, maybe it has sense to hide them or whatever? Because now it's just crashing my browser

Well, I just created empty dataset without type, and then tried to access it in the console

**Comment by rosiezou** [comment]
This looks like an issue with frontend. Triaging this issue to @kweinmeister for a quick look since he is more familiar with cross-functional workflows for Vertex AI. Karl, please re-assign to the Vertex AI Frontend team or another cross-functional team as you see fit.

**Comment by rosiezou** [comment]
This issue should be fixed now. Please re-open if the issue persists.
