### ISSUE TITLE
client.create_batch_prediction_job throws TypeError: Parameter to MergeFrom() must be instance of same class

### ISSUE THREAD

**Issue by Jakobhenningjensen** [googleapis/python-aiplatform#1625]
#### Environment details

  - OS type and version: Windows 11 Pro ( 22000.856)
  - Python version: 3.10.2
  - pip version: 22.2.2
  - `google-cloud-aiplatform` version: 1.16.1

#### Steps to reproduce

  Following the guide [here](https://github.com/googleapis/python-aiplatform/blob/main/samples/snippets/job_service/create_batch_prediction_job_bigquery_sample.py) - the step 

`    response = client.create_batch_prediction_job(parent=parent, batch_prediction_job=batch_prediction_job)`

throws the error `TypeError: Parameter to MergeFrom() must be instance of same class: expected google.cloud.aiplatform.v1.BatchPredictionJob got BatchPredictionJob.`

#### Code example

    location = 'europe-west4'
    project_id = "my_project"
    model_id = '99999999999999' #some id
    version = None
    bigquery_source_table = 'Table.name'
    batch_prediction_name = 'Batch prediction test'
    generate_explanation = False

    # The AI Platform services require regional API endpoints.
    client_options = {"api_endpoint": location + "-aiplatform.googleapis.com"}
    # Initialize client that will be used to create and send requests.
    # This client only needs to be created once, and can be reused for multiple requests.
    client = aiplatform.gapic.JobServiceClient(client_options=client_options)

    model = aiplatform.Model(
        project=project_id,
        location=location,
        model_name=model_id,
        version=version)

    batch_prediction_job = aiplatform.BatchPredictionJob.create(
        job_display_name=batch_prediction_name,
        project=project_id,
        location=location,
        model_name=model,
        bigquery_source=f'bq://{project_id}.{bigquery_source_table}',
        bigquery_destination_prefix=f'bq://{project_id}.test_results',
        generate_explanation=generate_explanation
    )
    parent = f"projects/{project_id}/locations/{location}"
    response = client.create_batch_prediction_job(
        parent=parent, batch_prediction_job=batch_prediction_job
    )

#### Stack trace
```
c:\Code\test\test_google_cloud\test_create_batch_prediction_job_bigquery.py in <cell line: 1>()
----> [65](file:///c%3A/test/test_google_cloud/test_create_batch_prediction_job_bigquery.py?line=64)
 response = client.create_batch_prediction_job(
      [66](file:///c%3A/test/test_google_cloud/test_create_batch_prediction_job_bigquery.py?line=65)
     parent=parent, batch_prediction_job=batch_prediction_job
      [67](file:///c%3A/test/test_google_cloud/test_create_batch_prediction_job_bigquery.py?line=66) )


File c:\Users\Hennings\AppData\Local\Programs\Python\Python310\lib\site-packages\google\cloud\aiplatform_v1\services\job_service\client.py:2397, in JobServiceClient.create_batch_prediction_job(self, request, parent, batch_prediction_job, retry, timeout, metadata)
   [2395](file:///c%3A/Users/Hennings/AppData/Local/Programs/Python/Python310/lib/site-packages/google/cloud/aiplatform_v1/services/job_service/client.py?line=2394)
         request.parent = parent
   [2396](file:///c%3A/Users/Hennings/AppData/Local/Programs/Python/Python310/lib/site-packages/google/cloud/aiplatform_v1/services/job_service/client.py?line=2395) 
    if batch_prediction_job is not None:
-> [2397](file:///c%3A/Users/Hennings/AppData/Local/Programs/Python/Python310/lib/site-packages/google/cloud/aiplatform_v1/services/job_service/client.py?line=2396)  
       request.batch_prediction_job = batch_prediction_job
   [2399](file:///c%3A/Users/Hennings/AppData/Local/Programs/Python/Python310/lib/site-packages/google/cloud/aiplatform_v1/services/job_service/client.py?line=2398)
 # Wrap the RPC method; this adds retry and timeout information,
   [2400](file:///c%3A/Users/Hennings/AppData/Local/Programs/Python/Python310/lib/site-packages/google/cloud/aiplatform_v1/services/job_service/client.py?line=2399) 
# and friendly error handling.
   [2401](file:///c%3A/Users/Hennings/AppData/Local/Programs/Python/Python310/lib/site-packages/google/cloud/aiplatform_v1/services/job_service/client.py?line=2400) 
rpc = self._transport._wrapped_methods[
   [2402](file:///c%3A/Users/Hennings/AppData/Local/Programs/Python/Python310/lib/site-packages/google/cloud/aiplatform_v1/services/job_service/client.py?line=2401) 
    self._transport.create_batch_prediction_job
   [2403](file:///c%3A/Users/Hennings/AppData/Local/Programs/Python/Python310/lib/site-packages/google/cloud/aiplatform_v1/services/job_service/client.py?line=2402) ]

File ~\AppData\Roaming\Python\Python310\site-packages\proto\message.py:766, in Message.__setattr__(self, key, value)
    [764](file:///c%3A/Users/Hennings/AppData/Roaming/Python/Python310/site-packages/proto/message.py?line=763) # Merge in the value being set.
    [765](file:///c%3A/Users/Hennings/AppData/Roaming/Python/Python310/site-packages/proto/message.py?line=764) if pb_value is not None:
--> [766](file:///c%3A/Users/Hennings/AppData/Roaming/Python/Python310/site-packages/proto/message.py?line=765)     self._pb.MergeFrom(self._meta.pb(**{key: pb_value}))

TypeError: Parameter to MergeFrom() must be instance of same class: expected google.cloud.aiplatform.v1.BatchPredictionJob got BatchPredictionJob.
```

**Comment by sasha-gitg** [comment]
You can interact with `aiplatform.BatchPredictionJob` directly after creation. Here is an [example notebook](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/daa64efd40b579bde8ab0e8431dbdc51f301bd1f/notebooks/official/migration/UJ10%20Vertex%20SDK%20Custom%20Scikit-Learn%20with%20pre-built%20training%20container.ipynb) demonstrating consumption of the predictions from the Job.

#1190 describes the separation of the different modules in the SDK.

**Comment by Jakobhenningjensen** [comment]
Thanks, I'll have a look at it.

Is it a bug or does the docs (linked in OP) have to be updated?

**Comment by rosiezou** [comment]
[Here](https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform.Model) is the latest docs for the `Model` class. Detailed documentation for `batch_predict` can be found [later on the docs page](https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform.Model#google_cloud_aiplatform_Model_batch_predict). The code snippet you have linked in the issue description needs to be updated -- it is being worked on and we are tracking the progress internally. In general, it is a lot easier to use the SDK classes directly instead of using GAPIC client classes. For more references please visit the docs page for the [BatchPredictionJob.create()](https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform.BatchPredictionJob#google_cloud_aiplatform_BatchPredictionJob_create) method. I hope this helps.

**Comment by janmejaya-nanda** [comment]
I guess, the documentation(to date) is not updated. But [BatchPredictionJob.create()](https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform.BatchPredictionJob#google_cloud_aiplatform_BatchPredictionJob_create) does not have an option to provide custom container for inferencing, whereas [client.create_batch_prediction_job](https://github.com/googleapis/python-aiplatform/blob/main/samples/snippets/job_service/create_batch_prediction_job_bigquery_sample.py) have. Any idea how to run a batch inference using the custom container?
