### ISSUE TITLE
_InactiveRpcError when interfacing with Matching Engine using `match_service.proto`

### ISSUE THREAD

**Issue by yeleer** [googleapis/python-aiplatform#1646]
Hi,

The interface for sending queries to Vertex AI Matching Engine with Python changed in a way that breaks functionality by disallowing "restricts". 

In particular, developers were previously able to send a request by working directly with the `match_service.proto` protocol buffer (see the "Create Online Queries" section of https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/matching_engine/matching_engine_for_indexing.ipynb). This allowed developers to specify key-value "restricts" as described here: https://cloud.google.com/vertex-ai/docs/matching-engine/filtering.

However, the solution put forth by that notebook no longer works; the preferred method for sending queries to Matching Engine now seems to be: https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform.MatchingEngineIndexEndpoint#google_cloud_aiplatform_MatchingEngineIndexEndpoint_match. However, this API does not allow restricts.

I was wondering:

1. Is interfacing with Matching Engine using gRPC in the way described in `matching_engine_for_indexing.ipynb` now deprecated, or is this a bug?
2. Is there any solution that uses `match_service.proto`, even if it's different from that detailed in `matching_engine_for_indexing.ipynb`? We'd like to be able to have access to all the functionality detailed in the message definition.
3. As noted above (and as can be seen from [`match_service.proto`](https://github.com/googleapis/python-aiplatform/blob/main/google/cloud/aiplatform/matching_engine/_protos/match_service.proto), the match service offers many knobs (in addition to restricts) that can be adjusted at match time. Are there plans to introduce a way to interface with this functionality in `MatchingEngineIndexEndpoint`?

From the following:
```
channel = grpc.insecure_channel("{}:10000".format(DEPLOYED_INDEX_SERVER_IP))
stub = match_service_pb2_grpc.MatchServiceStub(channel)
request = match_service_pb2.MatchRequest()
request.deployed_index_id = DEPLOYED_INDEX_ID
for val in query:
    request.float_val.append(val)

response = stub.Match(request)
```

I get this error:
```
File ~/miniforge3/envs/my_env/lib/python3.9/site-packages/grpc/_channel.py:946, in _UnaryUnaryMultiCallable.__call__(self, request, timeout, metadata, credentials, wait_for_ready, compression)
    937 def __call__(self,
    938              request,
    939              timeout=None,
   (...)
    942              wait_for_ready=None,
    943              compression=None):
    944     state, call, = self._blocking(request, timeout, metadata, credentials,
    945                                   wait_for_ready, compression)
--> 946     return _end_unary_response_blocking(state, call, False, None)

File ~/miniforge3/envs/my_env/lib/python3.9/site-packages/grpc/_channel.py:849, in _end_unary_response_blocking(state, call, with_call, deadline)
    847         return state.response
    848 else:
--> 849     raise _InactiveRpcError(state)

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1662499864.829752000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3135,"referenced_errors":[{"created":"@1662499864.829750000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
```

Thank you!

**Comment by jaycee-li** [comment]
Hi @yeleer ,

This [sample notebook](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/matching_engine/matching_engine_for_indexing.ipynb) is still working, but you need to run the "Create Online Queries" section in a Google managed notebook instance that is created with your VPC network. Please see the "Before you begin" section for more detail.

Last week we released google-cloud-aiplatform 1.17.0, and we add [filtering](https://github.com/googleapis/python-aiplatform/blob/2bc9b2b0d048c29ba43c8b4c3ea51370515d08c3/google/cloud/aiplatform/matching_engine/matching_engine_index_endpoint.py#L822) functionality to the `match` method in `MatchingEngineIndexEndpoint`.
