### ISSUE TITLE
Preserve Feature Order in the response of EntityType.read()

### ISSUE THREAD

**Issue by dslove** [googleapis/python-aiplatform#1694]
When calling the online serving method `EntityType.read()`, in the response the order of the returned features is not preserved as they are stored in FeatureStore. In other words, the returned Pandas DataFrame's columns can be in any order, which is totally in random. In some of our use cases, this problem forces us to have an extra step to re-order the DataFrame columns before we can use this DataFrame to join online prediction, which in general reduces our application's performance.
We are playing with V1.17.1 at this moment.
So here I suggest to maybe add a parameter in the method like `preserve_order=True` and provide such a functionality.
This problem is very easy to reproduce so I don't provide a test case here.

**Comment by rosiezou** [comment]
@sasha-gitg PTAL at this user feedback
