### ISSUE TITLE
Better organize FeatureStore, Entity Type, and Feature on GUI

### ISSUE THREAD

**Issue by dslove** [googleapis/python-aiplatform#1703]
The current (as of Sept 2022) FeatherStore GUI main page on GCP console shows all features under all entity types of all feature stores with paging. This looks a bit in chaos when there are a lot of features within multiple entity types and feature stores and makes it a bit difficult to browse. Yes there is a filter but not all the users like to memorize and enter the names of features, entity types, or feature stores.
Suggest to show all these things in a hierarchical way, like an explorer panel with tree view or whatever, but just don't throw all the stuff to the front.
Pls advise if this is not the right place to post this request.

**Comment by rosiezou** [comment]
Thanks for the feedback. There is a separate team responsible for UI work. I will close this issue since this repo is not the right space for it, but I will pass this feedback to our UI team.

**Comment by dslove** [comment]
Thank you @rosiezou
