### ISSUE TITLE
Support easily fetching all entities in one shot in batch_serve_to_***()

### ISSUE THREAD

**Issue by dslove** [googleapis/python-aiplatform#1706]
The current implementation of `batch_serve_to***()` requires us to compose a read_instance first in which we have to specify the entity ids to pull the feature values from. In some case where we need to simply output all data from a single entity type or join all entity ids from multiple entity types this becomes very inconvenient, because we have to find out all entity ids in relevant entity types first (and currently feature store cannot provide that and we have to look up the source feature dataset, this could be another feature request).
Can we implement a way to simply serve all entities without specifying their ids in read_instance? Or maybe using a wildcard `*` in read_instance like:
```
{
    "entity_type_id_1": "*",
    "timestamp": "......"
}
```

**Comment by petrokuzz** [comment]
So, what happened to this request?
