### ISSUE TITLE
Package has inconsistent dependencies due to `protobuf` conflict

### ISSUE THREAD

**Issue by jotaporras** [googleapis/python-aiplatform#1746]
We use `pip-tools` to ensure consistency between package dependencies. Recently our builds have been breaking on `pip-compile` because of inconsistent `protobuf` versions on the required dependencies of `google-cloud-aiplatform`. 

Specifically: `google-cloud-bigquery==2.34.4` requires `protobuf<4.0.0dev,>=3.12.0`, while `google-api-core[grpc]==2.10.2` requires `protobuf>=4.21.6`.

This seems like it could be resolved by updating to the latest `google-cloud-bigquery>=3.3.5`, as recent versions have enabled `protobuf>3.x`. This was also confirmed by successfully compiling the requirements of the latest `google-cloud-bigquery`.

#### Environment details

  - OS type and version: macOS 12.6
  - Python version: `python --version` `Python 3.7.9`
  - pip version: `pip --version``pip 22.3`
  - `google-cloud-aiplatform` version: `pip show google-cloud-aiplatform` `google-cloud-aiplatform==1.18.2`

#### Steps to reproduce

  1. Create a virtual environment with `venv` or similar, run `pip install pip-tools`
  2. Create a `requirements.in` with a single line `google-cloud-aiplatform` and run `pip-compile`

#### Code example

```sh
python -m venv .venv
source .venv/bin/activate
pip install pip-tools
echo "google-cloud-aiplatform" > requirements.in
pip-compile
```

#### Stack trace
```
Could not find a version that matches protobuf(...)

(...)

There are incompatible versions in the resolved dependencies:
  protobuf<5.0.0dev,>=3.19.0 (from proto-plus==1.22.1->google-cloud-aiplatform==1.18.2->-r requirements.in (line 1))
  protobuf<4.0.0dev,>=3.12.0 (from google-cloud-bigquery==2.34.4->google-cloud-aiplatform==1.18.2->-r requirements.in (line 1))
  protobuf>=4.21.6 (from grpcio-status==1.50.0->google-api-core[grpc]==2.10.2->google-cloud-aiplatform==1.18.2->-r requirements.in (line 1))
  protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 (from google-cloud-aiplatform==1.18.2->-r requirements.in (line 1))
  protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 (from google-api-core[grpc]==2.10.2->google-cloud-aiplatform==1.18.2->-r requirements.in (line 1))
  protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 (from google-cloud-resource-manager==1.6.3->google-cloud-aiplatform==1.18.2->-r requirements.in (line 1))
  protobuf<5.0.0dev,>=3.15.0 (from googleapis-common-protos==1.56.4->google-api-core[grpc]==2.10.2->google-cloud-aiplatform==1.18.2->-r requirements.in (line 1))
```

**Comment by sararob** [comment]
It looks like this is a known issue with `pip-compile`: https://github.com/jazzband/pip-tools/issues/1680

Could you try the following to see if it resolves the dependency error?

```
python -m venv .venv
source .venv/bin/activate
pip install pip-tools
echo "google-cloud-aiplatform" > requirements.in
pip-compile --resolver=backtracking
```

**Comment by jotaporras** [comment]
Thank you for the reply @sararob. This indeed solves the issue. 

I'm curious as to why, though. The version requirements do seem to be conflicting based on what's declared in the package's setup files, and no version should satisfy the requirements. 

Am I missing something? Does the new solver ignore certain constraints?

**Comment by sararob** [comment]
Sorry for the delayed response. I think the default resolver in `pip-tools` doesn't resolve dependencies in the same way as `pip`, but it looks like this is fixed with the backtracking resolver, which they're recommending in the issue linked above.
