### ISSUE TITLE
Passing env vars to to model created using `LocalModel.build_cpr_model`

### ISSUE THREAD

**Issue by tobiasb** [googleapis/python-aiplatform#1765]
Hi,

we're working off [the documentation](https://cloud.google.com/vertex-ai/docs/predictions/custom-prediction-routines#upload_to_vertex_ai_model_registry) to build a Vertex.AI model with a custom prediction routine.

What I'm trying to do is supply the model with an environment variable to use during prediction in our custom prediction routine. While `aiplatform.Model.upload` supports supplying env vars via `serving_container_environment_variables`, they [won't get used when providing a `local_model`](https://github.com/googleapis/python-aiplatform/blob/main/google/cloud/aiplatform/models.py#L3011) at the same time. `LocalModel.build_cpr_model` however (used in the example) doesn't support passing env variables to it so I ended up re-implementing most of `LocalModel.build_cpr_model` which feels suboptimal. Am I using the library wrong?

**Comment by kthytang** [comment]
It's a known issue that that `LocalModel.build_cpr_model` doesn't support user supplied environment variables. We're planning to add that functionality in the future.

For now, as a workaround, you can get the container spec of the local model creating using CPR by calling `local_model.get_serving_container_spec`. Then you can create a new `LocalModel` with your own env vars by calling
```
local_model2 = LocalModel(
        serving_container_image_uri=local_model.get_serving_container_spec().image_uri,
        serving_container_predict_route=local_model.get_serving_container_spec().predict_route,
        serving_container_health_route=local_model.get_serving_container_spec().health_route,
        serving_container_environment_variables={...}, # the env vars you want to set
)
```
