### ISSUE TITLE
Add class labels to ImageDataSet using import_data still does not work.

### ISSUE THREAD

**Issue by eddaypandera** [googleapis/python-aiplatform#1766]
[This](https://github.com/googleapis/python-aiplatform/issues/961) does not work for me either. It is importing to an existing dataset that doesn't seem to work.
I thought I'd be able to do something like:

```
class_labels = { 'gs://path/to/image/imagefile.jpg': 'lab1'}
ds = aiplatform.ImageDataset(existing_dataset_id)
ds.import_data(gcs_source=DATASET_PATH, data_item_labels=class_labels, 
import_schema_uri=aiplatform.schema.dataset.ioformat.image.single_label_classification)
```

but it doesn't like the filename in `class_labels`. If I leave it out the new images (defined in `gcs_source=DATASET_PATH`) are imported unlabelled.

_Originally posted by @eddaypandera in https://github.com/googleapis/python-aiplatform/issues/961#issuecomment-1298693425_

**Comment by jaycee-li** [comment]
Hi @eddaypandera ,

The `data_item_labels` argument is not used for specifying the training target of your data. It is used for setting some global labels for the whole dataset you upload. For example, the following `data_item_labels` tells that the data you upload is training data.
```
ds.import_data(
    gcs_source = "gs://path/to/input/file/input_file.csv",
    import_schema_uri=aiplatform.schema.dataset.ioformat.image.single_label_classification,
    data_item_labels={"aiplatform.googleapis.com/ml_use":"training"}
)
```

If you want to specify the training labels for your upload images, you can do that in the input file. For example,
```
## Write the input file
import csv
with open('input_file.csv', 'w') as f:
    writer = csv.writer(f)
    writer.writerows(
        [
            ["gs://path/to/image/image_1.jpg", "cat"],
            ["gs://path/to/image/image_2.jpg", "dog"],
            ["gs://path/to/image/image_3.jpg", "bird"],
        ]
    )

## Upload the file to gcs
!gsutil cp input_file.csv gs://path/to/input/file/input_file.csv

## Import data
ds.import_data(
    gcs_source = "gs://path/to/input/file/input_file.csv",
    import_schema_uri=aiplatform.schema.dataset.ioformat.image.single_label_classification,
)
```

Please check [this page](https://cloud.google.com/vertex-ai/docs/image-data/classification/prepare-data#csv_1) for more details on how to prepare input files. And let me know if you have any other questions.
