### ISSUE TITLE
Vertex AI Model Monitoring Training Data

### ISSUE THREAD

**Issue by gkoutsos9** [googleapis/python-aiplatform#1775]
This is a question around the training data to upload for Vertex's model monitoring.  Is the data required the fully preprocessed data? In the case of my model setup, I have a single .joblib file that handles both one hot encoding and prediction. The data being pushed through this file in the form of a Pandas dataframe. So in this case, would the data required for model monitoring need to be the data being pushed through the file or the data being pushed into Vertex (JSON payload)?

**Comment by nayaknishant** [comment]
Opened [b/258054333](https://b.corp.google.com/issues/258054333)

**Comment by nayaknishant** [comment]
Closing issue. Feel free to re-open if there are further questions.
