### ISSUE TITLE
Model.batch_predict with sync=False waits till batch prediction completed

### ISSUE THREAD

**Issue by havryliuk** [googleapis/python-aiplatform#1793]
#### Environment details

  - OS type and version:
  Windows 10 
  - Python version: `python --version`
  3.10.8
  - pip version: `pip --version`
  22.2.2
  - `google-cloud-aiplatform` version: `pip show google-cloud-aiplatform`
  1.18.3

#### Steps to reproduce

  1. Create a new batch prediction inside a pipeline component with `sync=False`. According to the documentation, `If False, this method will be executed in concurrent Future and any downstream object will be immediately returned and synced when the Future has completed.`
  2. When the pipeline is submitted and the component creates a batch prediction, the pipeline waits till the batch prediction is completed. I expect that the pipeline will create a batch prediction and exit without waiting for batch prediction.

#### Code example

```python
model.batch_predict(
        gcs_source=gcs_source,
        gcs_destination_prefix=gcs_destination,
        machine_type='n1-standard-4',
        instances_format='csv',
        sync=False
    )
```

Vertex AI pipeline log:

![image](https://user-images.githubusercontent.com/1567804/201663288-fd1771c2-9ff3-44a2-9276-898754c47f46.png)

**Comment by jaycee-li** [comment]
Hi @havryliuk ,

`sync=False` allows you run the `model.batch_predict` asynchronously, which means you can execute other codes or submit other jobs without waiting until this batch prediction job completed.

The pipeline run is created when you submit the batch prediction job. It ends when the job is completed.

**Comment by havryliuk** [comment]
Thank you for your answer, @jaycee-li !
I know this is not directly related to this issue, but is there a way to programmatically end a pipeline?

**Comment by jaycee-li** [comment]
Hi @havryliuk ,

The pipeline is complete(in `succeeded` or `failed` status) when the job is done. If you want to end a pipeline while the job is running, you can call `job.cancel()`.

**Comment by havryliuk** [comment]
Thanks a lot!
Closing this issue.
