### ISSUE TITLE
Is there any plan to upgrade google-cloud-bigquery dependency to v3?

### ISSUE THREAD

**Issue by skatsuta** [googleapis/python-aiplatform#1813]
Hi team, thanks for providing this convenient client library!

**Is your feature request related to a problem? Please describe.**

We use google-cloud-bigquery and google-cloud-aiplatform together in our ML application.
Since the current aiplatform library depends on bigquery v2 only, we cannot upgrade it to v3.

**Describe the solution you'd like**

Is there any plan to upgrade bigquery library dependency to v3?
v3 has added many features and improved type hint support, so we'd appreciate it if aiplatform could add support for bigquery v3.

Thanks!

**Comment by rosiezou** [comment]
@skatsuta will address this in #1821

**Comment by skatsuta** [comment]
Thanks a lot! v3 has some breaking changes, so a few fixes may be necessary on the part of this library.
I will close this issue once the PR has been merged!
