### ISSUE TITLE
"aiplatform.googleapis.com/annotation_set_name" ignored when importing data

### ISSUE THREAD

**Issue by Simon-Ince** [googleapis/python-aiplatform#1829]
Importing this jsonl file via the Vertex Dataset web UI (import tab) will add the image to the existing "8749834369004208128" Annotation Set, whereas passing the same file to the `import_data` method of `ImageDataset` will cause a new randomly generated Annotation Set to be created, ignoring the one specified by "aiplatform.googleapis.com/annotation_set_name"  in the file.

jsonl:

```
{
  "imageGcsUri": "gs://lens-vertex-stg-feeder-bucket/730fbcd0086092e49c4093b659f1f590.png",
  "classificationAnnotation": {
    "displayName": "test",
    "annotationResourceLabels": {
      "aiplatform.googleapis.com/annotation_set_name": "8749834369004208128"
    }
  },
  "dataItemResourceLabels": {}
}
```

Python:
```
dataset_id = os.environ.get("DATASET_ID")

def image_dataset_import_data(
        # list of gs uris for the jsonl data import files
        src_uris: list,
):
    ds = aiplatform.ImageDataset(dataset_id)

    ds = ds.import_data(
        gcs_source=src_uris,
        # import schema definition
        import_schema_uri=aiplatform.schema.dataset.ioformat.image.single_label_classification,
        sync=True,
    )
    return ds

```

**Comment by jaycee-li** [comment]
Hi @Simon-Ince ,

Currently this `annotationResourceLabels` field is not publicly enabled, so you can only use UI to import data to an existing annotation set. 

But this feature will be available soon in SDK, maybe in the Jan 2023 release. At that time your code should work. And we'll introduce a new field `annotation_labels` to `ds.import_data(...)`, which also allows users to specify the annotation set.

**Comment by jaycee-li** [comment]
Feel free to re-open if you have any other questions.

**Comment by longnx195** [comment]
Hi @jaycee-li 
Have any chance for this `annotationResourceLabels ` property work soon? Because it still did not work right now. 

And i also researched about field `annotation_labels`, this field contain KEY and VALUE but the documentation does not clearly describe the KEY and VALUE it required.

**Comment by willlahr** [comment]
@jaycee-li  was this feature ever released?   It doesn't seem to be available as a field in  ds.import_data(...).  This is what I assumed you mean but perhaps I've misunderstood.  

`        dataset.import_data( gcs_source=[f"gs://{bucket_name}/{jsonl_file_name}"], import_schema_uri='gs://google-cloud-aiplatform/schema/dataset/ioformat/image_bounding_box_io_format_1.0.0.yaml', annotation_labels="1197440730415497216")
`
Being able to add data to an existing dataset through the API would be very useful to us operationally here

**Comment by yinghsienwu** [comment]
Thanks for the feedback. We currently don't have bandwidth to support this. Please feel free to contribute a PR if you still want this feature. Thanks again!
