### ISSUE TITLE
Move generated code into google.cloud.aiplatform.gapic

### ISSUE THREAD

**Issue by busunkim96** [googleapis/python-aiplatform#19]
See discussion in https://github.com/googleapis/python-aiplatform/pull/17.

Not clear at the moment how to do this via the Microgenerator Docker image.

**Comment by sasha-gitg** [comment]
@busunkim96 Is this still required? Or can this issue be closed?

context: https://github.com/googleapis/python-aiplatform/blob/main/google/cloud/aiplatform/gapic/__init__.py
