### ISSUE TITLE
endpoint Response size to large

### ISSUE THREAD

**Issue by khu834** [googleapis/python-aiplatform#190]
I have a working model endpoint deployed on the AI Platform (Unified).
However, the response size is exceeding the maximum allowed by the gRPC max message setting.
How can I increase this limit of the tensorflow server running on the endpoint?

#### Environment details

  - OS type and version:
  - Python version: `python --version`
  - pip version: `pip --version`
  - `google-cloud-aiplatform` version: `pip show google-cloud-aiplatform`

#### Steps to reproduce

  1. Deployed an objection detection model trained from the tensorflow/models repository on the AI Platform (Unified)
  2. Send a single base64 encoded image using the aiplatform prediction client.

#### Code example

```python

with open(filename, "rb") as f:
    file_content = f.read()

encoded_content = base64.urlsafe_b64encode(file_content).decode("utf-8")
instances = [{"input_tensor": encoded_content}]
parameters_dict = {}
parameters = json_format.ParseDict(parameters_dict, Value())
endpoint = client.endpoint_path(
    project=project, location=location, endpoint=endpoint_id
)
response = client.predict(
    endpoint=endpoint, instances=instances, parameters=parameters,
)
```

#### Stack trace
```
InvalidArgument: 400 Failed to handle request. endpoint_id: 3414397020616523776, deployed_model_id: 7183628433748918272 with error: `Response size too large. Received at least 3288694 bytes; max is 2000000.`
```

**Comment by dizcology** [comment]
Hello @khu834: Thank you for reporting the issue.  That looks like the response size limitation currently imposed by the service.  At the moment you might need to explore options of reducing the response the TensorFlow model returns.

Is this the model you were using?  https://github.com/tensorflow/models/tree/master/official/vision/detection

**Comment by khu834** [comment]
Hi Yu-Han:

Ok, thanks for that information.
I just wanted to know if the response size is fixed using the
endpoint service.
We will look to doing some post-processing to trim the response size.

We are using some of the models in the tensorflow/models/research library.
Thank you. I think we can close this ticket now.

-Kevin

**Comment by dizcology** [comment]
Thank you @khu834, yes at the moment the response size is limited to ~2Mb as you saw in the error message.
