### ISSUE TITLE
Correct "Fitler" typo in samples

### ISSUE THREAD

**Issue by nicain** [googleapis/python-aiplatform#1942]
XREF b/267786201

Correct "fitler" to "filter" in aiplatform_sdk_create_artifact_with_sdk_sample and aiplatform_sdk_create_execution_with_sdk_sample

**Comment by nicain** [comment]
Fix PR closed, so that the issue can be corrected upstream. Ill leave issue open until that change is made.

**Comment by meredithslota** [comment]
Is there a link to the upstream fix issue?
