### ISSUE TITLE
Return `ClassificationMetrics` artifact on function `log_classification_metrics()`

### ISSUE THREAD

**Issue by igonro** [googleapis/python-aiplatform#1946]
I think it would be very useful to have the artifact item returned when I call `log_classification_metrics()`, because this way it would be possible to link this as output artifacts (with `assign_output_artifacts()`).

https://github.com/googleapis/python-aiplatform/blob/96e9e1239ae13e70b9b8ae929f7343155efe3e22/google/cloud/aiplatform/metadata/experiment_run_resource.py#L1095-L1099

**Comment by ZhenyiQ** [comment]
Thanks for the feedback! The artifact is returned now.

**Comment by igonro** [comment]
Thanks @ZhenyiQ
