### ISSUE TITLE
Endpoint network attribute 

### ISSUE THREAD

**Issue by WaterKnight1998** [googleapis/python-aiplatform#1965]
Hi,

The `network` attribute of the private `_create` method of Endpoint class should be accessible by the end user of the sdk. Thats why you need to expose this arg in public API.

Best regards,
David

**Comment by nayaknishant** [comment]
Hi @WaterKnight1998, so the private _create() method is the underlying helper method for both Endpoint and PrivateEndpoint. The network arg is available in the PrivateEndpoint class (which needs a specified private network) but not by the Endpoint class (which uses the public network).

Hope this helps,
Nishant
