### ISSUE TITLE
[Feature request] Provide a feature for incrementally uploading models using a single function

### ISSUE THREAD

**Issue by Rstar1998** [googleapis/python-aiplatform#1982]
Considering use cases where we need to upload ML models incrementally and version it in vertex ai , there needs a function to create i a model with that name if it doesnot exists and if it exists than incrementally upload it. As of now we have to use something like this in order to achieve incrementally model uploading. 

`

        aiplatform.init(project="", location="")
        model_list = [ model_ele.name for model_ele in aiplatform.Model.list( filter='display_name="chat-gpt-model"', ) ]
        
        if  len(model_list) > 0:
            model = aiplatform.Model.upload(
                    display_name="chat-gpt-model",
                    parent_model=model_list[0],
                    is_default_version=True,
                    artifact_uri="gs://...",
                    serving_container_image_uri="",
                    serving_container_predict_route="/predict",
                    serving_container_health_route="/health",
                    description="Model description increment load"
                )
        else:
            model = aiplatform.Model.upload(
                    display_name="chat-gpt-model",
                    artifact_uri="gs://../",
                    serving_container_image_uri="",
                    serving_container_predict_route="/predict",
                    serving_container_health_route="/health",
                    description="Model description first time load"
                )
        
        model.wait()

`

**Comment by nayaknishant** [comment]
Hi @Rstar1998, this is possible with model versioning, please take a look at: https://cloud.google.com/vertex-ai/docs/model-registry/versioning
