### ISSUE TITLE
Jupyter Notebooks on Vertex AI Workbench prompts for `password` when using `sudo`

### ISSUE THREAD

**Issue by gomrinal** [googleapis/python-aiplatform#1992]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-aiplatform/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version:
  - Python version: `python --version`
  - pip version: `pip --version`
  - `google-cloud-aiplatform` version: `pip show google-cloud-aiplatform`

#### Steps to reproduce

  1.  Create any managed notebook on vertex ai workbench using GUI
  2. Try installing any library for ex ```sudo apt install iputils-ping```
  3. It asks for a password. What would be the password if the notebooks are created via service account?
  
Can you provide `sudo` permissions by default when somebody spins up vertex ai notebook?

It seems like a long standing issue people are facing in Vertex AI workbench. In this following some people have tried with CLI however it would be better if either root access is given by default or UI has option to select it as well as most of our users prefer UI for spinning notebooks rather than CLI.

https://stackoverflow.com/questions/66994050/how-do-i-get-root-access-to-ai-platform-notebook-within-gcp

#### Code example

```python
Not using code. Just using GUI to spin up managed and user managed notebooks
```

**Comment by nchien2** [comment]
I am also running into this issue. Did you ever find a workaround or fix?

**Comment by gomrinal** [comment]
No workaround as of now! Only option I see is by creating a notebook on workbench using cli? (Haven't tried yet)

**Comment by gomrinal** [comment]
![Screenshot 2023-05-09 at 12 46 42 PM](https://github.com/googleapis/python-aiplatform/assets/29385581/0f9cddee-8192-41a8-b898-72c5b1368317)
Finally It's here folks! @nchien2

**Comment by WarrenGreen** [comment]
@gomrinal Where is this option?

**Comment by mzhou-mailchimp** [comment]
The checkbox is in the advanced options (during the creation of your notebook) -> IAM & Security section.

**Comment by jedi4ever** [comment]
The option is only for User Managed Notebook Instances

**Comment by happyeungin** [comment]
> The option is only for User Managed Notebook Instances

There is no such option under security.

**Comment by GameboyColor32** [comment]
> > The option is only for User Managed Notebook Instances
> 
> There is no such option under security.

There is, but only for user manager notebooks, under advanced options
