### ISSUE TITLE
Vertex AI Pipelines Runner broken with urllib3

### ISSUE THREAD

**Issue by Davidnet** [googleapis/python-aiplatform#2167]
See also report in: [kubeflow pipelines](https://github.com/kubeflow/pipelines/issues/9326)

#### Environment details

  - OS type and version:
  - Python version: 3.11 # python version does not matter

#### Steps to reproduce

I have created a repo that with the only dependency being: `kfp[all]==2.0.0b15` and run this component:

```
# %%
from kfp import dsl


@dsl.component
def print_component(str_exmpl: str) -> None:
    print(str_exmpl)


@dsl.pipeline
def pipeline():
    print_task = print_component(str_exmpl="Hello World!")


if __name__ == "__main__":
    import kfp

    print(kfp.__version__)
    kfp.compiler.Compiler().compile(pipeline, "pipeline.yaml")
```

This fails:

```
Traceback (most recent call last):
  File "/home/davidnet/.pyenv/versions/issue-kubeflow/lib/python3.11/site-packages/requests_toolbelt/_compat.py", line 48, in <module>
    from requests.packages.urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (/home/davidnet/.pyenv/versions/issue-kubeflow/lib/python3.11/site-packages/urllib3/contrib/__init__.py)
```
This is tracked in the repo: [branch issue/compile](https://github.com/Davidnet/kubeflow_request_issue/tree/issue/compile)
Now, pinning the urllib dependency:

```
$ cat requirements.txt
kfp[all]==2.0.0b15
urllib3==1.26.15
```

Makes the pipeline compile. but then when running on **vertex it** fails :
```
"message": "ImportError: cannot import name 'appengine' from 'urllib3.contrib' (/usr/local/lib/python3.7/site-packages/urllib3/contrib/__init__.py)",
```
With the same component.

Now technically all my pipelines are failing and the only solution we think with our team is to pin urllib in each lightweight component.

This is tracked in this repo (both logs, and the compiled yaml can be found) in [here](https://github.com/Davidnet/kubeflow_request_issue/tree/issue/running) branch issue/running

The logs here have the information when running in Vertex AI Pipelines: 

[gcp logs.json](https://github.com/Davidnet/kubeflow_request_issue/blob/issue/running/logs.json)

**Comment by matthew29tang** [comment]
Is this issue resolved now with https://github.com/kubeflow/pipelines/pull/9323 merged in?

**Comment by Davidnet** [comment]
Yes thank you
