### ISSUE TITLE
[Docs] Embedding Model Name example updated with latest release

### ISSUE THREAD

**Issue by kmaphoenix** [googleapis/python-aiplatform#2205]
Very minor update.  
In the latest release, the model import name for TextEmbeddingModel has updated from `embedding-gecko@001` -> `textembedding-gecko@001`.  

Submitting a PR to fix this in the docs.

**Comment by kmaphoenix** [comment]
PR: #2207

**Comment by matthew29tang** [comment]
Closing since this was just fixed in this commit[1].

[1]: https://github.com/googleapis/python-aiplatform/commit/88246293a8a4ba94a13106bc99044129674fd15e
