### ISSUE TITLE
Reading index datapoints within VPC network issue in Matching Engine

### ISSUE THREAD

**Issue by matthewsparr** [googleapis/python-aiplatform#2228]
I have a deployed Index with an Index Endpoint created with a VPC network. I'm able to use `MatchingEngineIndexEndpoint` and `.match()` to run queries and it works as expected (I am running this inside a Workbench notebook).

I'm wanting to read specific datapoints and tried using `read_index_datapoints()` as below:

```
index_endpoint = MatchingEngineIndexEndpoint(INDEX_ID)
index_endpoint.read_index_datapoints(deployed_index_id=DEPLOYED_INDEX_ID, ids=[item_id1, item_id2])
```

It appears that method is only supported when there's a public url as it gives this error:

```
AttributeError: 'MatchingEngineIndexEndpoint' object has no attribute '_public_match_client'
```

I tried instead to use the `MatchServiceClient` from `aiplatform_v1beta1`:

```
from google.cloud.aiplatform_v1beta1.services.match_service import MatchServiceClient
from google.cloud.aiplatform_v1beta1.types.match_service import ReadIndexDatapointsRequest

INDEX_ID = f"projects/{PROJECT_ID}/locations/us-west1/indexEndpoints/{INDEX_ENDPOINT_ID}"

client_options = {
  "api_endpoint": f"{REGION}-aiplatform.googleapis.com"
}

match_client = MatchServiceClient(client_options=client_options)

read_datapoints_request = ReadIndexDatapointsRequest(
    index_endpoint=INDEX_ID, 
    deployed_index_id=DEPLOYED_INDEX_ID,
    ids=[item_id1, item_id2]
)

match_client.read_index_datapoints(request=read_datapoints_request)
```

But I get this error:

```
MethodNotImplemented: 501 Operation is not implemented, or supported, or enabled.
```

Is there a different way to lookup index datapoints for a VPC hosted endpoint?

## Specifications

- Version: `1.25.0`

**Comment by thundercat1** [comment]
+1 - the [docs include an example](https://cloud.google.com/vertex-ai/docs/matching-engine/query-index-vpc#:~:text=query%20using%20a-,DOC_ID,-%2C%20use%20the%20following) of querying by document ID with the grpc cli, but the python client seems like it might be missing this.

**Comment by eddie-scio** [comment]
It would be great to have this!  It'll unblock some of our use cases that require item lookups (with Python API, on VPC)

**Comment by sshcherbakov** [comment]
Getting the same error just following the default Python example at https://cloud.google.com/vertex-ai/docs/vector-search/quickstart :
```
PROJECT_ID="my_project_id"
PROJECT_NUMBER="811111111111"
LOCATION="europe-west3"
INDEX_ENDPOINT_NAME="test-index-endpoint"
INDEX_ENDPOINT_ID="4444444444444444444"
DEPLOYED_INDEX_ID="my_deployed_test_index"

aiplatform.init(project=PROJECT_ID, location=LOCATION)

my_index_endpoint = aiplatform.MatchingEngineIndexEndpoint(
    index_endpoint_name = INDEX_ENDPOINT_ID,
    project = PROJECT_NUMBER,
    location = LOCATION
)


product_names = {}
product_embs = {}
with open('product-embs.json') as f:
    for l in f.readlines():
        p = json.loads(l)
        id = p['id']
        product_names[id] = p['name']
        product_embs[id] = p['embedding']

query_emb = product_embs['6523']

response = my_index_endpoint.find_neighbors(
    deployed_index_id = DEPLOYED_INDEX_ID,
    queries = [query_emb],
    num_neighbors = 10
)

for idx, neighbor in enumerate(response[0]):
    print(f"{neighbor.distance:.2f} {product_names[neighbor.id]}")
```

**Comment by tottenjordan** [comment]
@matthewsparr is your workbench instance also within the same VPC?

**Comment by kazunori279** [comment]
@sshcherbakov The example works with a public endpoint, not with a VPC. We will add a note to the sample code.

**Comment by Ludovic-Emo-Pyl-Tech** [comment]
+1

The query example page provided with a VPC are using low level grpc calls: https://cloud.google.com/vertex-ai/docs/vector-search/query-index-vpc

The query example page for a public endpoint is using python:
https://cloud.google.com/vertex-ai/docs/vector-search/query-index-public-endpoint

Would someone have a working example in a VPC context in python in Cloud Run ? 
We have tried to do it but could not achieve it so far.

**Comment by lingyinw** [comment]
read_index_datapoints() now support private service access endpoints, please update to or later https://pypi.org/project/google-cloud-aiplatform/1.38.0/.
