### ISSUE TITLE
TextGenerationModel tune_model() call fails with PermissionError

### ISSUE THREAD

**Issue by Dmitrii-Shutenkov** [googleapis/python-aiplatform#2233]
Environment details
Python version: 3.11.3
pip version: 23.1.2
OS Windows 11

tune_model() call on TextGenerationModel causes "PermissionError: [Errno 13] Permission denied:"
The problem is in the 
https://github.com/googleapis/python-aiplatform/blob/1d56b850b9491ada81ec9c2509d7f7bd2d906b8f/vertexai/language_models/_language_models.py#L788

The code opens a temporary file and then passes the file path to df.to_json() which tries to open the file again and fails.

A simple experiment confirms the source of the problem:
>>> ff = tempfile.NamedTemporaryFile()
>>> df.to_json(path_or_buf=ff, orient="records", lines=True)
>>> ff.name
'C:\\tmp\\tmpswn4n9hv'

>>> ff = tempfile.NamedTemporaryFile()
>>> df.to_json(path_or_buf=ff.name, orient="records", lines=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python311\Lib\site-packages\pandas\core\generic.py", line 2532, in to_json
    return json.to_json(
           ^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pandas\io\json\_json.py", line 198, in to_json
    with get_handle(
         ^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pandas\io\common.py", line 859, in get_handle
    handle = open(
             ^^^^^

**Comment by Ark-kun** [comment]
This issue has been fixed.
