### ISSUE TITLE
Parameters passed to start_chat() are ignored

### ISSUE THREAD

**Issue by khallbobo** [googleapis/python-aiplatform#2263]
When passing parameters (top_p, top_k, max_output_tokens) to the constructor, they will be ignored when sending messages with send_message().  send_message() explicitly defaults to global variables and never uses those from the class variables.  The only way to get them to be used it to also pass parameters to send_message with values to evaluate to False (0 or 0.0).  This has lead to a bug in the langchain() usage as there was an assumption that setting parameters in the constructor would be used.

https://github.com/googleapis/python-aiplatform/blob/50e08989b495a2ec9c51af3c64485ee0dd4b0ba2/vertexai/language_models/_language_models.py#L451

**Comment by Ark-kun** [comment]
This issue should be fixed in v1.26.0
