### ISSUE TITLE
start_upload_tb_log doesn't accept tensorboard_id from VertexAI 

### ISSUE THREAD

**Issue by tsveti-iko** [googleapis/python-aiplatform#2319]
`aiplatform.start_upload_tb_log()` doesn't accept a `tensorboard_id` that is created by VertexAI. 

Following the official documentation: https://cloud.google.com/vertex-ai/docs/experiments/tensorboard-overview#continuous-monitoring I use the same code snipped from the documentation above and get the `TENSORBOARD_ID` from the Vertex AI Experiments page. The `TENSORBOARD_ID` is in the following format: "190435413930803211". 
When I run `aiplatform.start_upload_tb_log()` I get the following error:

```
Traceback (most recent call last):
  File "/home/tsveti/venvs/python_3_10/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/tsveti/venvs/python_3_10/lib/python3.10/site-packages/grpc/_channel.py", line 1030, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/tsveti/venvs/python_3_10/lib/python3.10/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "List of found errors:	1.Field: tensorboard_experiment_id; Message: Valid characters are '[a-z][0-9]-'.	"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:216.58.214.10:443 {grpc_message:"List of found errors:\t1.Field: tensorboard_experiment_id; Message: Valid characters are \'[a-z][0-9]-\'.\t", grpc_status:3, created_time:"2023-06-22T17:49:31.835590934+02:00"}"
```

The version of the `google_cloud_pipeline_components` I used is '2.0.0', but I also tried with version '1.0.44' and got the same error.

I need to run the TensorBoard continuous monitoring for VertexAI experiments. Please help.

**Comment by wjessG** [comment]
Hi - Reading through the error message, the field that is missing is tensorboard_experiment_name, which is a String, and it should follow regex [a-z][0-9]-. Tensorboard ID and tensorboard_experiment are two different parameters. One tensorboard_id can include multiple tensorboard_experiments. 
The tensorboard_id field is set correctly.

**Comment by kgalias** [comment]
How can I find the appropriate `tensorboard_experiment_name`?
