### ISSUE TITLE
Unable to link pipeline schedule with compiled pipeline artifact in Artifact Registry when using the SDK

### ISSUE THREAD

**Issue by jasonbrancazio** [googleapis/python-aiplatform#2342]
After I create a pipeline schedule using the UI in the Vertex AI console, I can visit the schedules tab of the pipelines page and see that the schedule linked to a pipeline template stored in an Artifact Registry repository.

When I provide the same Artifact Registry repository path, including the sha256 hash, in the template_path argument of an aiplatform.PipelineJob, then create a PipelineJobSchedule and use PipelineJobSchedule.create to create the schedule, I don't see the schedule linked to the pipeline template stored in Artifact Registry.

My code looks something like this:

```
from google.cloud import aiplatform
from google.cloud.aiplatform.preview.pipelinejobschedule.pipeline_job_schedules import PipelineJobSchedule

project="my-project"
region="us-central1"
pipelines_repository = "repository-name"

# package name and package version are returned by kfp.Registry.RegistryClient.upload_pipeline
package_name = "repository-subdir"
package_version = "sha256:some_hash"

pipeline_job = aiplatform.PipelineJob(
    display_name="some-name",
    template_path=f"https://{region}-kfp.pkg.dev/{project}/{pipelines_repository}/{package_name}/{package_version}",
    pipeline_root="some_gs_path",
    enable_caching=False,
    project=project,
    location=region
)

schedule = PipelineJobSchedule(
    pipeline_job=pipeline_job,
    display_name="some-schedule-name",
    project=project,
    location=region
)

schedule.create(
    cron_expression="some-cron-expression",
    end_time="some-timestamp",
    service_account="some-service-account"
)

**Comment by jasonbrancazio** [comment]
Here is a screenshot. Note the inconsistency in the column on the right. The schedule row displaying the link was created with the UI, and the row without was created with the SDK.

<img width="555" alt="ui_inconsistency" src="https://github.com/googleapis/python-aiplatform/assets/22603787/1a7ce8a8-3f65-40ed-82b3-a1a935975e78">

**Comment by KevinGrantLee** [comment]
Thanks for bringing this issue up, I've submitted a fix and it should be included in next month's release.
