### ISSUE TITLE
Outdated version of Shapely

### ISSUE THREAD

**Issue by antoineleclair** [googleapis/python-aiplatform#2470]
The current requirements in `setup.py` include `shapely < 2.0.0`.

https://github.com/googleapis/python-aiplatform/blob/db518b0552a8900ca6a84a73ca711b775c786e92/setup.py#L146

The version `2.0.0` of Shapely has been released in December 2022.

https://pypi.org/project/shapely/#history

It would be great to update the dependency, so that users of your package that also depend on shapely directly don't have to use an outdated version.

**Comment by sararob** [comment]
We pinned the Shapely version because of a dependency issue with Colab (https://github.com/googleapis/python-aiplatform/pull/1860). I'll check if this is still an issue and see about updating the Shapely version.

**Comment by ianpegg-bc** [comment]
This issue is affecting us. We use shapely 2 and apache beam python SDK. The latest beam requires `google-cloud-aiplatform==1.31.1`, which requires `shapely<2`. This is blocking our upgrade to `apache-beam[gcp]==2.50.0`.

**Comment by computas-kwa** [comment]
Any news on this?
