### ISSUE TITLE
In version 1.31.0, logs are not being output to the stdout

### ISSUE THREAD

**Issue by yutatanamoto** [googleapis/python-aiplatform#2497]
#### Environment details
  - OS type and version: macOS 13.3
  - Python version: 3.11.2
  - pip version: 23.1
  - `google-cloud-aiplatform` version: 1.31.0

#### Steps to reproduce

1. Execute method that produce `INFO` level logs（e.g. `PipelineJob#submit`）.
    - I provided the details in the "Code example" section.
2. Confirm that the expected logs are not being output to stdout.

#### Code example

```bash
$ pip install google-cloud-aiplatform==1.30.1  kfp==1.8.22
$ python example.py
```

```python
# example.py
from google.cloud import aiplatform
from kfp.v2 import compiler
from kfp.v2.dsl import component, pipeline

PROJECT_ID = "YOUR_PROJECT_ID"
PIPELINE_ROOT = "YOUR_PIPELINE_ROOT"
PIPELINE_TEMPLATE_PATH = "example_pipeline.json"
PIPELINE_DISPLAY_NAME="example_pipeline"


@component(base_image="python:3.9")
def do_nothing():
    return


@pipeline(name="example-pipeline", pipeline_root=PIPELINE_ROOT)
def pipeline():
    do_nothing()


compiler.Compiler().compile(pipeline_func=pipeline, package_path=PIPELINE_TEMPLATE_PATH)

job = aiplatform.PipelineJob(
    display_name=PIPELINE_DISPLAY_NAME,
    template_path=PIPELINE_TEMPLATE_PATH,
    pipeline_root=PIPELINE_ROOT,
    project=YOUR_PROJECT_ID
)

# By calling this method, INFO-level log like `View Pipeline Job: https://...` should be generated.
job.submit()
```

#### Investigation and possible cause
Since this issue didn't occur in v1.30.1, I checked the differences between 1.30.1 and 1.31.0.（ref: https://github.com/googleapis/python-aiplatform/compare/v1.30.1...v1.31.0 ）
Based on this diff comparison, I suspect that the **changes in #2417 might have caused the inability to configure the `StreamHandler` for logging to stdout**.

**Comment by matthew29tang** [comment]
What environment are you using the SDK in? I verified that the logs appear in Colab from my end on v1.31.0

**Comment by yutatanamoto** [comment]
@matthew29tang 
Thank you for your quick response. 🙏 

> What environment are you using the SDK in?

I am using the SDK in my local machine(not in Colab).

> I verified that the logs appear in Colab from my end on v1.31.0

I can confirm the logs are visible on Colab, but in my local machine, I still cannot observe the logs.

Just a side note, if i downgrade to version 1.30.1, logs will become visible on my local machine. However, in Colab, logs will unfortunately start appearing duplicated (I think that #2417 was created to resolve this problem).

**Comment by yutatanamoto** [comment]
> I still cannot observe the logs.

Exactly, the situation is that only logs below INFO level are not displayed. On the other hand, logs of WARN level and above are shown, but I believe this is due to the lastResort handler.

**Comment by matthew29tang** [comment]
Thanks for investigating on your end. I'm able to reproduce the missing logs on 1.31 running on local environment. I'm working on a fix which will go out next release.

**Comment by yutatanamoto** [comment]
The issue #2474  might have the same underlying cause as well.

**Comment by matthew29tang** [comment]
#2529 resolves the issue and will be included in the next release.
