### ISSUE TITLE
AttributeError: module 'google.cloud.aiplatform.gapic' has no attribute 'QueryEndpointRequest'

### ISSUE THREAD

**Issue by joybrotodey-clousufi** [googleapis/python-aiplatform#2515]
Thanks for stopping by to let us know something could be better!

I am having an issues:

- `google-cloud-aiplatform` version: 23.3.1

query_instance = aiplatform.gapic.QueryEndpointRequest(
AttributeError: module 'google.cloud.aiplatform.gapic' has no attribute 'QueryEndpointRequest'

Please suggest the needful.

Thanks!

**Comment by joybrotodey-clousufi** [comment]
Please suggest the correct attribute.

**Comment by matthew29tang** [comment]
Could you provide more context of what you are trying to accomplish / where you got the example code snippet from?

Also, the version number seems incorrect. The leading number should start with 1, see this page for the releases: https://github.com/googleapis/python-aiplatform/tags
