### ISSUE TITLE
Vertex AI Matching Engine Retrieval: grpc_status:14

### ISSUE THREAD

**Issue by joybrotodey-clousufi** [googleapis/python-aiplatform#2516]
Thanks for stopping by to let us know something could be better!

Issue is being observed for the following:

from langchain.chains import RetrievalQA
qa = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=retriever,
    return_source_documents=True)

query="Query"
result = qa({"query": 'Query'})

   raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "DNS resolution failed for :10000: UNKNOWN: unparseable host:port: ':10000'"
	debug_error_string = "UNKNOWN:DNS resolution failed for :10000: UNKNOWN: unparseable host:port: ':10000' {created_time:"2023-08-28T06:09:44.442256019+00:00", grpc_status:14}"

Thanks!

**Comment by matthew29tang** [comment]
The error is quite vague, where did you get this code from? I would suggest that you use this sample notebook: https://github.com/GoogleCloudPlatform/generative-ai/blob/main/language/use-cases/document-qa/question_answering_documents_langchain_matching_engine.ipynb

**Comment by samkorn-acuitymd** [comment]
I'm getting pretty much exactly the same error when I try to query a matching engine endpoint (nothing to do with langchain). It looks like it's some sort of issue with gRPC host port formatting.

I'm running the following code:
```
response = index_endpoint.match(
    deployed_index_id=deployed_index_id,
    queries=[sample_embedding],
    num_neighbors=10
)
```
 And I get the error:
```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "DNS resolution failed for :10000: unparseable host:port"
        debug_error_string = "UNKNOWN:DNS resolution failed for :10000: unparseable host:port {created_time:"2023-08-29T15:02:49.304003-04:00", grpc_status:14}"
```
Here's a snippet of my libraries (let me know if there are other relevant ones I should include):
```
google-api-core==2.11.0
google-api-python-client==2.79.0
google-cloud==0.34.0
google-cloud-aiplatform==1.31.1
googleapis-common-protos==1.58.0
grpc-google-iam-v1==0.12.6
grpcio==1.57.0
grpcio-health-checking==1.47.5
grpcio-status==1.47.2
grpclib==0.4.3
```

**Comment by matthew29tang** [comment]
`match()` is to be used for a private endpoint, while `find_neighbors()` is meant to be used for a public endpoint (1).

If you are trying to use it in the context of langchain, it looks like there is an open PR to fix this issue: https://github.com/langchain-ai/langchain/issues/8378

(1): https://github.com/googleapis/python-aiplatform/blob/main/google/cloud/aiplatform/matching_engine/matching_engine_index_endpoint.py#L960
