### ISSUE TITLE
Tunable support of CodeGenerationModel

### ISSUE THREAD

**Issue by jk1333** [googleapis/python-aiplatform#2523]
#### Environment details

  - OS type and version:
  - Python version: 3.10
  - pip version: 23.2.1
  - `google-cloud-aiplatform` version: 1.31.0

#### Code example

```python
# example
vertexai.init()
model = CodeGenerationModel.from_pretrained("code-bison")
model.list_tuned_model_names()   # Not Implemented
```

Code-bison model now turned tunable feature
But sdk still remails which it as not tunable.

**Comment by Ark-kun** [comment]
The feature is still in preview. So you need to import the class from the preview module:

`from vertexai.preview.language_models import CodeGenerationModel`

**Comment by matthew29tang** [comment]
Additionally, please ensure that you have tuned the model first, or else `model.list_tuned_model_names()` will not list anything

**Comment by jk1333** [comment]
Thanks team, I checked it working after changing package name and specify version number.
Just use of "code-bison" or "text-bison" doesn't return tuned models because tuning is based on specific version of models.
"code-bison@001" or "text-bison@001" is required for dealing with models.
