### ISSUE TITLE
Remove upper bound on FastAPI dependency

### ISSUE THREAD

**Issue by jmayo-benchsci** [googleapis/python-aiplatform#2541]
https://github.com/googleapis/python-aiplatform/blob/0fb50c7dc4e8a6ce6895ec2850d042b0a71ec93d/setup.py#L76

It looks like the fix has been implemented upstream.

**Comment by matthew29tang** [comment]
Thanks for bringing this to our attention, I'll verify if later versions of FastAPI work.

**Comment by matthew29tang** [comment]
Resolved in #2543
