### ISSUE TITLE
Cutting a release that includes 2e3090b9

### ISSUE THREAD

**Issue by samertm** [googleapis/python-aiplatform#2551]
Do you think you can cut a release that includes this commit? https://github.com/googleapis/python-aiplatform/commit/2e3090b9f1f81b543650ae6bad31ee91395c03a4

I was testing out the new textembeddings-gecko@latest model with task type specified, and I hit a "400 Invalid Argument" error because it was being passed in as taskType instead of task_type.

Thanks!

**Comment by sasha-gitg** [comment]
Done: https://github.com/googleapis/python-aiplatform/releases/tag/v1.32.0
