### ISSUE TITLE
Not able to see Model Hyper Parameter section in Model Properties Tab

### ISSUE THREAD

**Issue by catchlui** [googleapis/python-aiplatform#260]
Hello  -

When I am trying to trigger the model training using API end point through (Python. I have followed the snippet provided in the automl) I am able to see the model getting trained successfully. But i am not able to see the hyper paramter section in the model properties tab. This section i can find out if i am training the model through UI. 
I am using the same dataset
Model type : regression
It has a date column to break train ,test,val **split**
Objective is : default (RMSE)
The model performance for model trained through GUI is better than trained through the API (data and all other parameters are same)

I am missing out any other parameters which need to be included in the API.

**Comment by dizcology** [comment]
Hello @catchlui thanks for reporting the issue.  Looks like there are two separate issues here:

1. Certain information available in the UI is missing if a model is trained with the API, but viewed in the UI.
2. Model performance differs depending on trained through the UI or API.

We will look into #1.  As for #2, could you verify that these two models were trained with the same amount of time?  Training through the API and the UI are served by the same backend jobs and there should not be significant difference if all parameters are the same and the dataset is of sufficiently large size.

**Comment by catchlui** [comment]
Yes the model is trained with the same data and same amount of time..
Looks like hyper parameter tuning is not happening when the model is trained through API?

**Comment by dizcology** [comment]
The API supports create_hyperparameter_tuning_job as well, and we have some samples:

https://github.com/googleapis/python-aiplatform/blob/master/samples/snippets/create_hyperparameter_tuning_job_sample.py

https://github.com/googleapis/python-aiplatform/blob/master/samples/snippets/create_hyperparameter_tuning_job_python_package_sample.py

**Comment by dizcology** [comment]
However please note that the samples above are for "custom training", and not AutoML.  For AutoML I expect some form of hptuning happens under the hood.

**Comment by catchlui** [comment]
Yes exactly

**Comment by dizcology** [comment]
@catchlui to help us investigate the issue, could you include something like a screenshot of the missing information you were looking for in the UI.

**Comment by catchlui** [comment]
![Inkedissue_upload_LI](https://user-images.githubusercontent.com/4323100/110725713-0e093600-823e-11eb-9ea8-fc3e24685bda.jpg)
I have uploaded the screenshots. Please note i have blurred the dataset. But it's the same dataset in both the places.Only i have given it two different names. Also the training time is different. So i thought that might be issue , so i ran the API job for two hours and i saw some improvement in accuracy . But still not close enough and the hyperparameter section is missing

**Comment by dizcology** [comment]
Thank you @catchlui - this is super helpful!  We will look into it.

**Comment by catchlui** [comment]
any Update on this ?

**Comment by dizcology** [comment]
Hello @catchlui: we tracked down the issue and the fix should be either already rolled out, or will be soon.

**Comment by dizcology** [comment]
@catchlui This should be fixed by now.  Are you still experience the same issue?

**Comment by catchlui** [comment]
Yes...it's fixed thanks...
