### ISSUE TITLE
Feature: Include GenAI metadata in model.predict's output

### ISSUE THREAD

**Issue by cymarechal-devoteam** [googleapis/python-aiplatform#2639]
Hi,

[text-bison's API output schema](https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/text#response_body) contains a metadata field carrying important information:

``` bash
{
  "predictions": [ ... ],
  "metadata": {
    "tokenMetadata": {
      "input_token_count": {
        "total_tokens": integer,
        "total_billable_characters": integer
      },
      "output_token_count": {
        "total_tokens": integer,
        "total_billable_characters": integer
      }
    }
  }
}
```

Currently in the Python SDK, text generation models output a [TextGenerationResponse](https://cloud.google.com/python/docs/reference/aiplatform/latest/vertexai.preview.language_models.TextGenerationResponse) type. And while the response type contains a `_prediction_response` field, this one is a [aiplatform.models.Prediction](https://github.com/googleapis/python-aiplatform/blob/main/vertexai/language_models/_language_models.py#L619C42-L619C70). In other words, it does not contain the additional `metadata` field.

This metadata field is especially important for production-ready use cases, therefore emphasizing the importance of implementing this feature.

Is this of any interest to incorporate in the roadmap?

Thank you,
cymarechal

**Comment by matthew29tang** [comment]
#3301 resolves this feature request.
