### ISSUE TITLE
Invalid model id: codechat-bison@001 when finetuning code-chat-bison

### ISSUE THREAD

**Issue by rmuller-ml** [googleapis/python-aiplatform#2785]
#### Environment details

Colab

google-cloud-aiplatform in /usr/local/lib/python3.10/dist-packages (1.34.0)

#### Steps to reproduce

Follow tutorial to train codechat-bison model in [tune-code-models](https://cloud.google.com/vertex-ai/docs/generative-ai/models/tune-code-models#generative-ai-tune-model-drest)

#### Code example

```python
from google.colab import auth as google_auth
google_auth.authenticate_user()
import vertexai
from vertexai.preview.language_models import CodeChatModel
vertexai.init(project=MY_PROJECT, location="us-central1")
model = CodeChatModel.from_pretrained("codechat-bison@001")
model.tune_model(
    training_data=JSONL_TRAIN,
    train_steps=500,
    tuning_job_location="us-central1",
    tuned_model_location="us-central1",
)
```

#### Stack trace

Pipeline component **vertex-pipelines-prompt-validation** fails with **Invalid model id: codechat-bison@001 provided.**

**Comment by Ark-kun** [comment]
Thank you for the report. The underlying issue has been fixed.
