### ISSUE TITLE
Support shapely version >= 2.0

### ISSUE THREAD

**Issue by jzxu** [googleapis/python-aiplatform#2829]
AIPlatform Python API is currently incompatible with the shapely library versions >= 2.0. This was reported in https://github.com/googleapis/python-aiplatform/issues/1852. The fix was to pin the shapely version to <2.0, which is 1.8.

However, the performance of certain core functions in shapely 1.8 is orders of magnitude slower than in shapely >= 2.0 (https://shapely.readthedocs.io/en/stable/migration.html). For many geospatial projects such as mine (https://github.com/google-research/skai), the performance hit basically makes shapely unusable, which in turn makes the ubiquitous GeoPandas library unusable as well. Furthermore, GeoPandas will completely stop supporting shapely < 2.0 in the near future (https://geopandas.org/en/stable/about/roadmap.html).

Please update the aiplatform library to be compatible with shapely 2.0 so that geospatial projects that depend on GeoPandas can continue using the Python aiplatform API.

**Comment by nayaknishant** [comment]
Hi @jzxu, we updated the Shapely dependency in https://github.com/googleapis/python-bigquery/pull/1696 and it also been updated in this repository (https://github.com/googleapis/python-aiplatform/commit/e76abd3901644f99ec6850b35e155d8b2c54008a). Hopefully Shapely version >= 2.0 should be supported now, please let us know.

**Comment by jzxu** [comment]
Thank you for the fast response!
