### ISSUE TITLE
Remove dependency on setuptools

### ISSUE THREAD

**Issue by parthea** [googleapis/python-aiplatform#2931]
We should consider removing `setuptools` as a dependency and drop usage of `distutils` and `pkg_resources` to align with other `google-cloud-*` python packages where `setuptools` is not declared as a dependency. 

https://github.com/googleapis/python-aiplatform/blob/755c3f99478e537ef5675ed7120a17eaf94ee5cd/setup.py#L186

- For `distutils`, 
Aside from tests, `distutils` is only needed in `google/cloud/aiplatform/utils/prediction_utils.py`. We could migrate from `distutils.dir_util` to `shutil.copytree`
https://github.com/googleapis/python-aiplatform/blob/dcb62051a7f3aeaa009b64165569c788d8c5ec44/google/cloud/aiplatform/utils/prediction_utils.py#L18

- For `pkg_resources`,
Aside from tests, `pkg_resources` is only needed in `google/cloud/aiplatform/initializer.py`. We could migrate to use `google.cloud.aiplatform.__version__` instead of `pkg_resources.get_distribution("google-cloud-aiplatform").version`
https://github.com/googleapis/python-aiplatform/blob/dcb62051a7f3aeaa009b64165569c788d8c5ec44/google/cloud/aiplatform/initializer.py#L424-L426

**Comment by kitokirti** [comment]
Hi @parthea , please assign this to me.

**Comment by kitokirti** [comment]
Hi @parthea, we would require to remove the dependency of setuptools, as well as would need to migrate the distutils and pkg_resources in only those files which are mentioned in the PR.
Please clarify.

**Comment by parthea** [comment]
The run time dependency on `setuptools` can be removed as long as there is no usage of `pkg_resources` or `distutils` in this repository.

**Comment by kitokirti** [comment]
What would be the testing scenarios we are looking for?

**Comment by parthea** [comment]
The are presubmits which run once the PR reviewed. To run the presubmits locally, [use nox](https://github.com/googleapis/python-aiplatform/blob/main/CONTRIBUTING.rst#using-nox).

**Comment by kitokirti** [comment]
Thanks!

**Comment by TheKevJames** [comment]
I have #2419 open to solve the `pkg_resources` case, as well. Using `__version__` directly would also work, if y'all prefer! I went with the `importlib` approach instead. Feel free to steal my PR / merge it with your changes / delete it and do it differently / whatever!

**Comment by nayaknishant** [comment]
The `setuptools` runtime dependency still needs to be removed in [python-aiplatform/setup.py](https://github.com/googleapis/python-aiplatform/blob/755c3f99478e537ef5675ed7120a17eaf94ee5cd/setup.py#L186)
