### ISSUE TITLE
SDK should update text-bison tuning to v3.0?

### ISSUE THREAD

**Issue by jasonbrancazio** [googleapis/python-aiplatform#2982]
I'm not sure if this is a feature or a bug. When you launch a fine-tuning job for text-bison@001 with the cloud console, v3.0 of the tuning template is used. When you launch a tuning job with the python SDK, v2.0 is still used. This is confusing: as a user, I don't know if v3.0 enables extra features or would produce a better model.

I've traced the reason to the `_SHORT_MODEL_ID_TO_TUNING_PIPELINE_MAP` -  text-bison wasn't updated to 3.0 while all the others were.
https://github.com/googleapis/python-aiplatform/blob/main/vertexai/_model_garden/_model_garden_models.py#L36

https://github.com/googleapis/python-aiplatform/commit/9eba18f70d36ac3901ba8b580cde6dde04413bc3

@Ark-kun

**Comment by Ark-kun** [comment]
These templates are really the same. Initially 3.0 was not supposed to be used. So we did not update the text-bison pipeline. But I guess UX uses the 3.0 tag.
