### ISSUE TITLE
Add logprobs to TextGenerationResponse

### ISSUE THREAD

**Issue by JosselinSomervilleRoberts** [googleapis/python-aiplatform#3065]
Similarly to #3064, the output of `TextGenerationModel.predict` does not contain all the field returned by the HTTP Response.
I am personally needing the logprobs, would it be possible to add them? Thanks!

**Comment by sasha-gitg** [comment]
Released in 1.38

**Comment by reshmighosh** [comment]
Hi @sasha-gitg, any documentation on this?

I cannot see it in https://cloud.google.com/vertex-ai/docs/generative-ai/start/quickstarts/api-quickstart?

**Comment by ebigelow** [comment]
@reshmighosh  it's in the docs for specific models, presumably those that support it, e.g. [https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/text](https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/text)
