### ISSUE TITLE
URGENT! _TextGenerationModel.predict() got an unexpected keyword argument 'grounding_config'

### ISSUE THREAD

**Issue by SaschaHeyer** [googleapis/python-aiplatform#3077]
The SDK does not seem to support the new grounding feature.

#### Environment details
Name: google-cloud-aiplatform / version: 1.37.0

see reproduction notebook

https://colab.research.google.com/drive/1Saiz9be__LhDYy43WRfu127fLLvKKzEL

#### Steps to reproduce

see reproduction notebook
https://colab.research.google.com/drive/1Saiz9be__LhDYy43WRfu127fLLvKKzEL

#### Stack trace

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-7-f9faac24f8d9>](https://localhost:8080/#) in <cell line: 20>()
     18 }
     19 model = TextGenerationModel.from_pretrained("text-unicorn@001")
---> 20 response = model.predict(
     21     """telle me about sascha heyer""",
     22     **parameters

TypeError: _TextGenerationModel.predict() got an unexpected keyword argument 'grounding_config'
```

**Comment by sasha-gitg** [comment]
Grounding is exposed through the `grounding_sources` parameter. https://cloud.google.com/python/docs/reference/aiplatform/latest/vertexai.language_models.TextGenerationModel#vertexai_language_models_TextGenerationModel_predict

**Comment by yyyu-google** [comment]
Hi, 
grounding source is used by importing the `GroundingSource` class. See example
```
from vertexai.language_models import TextGenerationModel, GroundingSource
from google.colab import auth as google_auth
import vertexai

PROJECT_ID='your project'
LOCATION = "us-central1"
google_auth.authenticate_user(project_id=PROJECT_ID)
vertexai.init(project=PROJECT_ID, location=LOCATION)
text_model_name = "text-bison@001"
prompt = "what is vertex ai"
text_model = TextGenerationModel.from_pretrained(text_model_name)
data_store_id = "your data store ID"# example is "google-cloud_1690936150456"
vertex_location = "you data store location"# example "global"
grounding_souce = GroundingSource.VertexAISearch(data_store_id=data_store_id, location=vertex_location)
es_res = text_model.predict(
    prompt,
    grounding_source=grounding_souce,
)
es_res.grounding_metadata, es_res
```

the above should output

```
(GroundingMetadata(citations=[GroundingCitation(start_index=0, end_index=180, url='https://cloud.google.com/vertex-ai-vision', title=None, license=None, publication_date=None)]),
 Vertex AI is a machine learning (ML) platform that lets you train and deploy ML models and AI applications, and customize large language models (LLMs) for use in your applications.)
```

**Comment by SaschaHeyer** [comment]
Thanks for the doc reference. 

In that case, the Vertex AI UI is showing the wrong example:
<img width="1506" alt="Screenshot 2023-12-10 at 11 59 35" src="https://github.com/googleapis/python-aiplatform/assets/1991664/efb12c45-dc7d-4b15-adf9-98ce398eccf9">

**Comment by yyyu-google** [comment]
Thanks for pointing this out. While I reach out to Vertex UI to update the sample code, are you unblocked on test the VertexAISearch grounding feature?

**Comment by rendinurcahyo22** [comment]
> Hi, grounding source is used by importing the `GroundingSource` class. See example
> 
> ```
> from vertexai.language_models import TextGenerationModel, GroundingSource
> from google.colab import auth as google_auth
> import vertexai
> 
> PROJECT_ID='your project'
> LOCATION = "us-central1"
> google_auth.authenticate_user(project_id=PROJECT_ID)
> vertexai.init(project=PROJECT_ID, location=LOCATION)
> text_model_name = "text-bison@001"
> prompt = "what is vertex ai"
> text_model = TextGenerationModel.from_pretrained(text_model_name)
> data_store_id = "your data store ID"# example is "google-cloud_1690936150456"
> vertex_location = "you data store location"# example "global"
> grounding_souce = GroundingSource.VertexAISearch(data_store_id=data_store_id, location=vertex_location)
> es_res = text_model.predict(
>     prompt,
>     grounding_source=grounding_souce,
> )
> es_res.grounding_metadata, es_res
> ```
> 
> the above should output
> 
> ```
> (GroundingMetadata(citations=[GroundingCitation(start_index=0, end_index=180, url='https://cloud.google.com/vertex-ai-vision', title=None, license=None, publication_date=None)]),
>  Vertex AI is a machine learning (ML) platform that lets you train and deploy ML models and AI applications, and customize large language models (LLMs) for use in your applications.)
> ```

Hi, this is only for text-bison? I've tried for chat-bison and there is no available predict function, only start_chat.

**Comment by SaschaHeyer** [comment]
@yyyu-google 
Thanks for the text model your code is working great. 

I have the same question as @rendinurcahyo22
How can grounding be used with the chat model via the SDK? 
(the UI supports it for chat models)

**Comment by SaschaHeyer** [comment]
solved found it in the github repos code

` message1 = "Are my favorite movies based on a book series?"
        response1 = chat.send_message(
            message1,
            grounding_source=grounding_source,
        )`

**Comment by SaschaHeyer** [comment]
@yyyu-google for me the issue is solved. 
Or you want to keep it open until the UI is fixed as well?

**Comment by rendinurcahyo22** [comment]
> solved found it in the github repos code
> 
> https://github.com/googleapis/python-aiplatform/blob/0dccd83e4d8f5b44a169765f70bc4f96645c0776/tests/system/aiplatform/test_language_models.py#L149
> 
> ```
>         response1 = chat.send_message(
>             message1,
>             grounding_source=grounding_source,
>         )```
> ```

Thanks @SaschaHeyer ! Work for me as well.

**Comment by yyyu-google** [comment]
Hi yes. For chat model, the high level logic is following:
1. start a chat session by `chat = model.start_chat()`. 
2. This session will do two things: 2.a, expose `send_message` method to call LLM endpoint. 2.b, have a record of the chat history, which you can access by `chat.message_history`


```
from vertexai.language_models import ChatModel, GroundingSource
from google.colab import auth as google_auth
import vertexai

PROJECT_ID="your project name"
LOCATION = "us-central1"
google_auth.authenticate_user(project_id=PROJECT_ID)
vertexai.init(project=PROJECT_ID, location=LOCATION)

chat_model_name = "chat-bison@001"
prompt = "what is vertex ai"
chat_model = ChatModel.from_pretrained(chat_model_name)
data_store_id = "your datastore id" # for example google-cloud_xyz
vertex_location = "global"
grounding_source = GroundingSource.VertexAISearch(data_store_id=data_store_id, location=vertex_location)

chat = chat_model.start_chat()
response = chat.send_message(
    prompt,
    grounding_source = grounding_source
)
chat.message_history, response.grounding_metadata, response
```

you shall see your chat history, the grounding metadata, and the response.
