### ISSUE TITLE
TFX trainer component running in Kubeflow fails although it was successful in the Interactive Context

### ISSUE THREAD

**Issue by crbl1122** [googleapis/python-aiplatform#3109]
In GCP I run a Kubeflow ML pipeline with TFX components using a custom service account. The pipeline reads data from BigQuery and it has the following components: components = [example_gen, statistics_gen, schema_gen, transform, trainer, pusher]

The main problem is that it fails at the last "trainer" step, although I tested each step in the interactive context and all were OK. The secondary problem is that I cannot display log messages for the trainer module execution code in the main GCP pipeline dashboard (in the logs area). This complicates my debugging attempts. I can only view the logs from Logs Explorer but I cannot display the messages for the python trainer module code, seem only to be the framework messages. In those messages I view only one type of error message. I identified that this operation uses the default service account (not the custom one) and it might not have all permissions needed. I tried to set the trainer component to use the custom SA but it is not use it. How can I set it properly for the custom SA?

    com.google.cloud.ai.platform.common.errors.AiPlatformException: code=ALREADY_EXISTS, message=Schema with name projects/2385..../locations/..../metadataStores/default/metadataSchemas/f14caf7e-4234-473d-ac31-.... and version 0.0.1 already exists., cause=null

Please view the detailed issue description, here:

[https://stackoverflow.com/questions/77652732/tfx-trainer-component-running-in-kubeflow-fails-although-it-was-successful-in-th](url)

**Comment by sararob** [comment]
Hi there,

It looks like this issue is not related to the Vertex Python SDK. Could you open an issue with [Kubeflow Pipelines](https://github.com/kubeflow/pipelines) or [TFX](https://github.com/tensorflow/tfx)?

**Comment by crbl1122** [comment]
Hi, I opened another one in TFX

**Comment by crbl1122** [comment]
Hi, I opened another one in TFX. Will close this
