### ISSUE TITLE
Vertex AI preview.generative_models Gemini Vision InternalServerError: 500 Internal error encountered.

### ISSUE THREAD

**Issue by jianglanCao** [googleapis/python-aiplatform#3145]
There is a 500 error when using Gemini-provision.
I have tried so many times, if you want to create a muti-turn conversation with Gemini-pro-vision, you are not allowed to add any non-text part through all Contents.
You can only be allowed to have a muti-turn conversation with texts.
Even the last part can not include non-text.

`multimodal_model = GenerativeModel("gemini-pro-vision")

response = multimodal_model.generate_content(
    contents=[
        Content(
            role="user",
            parts=[
                Part.from_text("what is shown in this image?"),
                Part.from_uri(
                    "gs://generativeai-downloads/images/scones.jpg",
                    mime_type="image/jpeg",
                ),
            ],
        ),
        Content(
            role="model",
            parts=[
                Part.from_text("it is good"),
                Part.from_uri(
                    "gs://generativeai-downloads/images/scones.jpg",
                    mime_type="image/jpeg",
                ),
            ],
        ),
        Content(role="user", parts=[Part.from_text("how are you")]),
    ], stream=False
)`

![image](https://github.com/googleapis/python-aiplatform/assets/37798223/3872007b-0d4e-490b-ba69-50aae8e4285f)
![image](https://github.com/googleapis/python-aiplatform/assets/37798223/b428d9fc-d127-4d92-9c02-f7010bf3f986)
![image](https://github.com/googleapis/python-aiplatform/assets/37798223/1dda22ed-44a4-45d7-a41c-5c73c1ce70bb)

**Comment by sararob** [comment]
Thanks for the feedback! None of the models released now (https://cloud.google.com/vertex-ai/docs/generative-ai/learn/models#gemini-models) support multi-modal multi-turn chat. The SDK will support this as soon as the released model does.
