### ISSUE TITLE
it would be good to make SafetySettingsType available for outer packages

### ISSUE THREAD

**Issue by izapolsk** [googleapis/python-aiplatform#3154]
I'd like to add safety settings to langchain wrapper around gemini model in order to get rid of some workarounds.
The  [SafetySettingsType](https://github.com/googleapis/python-aiplatform/blob/122074659871daa72aec4a6d3330a82eec77a1c5/vertexai/generative_models/_generative_models.py#L90)
type isn't avaible outside for the time being. I'd lke to expose it via vertexai/preview/generative_models.py

I'm going to create small PR. Please let me know if the above and my PR make sense.
Thanks.

**Comment by Ark-kun** [comment]
Could you use the `Dict[HarmCategory, SafetySetting.HarmBlockThreshold]` type instead?

**Comment by izapolsk** [comment]
> Could you use the `Dict[HarmCategory, SafetySetting.HarmBlockThreshold]` type instead?
@Ark-kun, of course. I just think that the types that are passed to such interface classes should also be a part of interface and should be available outwardly. If you don't think it makes sense, please close the issue and PR.
Thanks.

**Comment by izapolsk** [comment]
> I'm thinking about just removing `SafetySettingsType` everywhere in favor of `Dict[HarmCategory, SafetySetting.HarmBlockThreshold]`.
> 
> Would that cause any issues for you? Would it be an improvement?

nope, that's ok.
