### ISSUE TITLE
Using GroundingSource.VertexAISearch returns API error 

### ISSUE THREAD

**Issue by YupItsZac** [googleapis/python-aiplatform#3193]
I'm trying to use the SDK with grounding on the Vertex AI API but when I add the `grounding_source` argument to the `predict` call as the docs suggest, the following exception is raised:

`google.api_core.exceptions.InvalidArgument: 400 com.google.apps.framework.request.BadRequestException: At least one of 'q', 'exact_terms' or 'or_terms' must be set`

Where should this be set? I can't find it anywhere in the docs or on Google/StackOverflow.

**code sample**
 ```
vertexai.init(project="the-project-id", location="us-central1")
grounding_source = GroundingSource.VertexAISearch(data_store_id='the_data_store_id, location='global')
model = TextGenerationModel.from_pretrained("text-bison@001")

prompt = "What time is it?" #dummy prompt for this example
 
parameters = {
    "candidate_count": 1,
    "max_output_tokens": 1024,
    "temperature": 0.2,
    "top_p": 0.8,
    "top_k": 40,
    "grounding_source": grounding_source
}

response = model.predict(
      prompt,
        **parameters
)
```

If I remove the grounding source, the code and call to Vertex AI works as expected.

**Comment by YupItsZac** [comment]
The error is of course coming from the API so I moved form the SDK to troubleshoot and play with this by hitting the API directly with cURL. First I added some debugs so I could capture the request parameters from the SDK just before it makes the API call in the client. Using this body resulted in the same error. Sanity check complete. 

It looks like if you're using a grounding source the API is expecting one of those parameters (`q`, `exact_terms` or `or_terms` to be set in the instance in addition to the `prompt` parameter. 

So, for example, making a POST using the following body works as expected: 

```
{
  "instances": [
    { 
        "prompt": "What is the most popular day of the week?",
        "q": "What is the most popular day of the week?"
    }
  ],
  "parameters": {
    "temperature": 0.2,
    "maxOutputTokens": 1024,
    "topP": 0.8,
    "topK": 40,
    "groundingConfig": {
      "sources": [
          {
              "type": "VERTEX_AI_SEARCH",
              "vertexAiSearchDatastore": "the_data_store"
          }
      ]
    }
  }
}
```

I still haven't been able to find any documentation or anything published from Google to verify that this is expected behavior and not a bug, but given that grounding is still in preview documentation is kinda sparse. 

What I *think* needs to happen:

- Figure out how to verify that this is an intentional change to that API. 
- When a grounding source is used, the SDK should additionally include the additionally required params in the instance dict.

**Comment by Ark-kun** [comment]
This looks like an API breaking change.
@yyyu-google Can you please take a look and forward to the relevant team?

**Comment by yyyu-google** [comment]
hi @YupItsZac 
Appreciate your deep dive. Could you try to test one more time? It could be transient issue. I will also ask relevant backend team to understand what happened. I just tested with the following code

```
from vertexai.language_models import TextGenerationModel, GroundingSource
from google.colab import auth as google_auth
import vertexai

PROJECT_ID='my_projectID' 
LOCATION = "us-central1"
google_auth.authenticate_user(project_id=PROJECT_ID)
vertexai.init(project=PROJECT_ID, location=LOCATION)
text_model_name = "text-bison@001"
prompt = "what is vertex ai"
text_model = TextGenerationModel.from_pretrained(text_model_name)
data_store_id = "my_data_store_id"
vertex_location = "global"
grounding_souce = GroundingSource.VertexAISearch(data_store_id=data_store_id, location=vertex_location)
es_res = text_model.predict(
    prompt,
    grounding_source=grounding_souce,
)
es_res.grounding_metadata, es_res
```

The above output

```
(GroundingMetadata(citations=[GroundingCitation(start_index=0, end_index=107, url='https://cloud.google.com/vertex-ai/docs', title=None, license=None, publication_date=None)], search_queries=['Vertex AI']),
 Vertex AI is a machine learning (ML) platform that lets you train and deploy ML models and AI applications. Vertex AI combines data preparation, model training, model serving, and model monitoring into a single platform.)
```
