### ISSUE TITLE
log_time_series_metrics doesn't handle step=0 correctly

### ISSUE THREAD

**Issue by simonhessner** [googleapis/python-aiplatform#3198]
OS: Debian 5.10.205-2 (2023-12-31) x86_64 GNU/Linux 
Python 3.10.13
pip 23.3.1
google-cloud-aiplatform: 1.37.0  

The experiment tracking (`python-aiplatform/google/cloud/aiplatform/metadata/experiment_run_resource.py`) contains the function `log_time_series_metrics` which accepts an optional `step` number. If this is not set (`step` has a falsy value), the step internally gets set to 1.

This is a problem if someone wants to log values for step 0 and 1 because both logs will be for step=1 and overwrite each other.

I am working on a PR to fix this: https://github.com/googleapis/python-aiplatform/pull/3199

**Comment by ZhenyiQ** [comment]
The change is in. Thanks @simonhessner for raising this issue and for submitting the fix!
