### ISSUE TITLE
ValueError: Content has no parts

### ISSUE THREAD

**Issue by hemanth** [googleapis/python-aiplatform#3257]
```py
response = gemini_pro_vision_model.generate_content([
  "Summarize the video in 10 bullet points",
  response = generative_models.Part.from_uri("gs://bucket/videos/video.mp4", mime_type="video/mp4"),
], stream=True)

for chunk in response :
  print(chunk.text)
```

The above code is resulting in `ValueError: Content has no parts.`

__Trace:__

```py
-
ValueError                                Traceback (most recent call last)
[<ipython-input-11-c1fcd0e8b6dc>](https://localhost:8080/#) in <cell line: 12>()
     11 
     12 for chunk in response :
---> 13   print(chunk.text)

2 frames
[/usr/local/lib/python3.10/dist-packages/vertexai/generative_models/_generative_models.py](https://localhost:8080/#) in text(self)
   1423             raise ValueError("Multiple content parts are not supported.")
   1424         if not self.parts:
-> 1425             raise ValueError("Content has no parts.")
   1426         return self.parts[0].text
   1427 

ValueError: Content has no parts.
```

```py
list(response) # response has no parts 🤷‍♂️

[candidates {
  content {
    role: "model"
  }
  finish_reason: SAFETY
  safety_ratings {
    category: HARM_CATEGORY_HARASSMENT
    probability: NEGLIGIBLE
  }
  safety_ratings {
    category: HARM_CATEGORY_HATE_SPEECH
    probability: NEGLIGIBLE
  }
  safety_ratings {
    category: HARM_CATEGORY_SEXUALLY_EXPLICIT
    probability: MEDIUM
    blocked: true
  }
  safety_ratings {
    category: HARM_CATEGORY_DANGEROUS_CONTENT
    probability: NEGLIGIBLE
  }
}
usage_metadata {
  prompt_token_count: 1044
  total_token_count: 1044
}
]
```

#### Environment details

  - OS type and version: colab: `Linux c7e8ae4fc1a7 5.15.133+ #1 SMP Wed Jan 10 13:04:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
  - Python version: `3.10.0`
  - pip version: `pip 23.1.2 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)`
  - `google-cloud-aiplatform` version: `1.40.0`

**Comment by hemanth** [comment]
`Summarize the video in 10 bullet points` prompt causes this issue! 

`Summarize the video` works fine.

**Comment by UmerQam** [comment]
getting the same error "ValueError: Content has no parts." on version google-cloud-aiplatform 1.40.0 today

**Comment by hemanth** [comment]
@UmerQam curious about your `prompt`

**Comment by UmerQam** [comment]
@hemanth  - my prompt is below, what changes do you suggest ? Tried diff prompts, but still getting the same error

_prompt = """You ae an assistant well versed in understanding the call transcript & generating various intents.
Given that parent intent as "Techncical Support" , generate child intent for call transcript mentioned under {text}.

Child intent should be atleast two words & not more than three words 

{text}
"""_

**Comment by lgnashold** [comment]
We're also seeing this.

**Comment by ZhenyiQ** [comment]
Hi @hemanth 

Thanks for filing the issue! The response contains the finish reason ("safety"), which means that the content is blocked because it has some safety issues. In the `safety_rating`, the `HARM_CATEGORY_SEXUALLY_EXPLICIT` is rated as "medium".

**Comment by hemanth** [comment]
@ZhenyiQ Interesting! `finish_reason: SAFETY` 

`Summarize the video in 10 bullet points` prompt causes this issue! 

`Summarize the video` works fine.

**Comment by ZhenyiQ** [comment]
@hemanth 

The model output is not deterministic. There might be two things that you can try:
1. set a lower temperature (but it's possible that it is the high probability answer that triggers the safety blocking).
2. use the safety settings. Something like
```
        response = model.generate_content(
            contents="Why is sky blue?",
            # Optional:
            safety_settings={
                HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_ONLY_HIGH,
                HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
                HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_LOW_AND_ABOVE,
                HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_NONE,
            }
        )
```

**Comment by ZhenyiQ** [comment]
cc @Ark-kun
