### ISSUE TITLE
Would geminipro supports logit_bias

### ISSUE THREAD

**Issue by indiejoseph** [googleapis/python-aiplatform#3272]
`logit_bias` is a common generation config to control LLM's output, it appears in other vertexai's language model family such as `text-bison`, would it happen to having `logit_bias` in geminipro model's generation configs?

**Comment by ZhenyiQ** [comment]
Hi @indiejoseph ,

Thanks for bringing this up! We don't plan to add support for `logit_bias` for Gemini in the foreseeable near future.
