### ISSUE TITLE
Referenced kubeflow pipeline version for LLM evaluation does not exist (used in evaluate() of _EvaluatableLanguageModel)

### ISSUE THREAD

**Issue by mugglmenzel** [googleapis/python-aiplatform#3353]
https://github.com/googleapis/python-aiplatform/blame/c00219f3d71c97572ca81b7665fb0fb6de749b56/vertexai/language_models/_evaluatable_language_models.py#L64

Former version 1.0.1 exists but updated 2.9.0 version returns a 404 and evaluation of LLMs fails.

This works in Vertex AI SDK v1.41 and below, but breaks from 1.42 (see blame). However, when using Vertex AI SDK v1.41 with the 1.0.1 evaluation pipeline template, it requires an undocumented "prompt" key in the evaluation data (c.f. https://cloud.google.com/vertex-ai/docs/generative-ai/models/evaluate-models#prepare_evaluation_dataset).

**Comment by Ark-kun** [comment]
Thank you for the report. Investigating.

**Comment by Ark-kun** [comment]
Are you sure the pipeline returns 404?

Both of these URLs work for me.

https://us-kfp.pkg.dev/vertex-evaluation/pipeline-templates/evaluation-llm-classification-pipeline/2.9.0
https://us-kfp.pkg.dev/vertex-evaluation/pipeline-templates/evaluation-llm-text-generation-pipeline/2.9.0

@jsondai
