### ISSUE TITLE
FunctionDeclaration doesn't allow function without parameters 

### ISSUE THREAD

**Issue by Yuan325** [googleapis/python-aiplatform#3405]
https://github.com/googleapis/python-aiplatform/blob/2690e7223535d5758ed0e13075aebdde41a678f3/vertexai/generative_models/_generative_models.py#L1328C9-L1328C36

I added a function to my chat model's FunctionDeclaration. The function call does not require any input parameters, however, FunctionDeclaration needs to have a parameter (empty block `{}` doesn't work either since it does not follow the schema that is required). How should I go about this? According to the documentation (https://cloud.google.com/vertex-ai/docs/reference/rest/v1/Tool#functiondeclaration), parameters seems to be optional.
Thank you!

**Comment by Ark-kun** [comment]
Are there real user scenarios where calling a function without parameters is useful?

>empty block {} doesn't work

You can pass a valid JSON Schema that describes empty signature:
```
{"type": "object"}
```
or maybe 
```
{"type": "object", "properties": {}}
```

**Comment by Yuan325** [comment]
worked, thank you.
