### ISSUE TITLE
Custom job run is always blocking

### ISSUE THREAD

**Issue by racinmat** [googleapis/python-aiplatform#3432]
#### Environment details

  - OS type and version:
  - Python version: `3.10.12`
  - pip version: `23.2.1`
  - `google-cloud-aiplatform` version: `1.43.0`

#### Steps to reproduce

  1. create a custom job
  2. call run method with sync=False

#### Code example

```python
my_job = aiplatform.CustomJob(
    display_name='my_job',
    ...
)

my_job.run(sync=False)
```

is blocking.

Thie is because does not consider https://github.com/googleapis/python-aiplatform/blob/main/google/cloud/aiplatform/jobs.py#L2351 the sync and still blocks the thread.

I think it's similar to https://github.com/googleapis/python-aiplatform/issues/3038 where the program execution is blocked too regardless of the value of `sync` parameter.

**Comment by jaycee-li** [comment]
Hi Matěj, this is an intended behavior. If you use Colab or Jupyter notebook, you'll find `mo_job.run(syn=False)` unblock your code cell immediately.

If you want to unblock the python thread, you can use `my_job.submit()`

**Comment by racinmat** [comment]
oh, I see. So the sync argument is only working in colab or jupyter notebook? Is this documented anywhere?

**Comment by jaycee-li** [comment]
`sync` works in python threads as well. The blocking you experienced happened because your python script ended, automatically triggering the async CustomJob execution. If you try adding code after `CustomJob.run()` (like a print statement) – you'll see the code run before the CustomJob starts blocking.

**Comment by racinmat** [comment]
Oh, I see, thanks, I'll need to investigate it more. So it's running in separate thread?
