### ISSUE TITLE
GCP GroundingSource() 400 error Inline context must be specified

### ISSUE THREAD

**Issue by oroojlooy** [googleapis/python-aiplatform#3437]
Thanks for stopping by to let us know something could be better!

#### Environment details

  - OS type and version: fedora, 7.9
  - Python version: 3.11.0
  - pip version: 23.3.1 
  - `google-cloud-aiplatform` version: 1.43.0

#### Steps to reproduce

I am trying to run the grounding score API from GCP, where I am passing the context as a string to the API. But, I am getting the `google.api_core.exceptions.InvalidArgument: 400 Inline context must be specified` error. I checked the request object and the dict-converted context of that is: 

    grounding_source._to_grounding_source_dict()
    PyDev console: starting.
    {'sources': [{'type': 'INLINE'}], 'inlineContext': 'The Pixel Tablet, offered by Google, comes in three elegant colors: Porcelain, Hazel, and Rose. Let’s delve into the details: Price: The base model with 128GB of storage is priced at $499. If you need more storage, there’s a version with 256GB of storage available for $59912. Colors: Choose from the following stylish colors: Porcelain: A fresh and clean hue that’s new to Google’s tablet lineup. Hazel: A warm and inviting color option. Rose: A sophisticated choice for those who appreciate elegance3. Storage Size Options: The Pixel Tablet offers two storage variants: 128GB UFS 3.1 storage 256GB UFS 3.1 storage42. In addition to its sleek design, the Pixel Tablet boasts impressive specs, including an expansive 10.95-inch LCD display with a resolution of 2560x1600 pixels, 8GB LPDDR5 RAM, and the powerful Google Tensor G2 processor. Its battery life allows for up to 12 hours of video streaming, and it charges via the included Charging Speaker Dock or a separate USB-C® charger'}

Here is the full code to reproduce the error:

    from typing import Optional
    
    import vertexai
    from vertexai.language_models import (
        GroundingSource,
        TextGenerationModel,
        TextGenerationResponse,
    )
    
    
    def grounding(
        project_id: str, location: str = "",
        data_store_location: Optional[str] = None,
        data_store_id: Optional[str] = None) -> TextGenerationResponse:
        """Grounding example with a Large Language Model"""
    
        vertexai.init(project=project_id, location=location)
    
        # TODO developer - override these parameters as needed:
        parameters = {
            "temperature": 0.7,  # Temperature controls the degree of randomness in token selection.
            "max_output_tokens": 256,  # Token limit determines the maximum amount of text output.
            "top_p": 0.8,  # Tokens are selected from most probable to least until the sum of their probabilities equals the top_p value.
            "top_k": 40,  # A top_k of 1 means the selected token is the most probable among all tokens.
        }
    
        model = TextGenerationModel.from_pretrained("text-bison@002")
        source = "The Pixel Tablet, offered by Google, comes in three elegant colors: Porcelain, Hazel, and Rose. Let’s delve into the details: Price: The base model with 128GB of storage is priced at $499. If you need more storage, there’s a version with 256GB of storage available for $59912. Colors: Choose from the following stylish colors: Porcelain: A fresh and clean hue that’s new to Google’s tablet lineup. Hazel: A warm and inviting color option. Rose: A sophisticated choice for those who appreciate elegance3. Storage Size Options: The Pixel Tablet offers two storage variants: 128GB UFS 3.1 storage 256GB UFS 3.1 storage42. In addition to its sleek design, the Pixel Tablet boasts impressive specs, including an expansive 10.95-inch LCD display with a resolution of 2560x1600 pixels, 8GB LPDDR5 RAM, and the powerful Google Tensor G2 processor. Its battery life allows for up to 12 hours of video streaming, and it charges via the included Charging Speaker Dock or a separate USB-C® charger"
        if source is not None:
            grounding_source = GroundingSource.InlineContext(source)
        elif data_store_id and data_store_location:
            # Use Vertex AI Search data store
            grounding_source = GroundingSource.VertexAISearch(
                data_store_id=data_store_id, location=data_store_location
            )
        else:
            # Use Google Search for grounding (Private Preview)
            grounding_source = GroundingSource.WebSearch()
    
        response = model.predict(
            "What are the price, available colors, and storage size options of a Pixel Tablet?",
            grounding_source=grounding_source,
            **parameters,
        )
        print(f"Response from Model: {response.text}")
        print(f"Grounding Metadata: {response.grounding_metadata}")
    
    
    grounding(project_id="selfcheck1")

#### Stack trace
Below is the full error:

```
Traceback (most recent call last):
  File "/home/aoroojlo/miniconda3/envs/mixtral/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 76, in error_remapped_callable
    return callable_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aoroojlo/miniconda3/envs/mixtral/lib/python3.11/site-packages/grpc/_channel.py", line 1176, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aoroojlo/miniconda3/envs/mixtral/lib/python3.11/site-packages/grpc/_channel.py", line 1005, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Inline context must be specified."
	debug_error_string = "UNKNOWN:Error received from peer ipv4:142.251.42.42:443 {created_time:"2024-03-14T01:54:07.517518467+00:00", grpc_status:3, grpc_message:"Inline context must be specified."}"
>
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/aoroojlo/miniconda3/envs/mixtral/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InvalidArgument: 400 Inline context must be specified.
python-BaseException
```

**Comment by Ark-kun** [comment]
Fixed by https://github.com/googleapis/python-aiplatform/pull/3444
