### ISSUE TITLE
Support fastapi v0.109.1+

### ISSUE THREAD

**Issue by divya-layerhealth** [googleapis/python-aiplatform#3451]
FastAPI 0.109.1+ has a fix for a security vulnerability introduced via the `python-multipart` library, as per [this link](https://security.snyk.io/vuln/SNYK-PYTHON-FASTAPI-6228055). 

It would be great to increase the upperbound on `fastapi` versions within the prediction extra-requires: 

https://github.com/googleapis/python-aiplatform/blob/main/setup.py#L80-L86

**Comment by matthew29tang** [comment]
This issue has been resolved with (1) and released in `google-cloud-aiplatform==1.48.0`

(1): https://github.com/googleapis/python-aiplatform/commit/de226ba83b5a71799f7dd9c726a476024058c6d1
