### ISSUE TITLE
ImportError cloud_profiler could not found.

### ISSUE THREAD

**Issue by niraj06** [googleapis/python-aiplatform#3623]
We are trying to enable cloud_profiler by following this documentation https://cloud.google.com/vertex-ai/docs/training/tensorboard-profiler

Add below line to model train
from google.cloud.aiplatform.training_utils import cloud_profiler

cloud_profiler.init()

throwing error : ImportError: Could not load the cloud profiler. To use the profiler, install the SDK using 'pip install google-cloud-aiplatform[cloud-profiler]'

We tried to install pip install google-cloud-aiplatform[cloud-profiler]
and it says no matches found: google-cloud-aiplatform[cloud-profiler]

**Comment by Ark-kun** [comment]
Thank you for reporting. Can you please try `pip install google-cloud-aiplatform[cloud_profiler]`

**Comment by niraj06** [comment]
> pip install google-cloud-aiplatform[cloud_profiler]

@Ark-kun Yes we tried and it give warning 

(base) jupyter@niraj6-tensorflow-gpus:~$ pip install google-cloud-aiplatform[cloud_profiler]
Requirement already satisfied: google-cloud-aiplatform[cloud_profiler] in /opt/conda/lib/python3.10/site-packages (1.47.0)
**WARNING: google-cloud-aiplatform 1.47.0 does not provide the extra 'cloud-profiler'**

I tried with different version and its same Warning across different versions.

**Comment by niraj06** [comment]
@Ark-kun May i know the fix details, we are still getting error
