### ISSUE TITLE
Support GenerativeModel.count_tokens[_async] for fully-featured generation requests

### ISSUE THREAD

**Issue by adubovik** [googleapis/python-aiplatform#3631]
It should be possible to count number of **prompt** tokens via `GenerativeModel.count_tokens[_async]` method before running an actual generation request.

However, the [method](https://github.com/googleapis/python-aiplatform/blob/de226ba83b5a71799f7dd9c726a476024058c6d1/vertexai/generative_models/_generative_models.py#L648) takes into account only the `contents` component of a request.

[Other components](https://github.com/googleapis/python-aiplatform/blob/de226ba83b5a71799f7dd9c726a476024058c6d1/vertexai/generative_models/_generative_models.py#L237-L239) of a request _(such as `tools`, `tool_config`, and `system_instruction`)_ presumably affect prompt token count, so it would be great to support them in the count-token methods too.

**Comment by Ark-kun** [comment]
Thank you for the feedback. This makes sense.
However this is currently not supported by the API: https://github.com/googleapis/python-aiplatform/blob/cd85d8f74d3922de3f871415bacf77c594f0c547/google/cloud/aiplatform_v1beta1/types/prediction_service.py#L702

**Comment by happy-qiao** [comment]
system_instruction and tools are supported in [GenerativeModel.](https://github.com/googleapis/python-aiplatform/blob/ee65917fbc1edc58a7e57c3601f9329ffa1304b0/vertexai/generative_models/_generative_models.py#L826). 

tools_config is not in service API
