### ISSUE TITLE
Uri parameter cannot be overridden when sending via rest transport

### ISSUE THREAD

**Issue by karimmohraz** [googleapis/python-aiplatform#3724]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-aiplatform/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

>  no similar issue found

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Mac OS latest
  - Python version: 3.9
  - pip version: 24.0
  - `google-cloud-aiplatform` version: Version: 1.47.0

#### Steps to reproduce

  1. Created subclass for GenerativeModel
  2. Instantiated a GenerativeServiceClient for sending requests to Gemini 1.0 model
  3. Call generate_content with the intent to replace api endpoint, model uri, and api key

Context: we have our own AI hub where we count tokens for a set of models before forwarding the request to the model hosted by Google/ Azure-OpenAI, etc.
E.g., in case of OpenAI we can override the 3 parameters. But this is not the case for the Google SDK.

#### Code example

```python
        kwargs = dict(model_name='gemini-1.0-pro')
        model = MyGenerativeModel(proxy_client=self.proxy_client, **kwargs)
        content = self._get_test_messages()
        model_response = model.generate_content(content)

       ## in MyGenerativeModel subclass we do the following:
        super().__init__(**kwargs)
        self._client = GenerativeServiceClient(transport=transport, client_options={'api_endpoint': 'myhost'})
```

However, in 
venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/transports/rest.py:810
uri seems to be hard coded.
We want to override with this uri: "models/gemini-1.0-pro:generateContent" (remove e.g. /v1/beta/)

#### Stack trace
```
400 response code as /v1/beta/ is not part of our suffix.
```

In addition I created a Interceptor, but did not help either, as the uri code is not adapted in rest.py
```python
class MyCustomGenerativeServiceInterceptor(GenerativeServiceRestInterceptor):
    def pre_generate_content(self, request, metadata):
        # logging.log(f"Received request: {request}")
        metadata.append(("uri", "models/gemini-1.0-pro:generateContent"))
        return request, metadata
```

Plz let us know if there is another way to override uri.
Thanks!

**Comment by Ark-kun** [comment]
Hello. You might want to move this issue to the corresponding repository (this repository is for the Vertex GenAI SDK): https://github.com/google-gemini/generative-ai-python or https://github.com/googleapis/google-cloud-python 

I'm not sure what you want can be easily done. The code in question is auto-generated and it's generated like this for hundreds of Google API services. I'm not sure it will be changed.

Would it be possible to fix the proxy to handle versioned APIs? Usually proxies can handle arbitrary requests and URLs.
