### ISSUE TITLE
EDIT: Update Documentation on response_mime_type

### ISSUE THREAD

**Issue by 17jmumford** [googleapis/python-aiplatform#3807]
**Is your feature request related to a problem? Please describe.**
JSON format is something frequently used by our team of developers when interacting with other AI providers. The lack of JSON format support for Gemini in the Python package is frustrating since the documentation shows it is available in the API. 
https://ai.google.dev/gemini-api/docs/api-overview?utm_source=gfd&utm_medium=referral&utm_campaign=blog-gemini-15-pro-preview&utm_content#json
 **Describe the solution you'd like**
Add a response_format parameter to either GenerativeModel or GenerationConfig, probably the latter. Users can select 'text' or 'json' as response_format options.
 **Describe alternatives you've considered**
The alternative would be refactoring our code to interact directly with the API via curl, but we would lose the many benefits of using the Python package.

**Comment by 17jmumford** [comment]
Upon diving into the code, it looks like this feature is already available, but the documentation has not been updated. I will attempt to update the documentation to match this.

**Comment by 17jmumford** [comment]
The documentation that is out of date is not in this repo. It is also not in this repo:
https://github.com/google/generative-ai-docs

If anybody knows where to find this documentation or who is in charge of updating it, that would be most appreciated.

**Comment by holtskinner** [comment]
This is where the `response_mime_type` parameter is set for the Gemini API (Not the Vertex AI SDK)

https://github.com/googleapis/googleapis/blob/f84e781256b0657a0d67bc1818bbb7e9a3e86a85/google/ai/generativelanguage/v1beta/generative_service.proto#L252

The documentation should be auto-updated with the latest parameters once the client libraries are updated.
