### ISSUE TITLE
ValueError: Cannot get the response text

### ISSUE THREAD

**Issue by Julian-Cao** [googleapis/python-aiplatform#3837]
We have batch predictions but some got this back without more details.
We use Gemini 1.5 Flash without any maunal setting like temprature or safety setting.
It is different from the other one "ValueError: Response candidate content has no parts (and thus no text). The candidate is likely blocked by the safety filters. "

No more error msg info here.
Does this mean there are some bugs or poor error handler from Gemini 1.5 Flash API?

model = GenerativeModel(
            model_name="gemini-1.5-flash-001", system_instruction=[context]
        )

        response = model.generate_content(
            contents=[
                Content(
                    role="user",
                    parts=[
                        Part.from_text(
                            "The file content is the following : /n"
                            + "<file> /n"
                            + summarized_text
                            + "</file>"
                        )
                    ],
                )
            ],
            stream=False,
        )
File "/usr/local/lib/python3.9/site-packages/vertexai/generative_models/_generative_models.py", line 1671, in text
raise ValueError(
ValueError: Cannot get the response text.

**Comment by Ark-kun** [comment]
As the error states, there are not response parts. There is not response text, so you cannot get it. As the error said, "The candidate is likely blocked by the safety filters".

Please update the SDK. The latest versions provide much more information in such scenario.

**Comment by Julian-Cao** [comment]
> As the error states, there are not response parts. There is not response text, so you cannot get it. As the error said, "The candidate is likely blocked by the safety filters".
> 
> Please update the SDK. The latest versions provide much more information in such a scenario.

Hello, this error seems to be different from the one " safety filters"
It only throws out the " ValueError: Cannot get the response text" without mentioning the  safety filters

Do you mean the two are the same issue?

**Comment by ZhenyiQ** [comment]
Hi @Julian-Cao , I'm expecting the error message to have more content, as I suspect that it's thrown here: https://github.com/googleapis/python-aiplatform/blob/88c6a6a4f11285d429c3777f59101e53e4672185/vertexai/generative_models/_generative_models.py#L1680-L1683.

Would you mind providing more about the error message? Thanks!

**Comment by Julian-Cao** [comment]
> Hi @Julian-Cao , I'm expecting the error message to have more content, as I suspect that it's thrown here:
> 
> https://github.com/googleapis/python-aiplatform/blob/88c6a6a4f11285d429c3777f59101e53e4672185/vertexai/generative_models/_generative_models.py#L1680-L1683
> 
> .
> Would you mind providing more about the error message? Thanks!
To be honest, no more information is thrown out, we don't know how this happened、
logs like these are all we can get:
line 1667+line 1754+ line 1671

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/vertexai/generative_models/_generative_models.py", line 1667, in text
    return self.candidates[0].text
  File "/usr/local/lib/python3.9/site-packages/vertexai/generative_models/_generative_models.py", line 1754, in text
    raise ValueError(
ValueError: Cannot get the Candidate text. 


 File "/usr/local/lib/python3.9/site-packages/vertexai/generative_models/_generative_models.py", line 1671, in text
    raise ValueError(
ValueError: Cannot get the response text.

**Comment by nikhil2406** [comment]
I stumbled upon this issue as well. I put this fix in my local version of python-aiplatform. 
```
diff --git a/vertexai/generative_models/_generative_models.py b/vertexai/generative_models/_generative_models.py
index df6536ec..3f2b11df 100644
--- a/vertexai/generative_models/_generative_models.py
+++ b/vertexai/generative_models/_generative_models.py
@@ -1866,9 +1866,9 @@ class Part:
 
     @property
     def text(self) -> str:
-        if "text" not in self._raw_part:
+        if not hasattr(self._raw_part, 'text'):
             raise AttributeError("Part has no text.")
-        return self._raw_part.text
+        return getattr(self._raw_part, 'text')
 ```

**Comment by Ark-kun** [comment]
@Julian-Cao @nikhil2406 
What is the SDK version you're using? Can you please try updating to the latest version?

**Comment by Ark-kun** [comment]
@nikhil2406 

> if not hasattr(self._raw_part, 'text'):

I'm not sure the proposed solution is correct since all attributes always exist on a proto message.

Example:
```
>>> hasattr(response.candidates[0].content.parts[0]._raw_part, "function_call")
True
```
So, `hasattr` just always returns `True`.

**Comment by Ark-kun** [comment]
I'm closing the issue since the real cause is likely a safety-blocked response and updating the SDK will help reveal that by improving the error messages. If that's not the case, feel free to reopen.

**Comment by nikhil2406** [comment]
@Ark-kun I know that I have an older version. But I thought the problem was due to this line `if "text" not in self._raw_part:` . Since self._raw_part is not a dict or list or Set or string, this line was throwing error `Part class is not iterable`. I see that line is same in the latest code too. Let me know what do you think.

**Comment by Ark-kun** [comment]
>But I thought the problem was due to this line if "text" not in self._raw_part: . Since self._raw_part is not a dict or list or Set or string

I'm not sure about that. What does `response.to_dict()` return?

>Since self._raw_part is not a dict or list or Set or string

`self._raw_part` has `__contains__` method which is the official way to check for the presence of oneof fields.

>this line was throwing error Part class is not iterable

There is another bug about this issue. I'm unable to reproduce it, but would be glad to debug. https://github.com/googleapis/python-aiplatform/issues/3129
