### ISSUE TITLE
Spelling mistake in error message

### ISSUE THREAD

**Issue by Zeneixe** [googleapis/python-aiplatform#3870]
https://github.com/googleapis/python-aiplatform/blob/945b9e4835149111cd33beaee4301f3d8f05f59d/google/cloud/aiplatform/utils/featurestore_utils.py#L60C62-L60C68

Valied -> Valid

**Comment by matthew29tang** [comment]
Thanks, resolved in https://github.com/googleapis/python-aiplatform/commit/ebb8f6233bfaf7bbfbc8a5fbfb22cbc560f23557
