### ISSUE TITLE
_append_tool_name raises list index out of range on 1.54.0 

### ISSUE THREAD

**Issue by nicoloboschi** [googleapis/python-aiplatform#3910]
#### Environment details

  - OS type and version: MacOS
  - Python version: any
  - pip version: any
  - `google-cloud-aiplatform` version: 1.54.0

#### Steps to reproduce

Use vertexAI embeddings from langchain now raises
```
    def _append_tool_name(tool_name: str) -> None:
>       if _tool_names_to_append[-1] != tool_name:
E       IndexError: list index out of range
```

**Comment by sasha-gitg** [comment]
Fixed in 1.54.1
