### ISSUE TITLE
Support protobuf>=5

### ISSUE THREAD

**Issue by TheMichaelHu** [googleapis/python-aiplatform#3927]
I am trying to install protobuf 5.27.0+ alongside the Vertex SDK, however only versions below 5 [are supported](https://github.com/googleapis/python-aiplatform/blob/4f1b5593bfe67c4b1d69e49a706587b9fe9b3f4e/setup.py#L245).

Protobuf has stopped releasing 4.x.x versions since February, so it may be worth testing if the Vertex SDK is compatible with 5.x.x.

**Comment by RoyLeviLangware** [comment]
Any update here? @parthea

**Comment by parthea** [comment]
Wait for cl/658142937

**Comment by nategoethel** [comment]
Bump on this?

**Comment by parthea** [comment]
This was completed in https://github.com/googleapis/python-aiplatform/pull/4132. 

https://github.com/googleapis/python-aiplatform/blob/acf31138177fbcc29e469c863615cfa70b4ccc19/setup.py#L251

https://github.com/googleapis/python-aiplatform/releases/tag/v1.61.0
