### ISSUE TITLE
Error stream=True freeze screen and not response no error nothing in logs

### ISSUE THREAD

**Issue by mutonby** [googleapis/python-aiplatform#3934]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-aiplatform/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Docker with image: python:3.10.10
  - Python version: 3.10.10

  - `google-cloud-aiplatform` version: 1.54.1

#### Steps to reproduce

 Run the code with stream =True and not answer, the api running freeze, I am using the same example of documentation in the sandbox works but in my api no. And with stream=False is working well

I am using docker compose,and socketio for the endpoint

#### Code example

```python
responses = model.generate_content(prompt, stream=True)
    log("LOG", "Gemini responde:", responses)
    full_response = ""

    for response in responses:
        log("LOG", "Gemini response:", response.text)
        print(response.text, end="")
```

#### Stack trace
```
Not show logs inside of for loop is freeze forever,  only before:

[Gemini responde:]: <generator object _GenerativeModel._generate_content_streaming at 0x4025fbbf40>
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by jaycee-li** [comment]
Hi @mutonby, just wanted to check which model you were using and if you're still having the issue you mentioned. I tried `gemini-1.0-pro` in Colab today and it's working without any problems on my end.

![image](https://github.com/googleapis/python-aiplatform/assets/102714969/ded5d03c-d10c-4cc7-8fc2-e95798003eb7)
