### ISSUE TITLE
[BUG] Can't use seed parameter with TextGenerationModel.predict_async

### ISSUE THREAD

**Issue by uripeled2** [googleapis/python-aiplatform#3974]
#### Environment details

  - OS type and version: MacOS Sonoma 14.5
  - Python version: 3.10.4
  - pip version: 24.0
  - `google-cloud-aiplatform` version: 1.56

#### Code example

```python
model = TextGenerationModel.from_pretrained("text-bison@001")
response = await model.predict_async(
                prompt="hello world",
                max_output_tokens=1024,
                temperature=0.0,
                top_p=1.0,
                seed=42
            )
```

#### Stack trace
```
raise exceptions.from_grpc_error(rpc_error) from rpc_error
google.api_core.exceptions.InternalServerError: 500 Internal error encountered.
```

**Comment by jaycee-li** [comment]
It seems there's a problem with version `@001`. I've notified the service team and will update you as soon as I hear back.

In the meantime, you can try using `text-bison` or `text-bison@002` as temporary alternatives.

**Comment by jaycee-li** [comment]
The service team said `text-bison@001` doesn't support seed.  The problem is the 500 Internal Error is not informative, they'll update the error message to be more clear.
