### ISSUE TITLE
MAX_TOKENS is not working anymore with Vertex/Gemini.

### ISSUE THREAD

**Issue by vi3k6i5** [googleapis/python-aiplatform#4058]
Till last week this was working fine, but now it has stopped working.

#### Environment details

  - OS type and version: Mac latest
  - Python version: `python --version` 3.9
  - pip version: `pip --version` NA
  - `google-cloud-aiplatform` version: `pip show google-cloud-aiplatform` 1.54.0

#### Steps to reproduce

  1. Make a curl call with condition for max_tokens in GenerationConfig
 
`
Curl` -v -X '<aiplatformurl>/location/us-central1/publishers/google/models/gemini-1.0-pro:generateContent' \
--data '{
    "contents": {
        "role: "user",
       "parts": { "Give me a recipe for Banana bread."}
    },
    "generation_config": {
         "maxOutputTokens": 4
    }
}'

`
this returns output with 4 tokens
`
...."text: "## Easy Banana Bread"
`
But the reason for finish is "STOP", which is incorrect, it should be MAX_TOKENS. Till last week the reason was correct.

Thanks!

**Comment by jaycee-li** [comment]
@vi3k6i5 I can reproduce the issue on my end. I've informed the backend team and will update you as soon as I have more information.

**Comment by jaycee-li** [comment]
This issue has been fixed. Please feel free to reopen if you encounter any further problems.
