### ISSUE TITLE
How to add header to AnthropicVertex Python request

### ISSUE THREAD

**Issue by SomebodySysop** [googleapis/python-aiplatform#4124]
I am using  AnthropicVertex SDK (which I assume is a subset of the Vertex AI Platform) to make calls to claude-3-5-sonnet@20240620 as per: https://console.cloud.google.com/vertex-ai/publishers/anthropic/model-garden/claude-3-5-sonnet?service=claude-3-5-sonnet.endpoints.mp-anthropic.cloud.goog

This is working fine.  The only issue is that I need to access the maxium output token limit of 8192.

According to: https://docs.anthropic.com/en/docs/about-claude/models

> Max output | 8192 tokens1
> 8192 output tokens is in beta and requires the header anthropic-beta: max-tokens-3-5-sonnet-2024-07-15. If the header is not specified, the limit is 4096 tokens.
> 

My question is:  How can I add this header line to the output request using the Python AnthropicVertex SDK?

**Comment by SomebodySysop** [comment]
After extensive online searches, I did find two ways advertised to modify the headers to increase the maximum output tokens:

https://github.com/anthropics/anthropic-sdk-python?tab=readme-ov-file#default-headers
```
    client = AnthropicVertex(
        region=LOCATION,
        project_id=project_id,
		# https://github.com/anthropics/anthropic-sdk-python?tab=readme-ov-file#default-headers
		default_headers={"anthropic-beta": "max-tokens-3-5-sonnet-2024-07-15"} # Custom headers here
    )
```
And also:

 https://x.com/alexalbert__/status/1812921642143900036

```
    message = client.messages.create(
        max_tokens=max_tokens,
        messages=[
            {
                "role": "user",
                "content": content,
            }
        ],
        model="claude-3-5-sonnet@20240620",
        # https://x.com/alexalbert__/status/1812921642143900036
		extra_headers={"anthropic-beta": "max-tokens-3-5-sonnet-2024-07-15"}  # Custom headers here
    )
```
But neither way appears to work in the AnthropicVertex SDK:

> Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'max_tokens: 8192 > 4096, which is the maximum allowed number of output tokens for claude-3-5-sonnet-20240620'}}

**Comment by Ark-kun** [comment]
It's likely that the header is correctly added, but the feature is in beta and not yet available from the model deployed to Vertex AI.

Could you please transfer this issue to the Anthropic SDK repository (https://github.com/anthropics/anthropic-sdk-python). This repository is for the Vertex SDK and the `google-cloud-aiplatform` package? Vertex SDK has it's own way to add headers/request metadata, but it's irrelevant since you're not using it.
