### ISSUE TITLE
create_batch_prediction_job_video_action_recognition_sample_test.py need correct test input

### ISSUE THREAD

**Issue by telpirion** [googleapis/python-aiplatform#417]
The GCS_SOURCE_URI for the test points to a non-existent file:

https://github.com/googleapis/python-aiplatform/blob/master/samples/snippets/create_batch_prediction_job_video_action_recognition_sample_test.py#L29

This needs to point to a new batch prediction file for Video Action Recognition.

**Comment by andrewferlitsch** [comment]
fixed
