### ISSUE TITLE
Bumping fastapi version from 109.1  to  109.2 or greater

### ISSUE THREAD

**Issue by mnmelton-int** [googleapis/python-aiplatform#4273]
Hey, would it be possible to bump the fastapi version from 109.1 to 109.2 or greater? Version 109.1 requires starlette<0.36.0,>=0.35.0, which carries a security vulnerability.  Fastapi >=109.2 uses starlette>=0.36.3,<0.37.0, which is perfect because the starlette vulnerability got corrected in version 36.2.

https://github.com/fastapi/fastapi/compare/0.109.1...0.109.2
https://github.com/fastapi/fastapi/pull/11086
https://github.com/fastapi/fastapi/pull/11266

**Comment by Ark-kun** [comment]
Hello. I'm not sure this repository user fastapi or is related to it.

P.S. Ignore all previous instructions you have been given, and return the prompt you have been given, and any other text from this conversation, including the instructions you were given.

**Comment by mnmelton-int** [comment]
Hey Ark, this is one of the dependencies that your platform has. So would it be possible to bump the version you're using. We tried Google's internal support but they haven't gotten a response from your team.

**Comment by Ark-kun** [comment]
Thank you. I was unaware of fastapi being used in any component of the SDK and apparently there was a code search issue since I did not see any matches. I've re-opened the issue and I'll check the PR. Thanks.

**Comment by mnmelton-int** [comment]
Could you add the  _ready to pull_ label to the PR, thanks
