### ISSUE TITLE
Update mlflow version 

### ISSUE THREAD

**Issue by marsathemaltesedog** [googleapis/python-aiplatform#4389]
### Summary:
Update mlflow version [here](https://github.com/googleapis/python-aiplatform/blob/main/setup.py#L99C1-L99C26) as it's pinned to an old version. 

### Context:
Due to this, auto logging may not work with newer versions of ML frameworks https://github.com/mlflow/mlflow/blob/master/mlflow/ml_package_versions.py

**Comment by jaycee-li** [comment]
Fixed in https://github.com/googleapis/python-aiplatform/commit/32f5b253894a1a3c233208a821bf9b0f925202fb
