### ISSUE TITLE
Bump pydantic version for google-cloud-aiplatform[ray]

### ISSUE THREAD

**Issue by h4gen** [googleapis/python-aiplatform#4393]
**Is your feature request related to a problem? Please describe.**
google-cloud-aiplatform[ray] currently not installable in a poetry env with tools like instructor, fastapi installed, that depend on newer versions of pydantic.
 **Describe the solution you'd like**
Bump pydantic to current version
 **Describe alternatives you've considered**
Force installation but thats bad
 **Additional context**

Problematic line: [    "pydantic < 2"
](https://github.com/googleapis/python-aiplatform/blob/94ebf9f5daa6137f8263f0dce8713372b0021527/setup.py#L123)

**Comment by matthew29tang** [comment]
Resolved in https://github.com/googleapis/python-aiplatform/pull/4408
