### ISSUE TITLE
Typo in PAIRWISE_INSTRUCTION_FOLLOWING_PROMPT_TEMPLATE ?

### ISSUE THREAD

**Issue by Valeriy-Burlaka** [googleapis/python-aiplatform#4419]
I believe there is a typo on [this line](https://github.com/googleapis/python-aiplatform/blob/main/vertexai/evaluation/metrics/_default_templates.py#L393) of the `"pairwise_instruction_following"` metric prompt template example for Vertex AI.
**STEP 2** should refer to the **Response B** but it currently reads as "STEP 2: Analyze **Response B** based on the instruction following criteria: Determine how well **Response A** fulfills ..."

**Update:** Spotted the same issue for the `PAIRWISE_SUMMARIZATION_QUALITY_PROMPT_TEMPLATE` template ([link](https://github.com/googleapis/python-aiplatform/blob/main/vertexai/evaluation/metrics/_default_templates.py#L819)), and for the `PAIRWISE_QUESTION_ANSWERING_QUALITY_PROMPT_TEMPLATE` template ([link](https://github.com/googleapis/python-aiplatform/blob/main/vertexai/evaluation/metrics/_default_templates.py#L903))

**Comment by Valeriy-Burlaka** [comment]
Spotted the same issue for the `PAIRWISE_SUMMARIZATION_QUALITY_PROMPT_TEMPLATE` template, — see [this line](https://github.com/googleapis/python-aiplatform/blob/main/vertexai/evaluation/metrics/_default_templates.py#L819).

**Comment by matthew29tang** [comment]
Resolved in https://github.com/googleapis/python-aiplatform/commit/5f4d586d4f2d20f48f0c3bdd3ea00ec8e5bcdd77

**Comment by Valeriy-Burlaka** [comment]
@matthew29tang , that commit misses to fix 1 of the 3 templates reported as having the issue (see the `PAIRWISE_SUMMARIZATION_QUALITY_PROMPT_TEMPLATE` prompt  — [link](https://github.com/googleapis/python-aiplatform/blob/main/vertexai/evaluation/metrics/_default_templates.py#L819)).

I opened https://github.com/googleapis/python-aiplatform/pull/4444 from my fork to fix the remaining template, — could you please check it out? Thanks!

**Comment by matthew29tang** [comment]
Fixed with https://github.com/googleapis/python-aiplatform/commit/b456ce3fd8017f6ce97f6be6c80924d8f55ce057
