### ISSUE TITLE
501 Unable to submit request because one or more response schemas specified unsupported field min_length

### ISSUE THREAD

**Issue by mihalaches** [googleapis/python-aiplatform#4510]
## Expected Behavior
Until this morning this worked. I have this schema and I'm using :
vertexai = "^1.69.0"
google-cloud-aiplatform = "^1.69.0"
And for some reason I receive this error:
<html>
<body>
<pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; word-break: break-word; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">501 Unable to submit request because one or more response schemas specified unsupported field min_length. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/control-generated-output</pre>
Request Method: | GET
-- | --
http://localhost:8651/test
5.0.3
MethodNotImplemented
501 Unable to submit request because one or more response schemas specified unsupported field min_length. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/control-generated-output

This is the schema:

INVOICE_PRODUCTS_SCHEMA = {
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "product_code": {
                "type": "string",
                "minLength": 1,
                "maxLength": 50,
                "pattern": "^[a-zA-Z0-9-_.]+$",  
                "description": "A unique identifier for the product. This may include letters, numbers, and specific symbols (hyphen, underscore, period)."
            },
            "product_description": {
                "type": "string",
                "minLength": 5,
                "maxLength": 500,
                "pattern": "^[\\w\\s,.-]+$", 
                "description": "A detailed description of the product, typically including its name, type, and key features."
            },
            "external_product_code": {
                "type": "string",  
                "minLength": 0,
                "maxLength": 50,
                "pattern": "^[\\w\\s-_.]*$", 
                "description": "An optional external code used to identify the product in systems outside your organization."
            },
            "unit_and_quantity_detected": {
                "type": "string",
                "minLength": 1,
                "maxLength": 100,
                "pattern": "^[\\w\\s,()]+(\\s\\d+)?$",  
                "description": "The detected unit and quantity of the product, which may include text descriptions (e.g., 'boxes', 'packs') and quantities."
            },
            "customer_unit_and_quantity_detected": {
                "type": "string",
                "minLength": 1,
                "maxLength": 100,
                "pattern": "^[\\w\\s,()]+(\\s\\d+)?$",  
                "description": "The customer-specific unit and quantity detected, similar to the previous field but tailored to the customer's terminology.",
                "example": ['20 for 40 Stuck', 'pro 10 stk', '20uz', 'Dis a 50 Stk', '60 Stuck/Dispenser', '20 Stuck/Dispenser', '30 Stuck', 'a 50 ST', 'Pack a 10 Stk', 'only a integer']
            },
            "product_quantity": {
                "type": "integer",
                "minimum": 1,
                "description": "The actual quantity of the product being purchased, which must be a positive integer."
            },
            "unit_price": {
                "type": "number",
                "minimum": 0.01, 
                "description": "The price per unit of the product, expressed in the appropriate currency format with two decimal places."
            }
        },
        "required": ["product_code","product_description","external_product_code","unit_and_quantity_detected","customer_unit_and_quantity_detected","product_quantity","unit_price"],
    },
}

</body>
</html>

This was working until 2 hrs ago or something like that, And in the documentation I can see that we can use this schema:
https://cloud.google.com/vertex-ai/docs/reference/rest/v1/Schema

## Specifications

- Version: 1.69.0

**Comment by kylePmcloughlin** [comment]
Same problem.
Started at Friday 2024-10-04 18:00 UCT.
I am using google-cloud-aiplatform==1.68.0

**Comment by jaycee-li** [comment]
Hi @mihalaches , I tried your schema with vertexai==1.69.0 using the following code, and it worked without any issues:
```
response_schema = {
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "product_code": {
        "type": "string",
        "minLength": 1,
        "maxLength": 50,
        "pattern": "^[a-zA-Z0-9-.]+$",
        "description": "A unique identifier for the product. This may include letters, numbers, and specific symbols (hyphen, underscore, period)."
      },
      "product_description": {
        "type": "string",
        "minLength": 5,
        "maxLength": 500,
        "pattern": "^[\w\s,.-]+$",
        "description": "A detailed description of the product, typically including its name, type, and key features."
      },
      "external_product_code": {
        "type": "string",
        "minLength": 0,
        "maxLength": 50,
        "pattern": "^[\w\s-.]*$",
        "description": "An optional external code used to identify the product in systems outside your organization."
      },
      "unit_and_quantity_detected": {
        "type": "string",
        "minLength": 1,
        "maxLength": 100,
        "pattern": "^[\w\s,()]+(\s\d+)?$",
        "description": "The detected unit and quantity of the product, which may include text descriptions (e.g., 'boxes', 'packs') and quantities."
      },
      "customer_unit_and_quantity_detected": {
        "type": "string",
        "minLength": 1,
        "maxLength": 100,
        "pattern": "^[\w\s,()]+(\s\d+)?$",
        "description": "The customer-specific unit and quantity detected, similar to the previous field but tailored to the customer's terminology.",
        "example": ['20 for 40 Stuck', 'pro 10 stk', '20uz', 'Dis a 50 Stk', '60 Stuck/Dispenser', '20 Stuck/Dispenser', '30 Stuck', 'a 50 ST', 'Pack a 10 Stk', 'only a integer']
      },
      "product_quantity": {
        "type": "integer",
        "minimum": 1,
        "description": "The actual quantity of the product being purchased, which must be a positive integer."
      },
      "unit_price": {
        "type": "number",
        "minimum": 0.01,
        "description": "The price per unit of the product, expressed in the appropriate currency format with two decimal places."
      }
    },
    "required": ["product_code","product_description","external_product_code","unit_and_quantity_detected","customer_unit_and_quantity_detected","product_quantity","unit_price"],
  }
}

model = GenerativeModel("gemini-1.5-flash")
response = model.generate_content(
    "tell me something about Google products",
    generation_config=GenerationConfig(
        response_mime_type="application/json", response_schema=response_schema
    ),
)
```

It seems the error you encountered might be related to the limited support for schema fields in `response_schema`. Currently, only `enum`, `items`, `maxItems`, `nullable`, `properties`, and `required` are supported. Other fields like `minLength` in your schema will be ignored.

Ideally, unsupported fields should be ignored instead of causing an error like the one you experienced: `501 Unable to submit request because one or more response schemas specified unsupported field min_length...`

Could you please try again and confirm if you still encounter the same error? If so, sharing your full code would be helpful in investigating this further. Thanks!

**Comment by jaycee-li** [comment]
Hi @kylePmcloughlin , the following code(with `example` field in schema) works on my side. Could you please share your code so we can further investigate? Thanks!
```
response_schema = {
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "recipe_name": {
                "type": "string",
                "example": "recipe"
            },
        },
        "required": ["recipe_name"],
    },
}

model = GenerativeModel("gemini-1.5-flash")

response = model.generate_content(
    "Give me a recipe of ice cream",
    generation_config=GenerationConfig(
        response_mime_type="application/json", response_schema=response_schema
    ),
)
```

**Comment by kylePmcloughlin** [comment]
Hi @jaycee-li sure, here is the code that worked until about Friday 2024-10-04 16:00 UCT:

```
def get_response_schema():
    """ Makes an OpenAPI 3.0 compliant schema object """
    
    # Declare schema dict
    response_schema_dict = {}
    
    # Top Level
    response_schema_dict["type"] = "object"
    response_schema_dict["required"] = ["label", "score", "explanation"]
    response_schema_dict["properties"] = {}
    response_schema_dict["example"] = {}
    
    # Properties: label
    response_schema_dict["properties"]["label"] = {"type": "string", "enum": ["positive", "negative", "neutral"]}
    response_schema_dict["example"]["label"] = "positive"
    
    # Properties: score
    response_schema_dict["properties"]["score"] = {"type": "number", "format":"float"}
    response_schema_dict["example"]["score"] = 0.7
    
    # Properties: explanation
    response_schema_dict["properties"]["explanation"] = {"type": "string"}
    response_schema_dict["example"]["explanation"] = "Der Artikel thematisiert positive Entwicklungen und Erfolge."
        
    return response_schema_dict
```
    
And here is my updated code which got my program working again. (Removed example and changed number specification):

```
def get_response_schema():
    """ Makes an OpenAPI 3.0 compliant schema object """
    
    # Declare schema dict
    response_schema_dict = {}
    
    # Top Level
    response_schema_dict["type"] = "object"
    response_schema_dict["required"] = ["label", "score", "explanation"]
    response_schema_dict["properties"] = {}
    
    # Properties: label
    response_schema_dict["properties"]["label"] = {"type": "string", "enum": ["positive", "negative", "neutral"]}
    
    # Properties: score
    response_schema_dict["properties"]["score"] = {"type": "number"}
    
    # Properties: explanation
    response_schema_dict["properties"]["explanation"] = {"type": "string"}
        
    return response_schema_dict
```

**Comment by michaelwsherman** [comment]
@jaycee-li `example` is one of the fields in the schema, see our docs: https://cloud.google.com/vertex-ai/docs/reference/rest/v1/Schema .

**Comment by md2eoseo** [comment]
I'm getting same error when I send `response_schema` as [document](https://cloud.google.com/vertex-ai/docs/reference/rest/v1/Schema) written.

I'm using python, so I'm not sure document that I linked here is right for me.
If I'm wrong please guide me with right document. Thank you.

Error messages:
google-cloud-aiplatform==1.60.0
```
{"utils": {"error": "Protocol message Schema has no \"minLength\" field."}}}
```
google-cloud-aiplatform==1.70.0
```
{"utils": {"error": "400 Unable to submit request because one or more response schemas specified unsupported field min_length. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/control-generated-output"}}}
```

**Comment by jaycee-li** [comment]
Hey @Ark-kun , do you have more insights on this?

**Comment by Ark-kun** [comment]
I'm not sure the SDK team can do anything here. The `501 Unable to submit request because one or more response schemas specified unsupported field min_length` error message coming from the service is clear an actionable.

AFAIK, the service now ignores the unsupported fields, s the issue is fixed.

**Comment by mreza0100** [comment]
Same class of problem — Gemini/Vertex rejects (or silently ignores) value-level schema fields like `min_length`/`max_length`/`maxItems`. Our fix was to strip those bounds from the schema we send and re-enforce them client-side after parsing by clamping the response.

Packaged as `clamp_to_constraints` in a small MIT lib — keeps the bound as a real guarantee without tripping the 501.

🔗 https://github.com/mreza0100/gemini-coax
