### ISSUE TITLE
Configuring `tool_config` for Dynamic Threshold in Google Search Grounding with `vertexai` Package

### ISSUE THREAD

**Issue by GuglielmoCerri** [googleapis/python-aiplatform#4644]
#### Background
This [documentation](https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/ground-gemini) explains how to integrate Google Search grounding with the Gemini model using the `vertexai` package from `google-cloud-aiplatform`. According to the article:
> "Threshold: In your request, you can specify a dynamic retrieval configuration with a threshold. The threshold is a floating point value in the range [0,1] and defaults to 0.7."

The [API documentation](https://ai.google.dev/gemini-api/docs/grounding?lang=python) also mentions that the threshold can be set in the `genai` package using a dictionary as follows:

```python
tools = {"google_search_retrieval": {
        "dynamic_retrieval_config": {
            "mode": "unspecified",
            "dynamic_threshold": 0.06}}}
```

#### Problem
However, the `vertexai` package (which is used in the main documentation) does not clearly explain how to set this `dynamic_threshold` value within `DynamicRetrievalConfig`. Currently, I am using the following code:

```python
tools = Tool.from_google_search_retrieval(grounding.GoogleSearchRetrieval())
model.generate_content(prompt, tools=[tools])
```

The class `GoogleSearchRetrieval` is defined in the `_GenerativeModel` class [here](https://github.com/googleapis/python-aiplatform/blob/main/vertexai/generative_models/_generative_models.py#L2731), but there is no clear option to configure `dynamic_threshold`.

#### Request
Could you provide guidance on setting the `dynamic_threshold` in `vertexai`’s `tool_config` for Google Search grounding? Alternatively, if this feature is not currently supported in `vertexai`, could it be added or documented for more clarity?

**Comment by diemtvu** [comment]
Fixed with https://github.com/googleapis/python-aiplatform/commit/c39334a63e83d4ab8e4d5cc82b22b9096940fe50
