### ISSUE TITLE
`ds.column_names` doesn't contain nested fields in BigQuery table

### ISSUE THREAD

**Issue by geraint0923** [googleapis/python-aiplatform#504]
https://github.com/googleapis/python-aiplatform/blob/d0f229d8839cf5008666e369ffeff25a95fa4ac2/google/cloud/aiplatform/datasets/tabular_dataset.py#L207

This only returns the outer field names, and the nested fields are ignored.

**Comment by ivanmkc** [comment]
Thanks for flagging this.

**Comment by sirtorry** [comment]
fixed in #522
