### ISSUE TITLE
Expose JobState enum

### ISSUE THREAD

**Issue by telpirion** [googleapis/python-aiplatform#506]
When listing a bunch of `BatchPredictionJob` objects, it should be possible to compare the value of `BatchPredictionJob.job_state` against a specific enum constant, e.g. JOB_STATE_SUCCEEDED. Currently, this enum is wrapped within the `gca_job_state` module.

**Comment by dizcology** [comment]
To clarify, is this about exposing the enum in Vertex SDK?

Something like this works:
```
from google.cloud import aiplatform

aiplatform.init(project='...', location='...')
jobs = aiplatform.BatchPredictionJob.list()
job[0].state is aiplatform.gapic.JobState.JOB_STATE_SUCCEEDED  # => True/False
```

**Comment by telpirion** [comment]
Both, kind of:

1. Expose JobState at a higher level in the object hierarchy. I feel that accessing the `gca` resources isn't intuitive from a developer standpoint. Rather, I expect something like this:
   
       job.state is aiplatform.jobs.JobState.JOB_STATE_SUCCEEDED

2. Likewise, it would be helpful to be able to filter a `list()` result by job state.

**Comment by vinnysenthil** [comment]
1. I'll raise this, it would be nice to have these enums be accessible. For now we can get away with the following:
```py
str(job.state) == "JobState.JOB_STATE_SUCCEEDED"
```
2. This is available as @dizcology mentioned:
```py
cancelled_jobs = aiplatform.BatchPredictionJob.list(filter='state=JOB_STATE_CANCELLED')
```

**Comment by dizcology** [comment]
Regarding 1: you could do something like this:
```
jobs = aiplatform.BatchPredictionJob.list()
jobs[0].state.name == 'JOB_STATE_SUCCEEDED'
```
