### ISSUE TITLE
400 "Prediction failed

### ISSUE THREAD

**Issue by AnkitKundariya** [googleapis/python-aiplatform#514]
https://github.com/googleapis/python-aiplatform/blob/master/samples/snippets/predict_custom_trained_model_sample.py

Data I'm submitting as instances to API

```

[struct_value {
  fields {
    key: "field"
    value {
      number_value: 107.0
    }
  }
  fields {
    key: "source"
    value {
      number_value: 1.0
    }
  }
  fields {
    key: "target"
    value {
      number_value: 2.0
    }
  }
}
]

```

Error

`400 "Prediction failed: Exception during sklearn prediction: float() argument must be a string or a number, not 'dict'"
`

Executing the same thing from UI Endpoint from VerexAI

`{
 "error": {
   "code": 400,
   "message": "\"Prediction failed: Exception during sklearn prediction: float() argument must be a string or a number, not 'dict'\"\n",
   "status": "FAILED_PRECONDITION"
 }
}`

**Comment by vinnysenthil** [comment]
Hi @AnkitKundariya,

Are you are passing the following `dict` as an argument to `instances` in `predict_custom_trained_model_sample`?
```py
{"field": 107.0, "source": 1.0, "target": 2.0}
```

What input signature does your sklearn model expect? If it's a NumPy array, this should suffice:

```py
from google.cloud import aiplatform

aiplatform.init(project="your-project")  # Replace with project ID

ep = aiplatform.Endpoint("your endpoint ID")

res = ep.predict([[107.0, 1.0, 2.0]])
```

**Comment by vinnysenthil** [comment]
Closing out, feel free to re-open if you're still running into trouble.
