### ISSUE TITLE
JSON logs are not being parsed with cloud ml jobs (vertex pipelines)

### ISSUE THREAD

**Issue by amit-artlist** [googleapis/python-aiplatform#629]
#### Environment details

  - OS type and version: Debian 9
  - Python version: 3.8
  - pip version: `pip --version` 
  - 1.3

#### Steps to reproduce

  1. Deploy a vertex pipeline (kfp) - with a component that outputs JSON logs
  2. Run the pipeline
  3. Logs are not being parsed 

#### example

Log structure - inside of `jsonPayload` 2 properties -
1. `levelname = info` 
2. `message` contains the full payload `"{"event": "cv2_res: True", "level": "debug", "severity": "debug", "message": "cv2_res: True"}
"`

Same code tested on cloud functions and worked as expected

**Comment by andrewferlitsch** [comment]
more than 30 days w/o response from submitter on copy of component that outputs the JSON log. Closing the issue.
