### ISSUE TITLE
Vertex AI Pipeline - How to create a scheduled Vertex AI pipeline? (As the AIPlatformClient in the Kubeflow SDK is marked as deprecated)

### ISSUE THREAD

**Issue by SaschaHeyer** [googleapis/python-aiplatform#673]
Hello Google Team,

AIPlatformClient as part of the Kubeflow SDK will be deprecated in favor of this AI Platform SDK. 
As documented in the repository: 
https://github.com/kubeflow/pipelines/blob/56cf094fd3058b5c640077968ffb0f01e0511a57/sdk/python/kfp/v2/google/client/client.py#L169

The Kubeflow SDK offers a possibility to create a scheduled job. 

Checked the repository for the keyword schedule, nothing related to pipelines. 
So what is the recommended way of creating scheduled pipelines using this recommended AI Platform SDK?

Looking forward to your feedback

**Comment by SaschaHeyer** [comment]
Morning
any feedback on that?

**Comment by SaschaHeyer** [comment]
Morning 
any feedback on that?

**Comment by mrhimanshu** [comment]
Any update on this ?

**Comment by SaschaHeyer** [comment]
Morning
any feedback on that?

**Comment by andrewferlitsch** [comment]
@SaschaHeyer You will find all the notebooks in this git folder show the Vertex AI pipeline method for executing a KFP pipeline.

**Comment by SaschaHeyer** [comment]
@andrewferlitsch 
Thanks, I am aware of those notebooks and I also know how to run a pipeline. 

AIPlatformClient as part of the Kubeflow SDK will be deprecated in favor of this AI Platform SDK.
As documented in the repository:

see:
https://github.com/kubeflow/pipelines/blob/56cf094fd3058b5c640077968ffb0f01e0511a57/sdk/python/kfp/v2/google/client/client.py#L169

The Kubeflow SDK offers a possibility to create a scheduled job, but the Vertex AI SDK currently does not provide any of that functionality. 

Can you please re-open the ticket or guidance on how to do that with the Vertex AI SDK

**Comment by SaschaHeyer** [comment]
https://medium.com/google-cloud/how-to-implement-ci-cd-for-your-vertex-ai-pipeline-27963bead8bd

**Comment by SaschaHeyer** [comment]
@andrewferlitsch any feedback on that? We would like to react to that deprecation warning.

**Comment by SaschaHeyer** [comment]
@andrewferlitsch any updates on that?

**Comment by SaschaHeyer** [comment]
Morning @andrewferlitsch 
any feedback on that?

**Comment by tarrade** [comment]
@SaschaHeyer, not sure what is the "official way" but I guess Vertex A could de define a some kind of serveless ML services. In my case:
- CI/CD or Notebook to build the KFP pipeline and store the JSON on a GCS bucket
- Cloud Scheduler+Pub/Sub (to send the parameters of your pipelines at some given time)+CloudFunction(run the pipeline using the parameter of the payload of Pub/Sub. 

It is much more verbose than what your where doing before(need 3 additionals GCP serveless services) but you can:
- do everything with python client lib
- I guess in such case you can pass any parameters to your pipeline

There is some example with TFX, using python client lin for Cloud Scheduler/PubSub here [1]

This is the best way I found to run Vertex AI pipeline (KFP) in a CI/CD process. I will be more than happy to learn better way or alternative to run pipeline

[1] https://cloud.google.com/blog/topics/developers-practitioners/model-training-cicd-system-part-ii

**Comment by clausagerskov** [comment]
why is this issue closed?

**Comment by sfujiwara** [comment]
Currently, Google Cloud official document recommends following ways

1. Cloud Scheduler ==> Cloud Functions ==> Vertex Pipelines
2. Cloud Pub/Sub ==> Cloud Functions ==> Vertex Pipelines

https://cloud.google.com/vertex-ai/docs/pipelines/schedule-cloud-scheduler

I think it is reasonable. Especially, 2 is a good idea if we want to run our pipeline repeatedly but with different parameter. The previous way using `create_schedule_from_job_spec` could not handle such cases.

**Comment by SaschaHeyer** [comment]
@sfujiwara @tarrade absolutely appreciate your feedback and agree with your solutions. 
I wrote about exactly the same approach a couple of months ago
https://medium.com/google-cloud/how-to-implement-ci-cd-for-your-vertex-ai-pipeline-27963bead8bd

But it would be nice to get some official feedback from the Google team if there is either 

1. A replacement in the Vertex AI SDK planned 
2. Or a tighter integration of scheduling in Vertex AI UI itself

Putting functions to depreciation without replacement is just bad practice (considering people using it already in production).

**Comment by shotarok** [comment]
It looks like a new Vertex AI API supports setting up a scheduled job without Cloud Function and Cloud Scheduler 🎉 

* https://cloud.google.com/vertex-ai/docs/pipelines/schedule-pipeline-run
* https://cloud.google.com/vertex-ai/docs/reference/rest/v1beta1/projects.locations.schedules

**Comment by antnsi** [comment]
Has anyone managed to update (re-upload) a PipelineJob for an existing schedule without creating a new one? It looks like there is an API to only update attributes associated with the schedule itself, but not the underlying PipelineJob, which sounds like backwards logic to me. This is the typical workflow for updating a PipelineJob without touching existing jobs (existing schedule), but the current API suggests to create a new schedule. Am I missing something?
