### ISSUE TITLE
bug: References to non-existent classes in docstrings

### ISSUE THREAD

**Issue by nicain** [googleapis/python-aiplatform#681]
There are 7 locations referring to objects that are not defined in the API (referring to a non-existent "master" module.)

xref: cl/394364741

- google.cloud.aiplatform.master.ModelDeploymentMonitoringObjectiveConfig.deployed_model_id

https://github.com/googleapis/python-aiplatform/blob/af809b0551db88f8be7dd159f846bf60ab2a0296/google/cloud/aiplatform_v1/services/job_service/async_client.py#L1966
https://github.com/googleapis/python-aiplatform/blob/af809b0551db88f8be7dd159f846bf60ab2a0296/google/cloud/aiplatform_v1/types/job_service.py#L634
https://github.com/googleapis/python-aiplatform/blob/af809b0551db88f8be7dd159f846bf60ab2a0296/google/cloud/aiplatform_v1beta1/services/job_service/async_client.py#L1970
https://github.com/googleapis/python-aiplatform/blob/af809b0551db88f8be7dd159f846bf60ab2a0296/google/cloud/aiplatform_v1beta1/services/job_service/client.py#L2328
https://github.com/googleapis/python-aiplatform/blob/af809b0551db88f8be7dd159f846bf60ab2a0296/google/cloud/aiplatform_v1beta1/types/job_service.py#L636
https://github.com/googleapis/python-aiplatform/blob/af809b0551db88f8be7dd159f846bf60ab2a0296/google/cloud/aiplatform_v1/services/job_service/client.py#L2310

- google.cloud.aiplatform.master.ModelDeploymentMonitoringObjectiveConfig.deployed_model_id

https://github.com/googleapis/python-aiplatform/blob/af809b0551db88f8be7dd159f846bf60ab2a0296/google/cloud/aiplatform_v1beta1/types/feature.py#L85

**Comment by sasha-gitg** [comment]
Looks like this is resolved.
