### ISSUE TITLE
Use latest generator version

### ISSUE THREAD

**Issue by busunkim96** [googleapis/python-aiplatform#7]
This library is pinned to an older version of the library via `synth.py`. 

https://github.com/googleapis/python-aiplatform/blob/42fa6fd761ad446872cd4bb1aca3d88abb8d7085/synth.py#L38-L42

Eventually, the library should move to using the latest version of the microgenerator to get new features and bug fixes.

I've confirmed that continuing to use the Docker image is fine for the time being, and AC Tools will continue to publish it in addition to supporting the Bazel workflow.

**Comment by sasha-gitg** [comment]
@busunkim96 Is this item still required?
