### ISSUE TITLE
Private endpoints are not supported

### ISSUE THREAD

**Issue by Ark-kun** [googleapis/python-aiplatform#708]
Vertex AI supports private endpoints.
https://cloud.google.com/vertex-ai/docs/predictions/using-private-endpoints#create-private-endpoint
The user can specify the `network` for the endpoint.

 **Is your feature request related to a problem? Please describe.**

`Endpoint.create()` method does not allow specifying the network.

 **Describe the solution you'd like**
Add `Endpoint.create(network=...)` parameter.

**Comment by vinnysenthil** [comment]
Hey @Ark-kun - Private Endpoint support is planned for the next release cycle this month, thanks for raising this.

**Comment by steve-marmalade** [comment]
Does this library now support Private Endpoints (specifically, making online prediction requests) or is this still planned for a future release?
