### ISSUE TITLE
Difference between PredictionServiceClient and aiplatform.Endpoint()

### ISSUE THREAD

**Issue by alejandrods** [googleapis/python-aiplatform#747]
Hi,

I have followed [this example of the documentation](https://github.com/googleapis/python-aiplatform/blob/8fde2ce4441139784bc0fdd62c88d4b833018765/samples/snippets/prediction_service/predict_sample.py) to send a request to an vertexai endpoint. However, I got the same 500 error that in [this issue ](https://github.com/googleapis/python-aiplatform/issues/410). I managed to solve it using the lines you suggested:

```
aiplatform.init(project='my-project', location='us-central1')

endpoint = aiplatform.Endpoint('7912877321848094720')

response = endpoint.predict([
        [6.7, 3.1, 4.7, 1.5],
        [4.6, 3.1, 1.5, 0.2]
])
```

However, I would like to know what are the differences between `PredictionServiceClient` and `aiplatform.Endpoint`. I could not find the differences in the documentation.

Thank you.

**Comment by vinnysenthil** [comment]
Hi alejandrods@ - the `PredictionServiceClient` is the generated client built off of the Vertex AI API. This is accessible through the generated ("GAPIC") module:
```py
from google.cloud.aiplatform import gapic

client = gapic.PredictionServiceClient
```

the `aiplatform` classes are the higher-level SDK that is built on top of the generated client which we recommend for most use cases and is simpler to use. Hope that helps clear things up!

**Comment by alejandrods** [comment]
@vinnysenthil Thank you!
