### ISSUE TITLE
Specifying predictor class when creating a model (version?)

### ISSUE THREAD

**Issue by assapin** [googleapis/python-aiplatform#775]
There is a feature that enables one to specify a "custom prediction routine" - i.e. include a predictor class in python to be used as part of an endpoint over standard prediction containers. see [here](https://cloud.google.com/ai-platform/prediction/docs/custom-prediction-routines)

Is there an equivalent set of Python API's?

**Comment by assapin** [comment]
Thank you, @vinnysenthil. I think the API offered by the AI platform is more streamlined and less invasive; in my opinion worth creating an ability to override the predict() function (as well as pre process and postprocess)  within Vertex.ai

**Comment by rosiezou** [comment]
Hi @assapin, this feature has been made available in #1535, and the predictor class can be found in [`google/cloud/aiplatform/prediction/predictor.py`](https://github.com/googleapis/python-aiplatform/blob/main/google/cloud/aiplatform/prediction/predictor.py)
