### ISSUE TITLE
Why can't I specify the full path to the GCS when exporting a model?

### ISSUE THREAD

**Issue by nyuta01** [googleapis/python-aiplatform#802]
I would like to export the vertex model to the specified path for the convenience of integration with other services.
However, the implementation of Model#export_model allows us to specify the GCS prefix path, but not the full path.

Of course, we can solve this problem by using tools such as gsutil, but I think it would be convenient if we can specify the full path as a feature of Model#export_model[1].
If there is any significance to this specification, I would like to know about it.

[1] https://github.com/googleapis/python-aiplatform/blob/c795c6fbb87c4f71845cfbd2647c1adbc029bcef/google/cloud/aiplatform/models.py#L2258

**Comment by vinnysenthil** [comment]
Hi @nyuta01 - the `artifact_destination` should allow you to store the exported model in any GCS folder that you have write access to. Could you provide an example of a full path use case that is not supported?

**Comment by Ark-kun** [comment]
>Could you provide an example of a full path use case that is not supported?

The service adds a unique suffix to the user-provided URI.

**Comment by kweinmeister** [comment]
It looks like model export returns the Dict below. Does that provide the full path?
```
output_info (Dict[str, str]):
                Details of the completed export with output destination paths to
                the artifacts or container image.
```

**Comment by aribray** [comment]
Closing this because the reporter hasn't given any extra information. Thanks!
