### ISSUE TITLE
Update sample tests for Python 3.10

### ISSUE THREAD

**Issue by kweinmeister** [googleapis/python-aiplatform#820]
Sample tests for Python 3.10 have been temporarily disabled, due to TensorFlow not currently supporting them. This tracking issue is to add back sample testing when Python 3.10 is supported.

**Comment by parthea** [comment]
I'm going to unassign this issue as there is no action item right now. We have to wait for TensorFlow to support Python 3.10.

**Comment by parthea** [comment]
Tensorflow 2.8.0 was released and supports python 3.10: https://pypi.org/project/tensorflow/2.8.0/
