### ISSUE TITLE
Getting predictions from specific model variants inside an endpoint

### ISSUE THREAD

**Issue by assapin** [googleapis/python-aiplatform#827]
Hi

I have multiple model variants that I want to use to make predictions.
I started off putting all of them inside an endpoint with traffic splitting.

However, I have some cases where I want more control over the routing to specific variants - 
e.g. request a prediction from a specific model variant based on some parameter known at the time of request.

Is there a way to achieve this while deploying all the variants to a single endpoint?
e.g. somehow force the endpoint to use a certain model for prediction?

if not, what's the best way to achieve this level of control?

Thanks!

**Comment by kweinmeister** [comment]
That is correct, there is currently no way to override the traffic splitting on an endpoint by sending predictions to a specific model. The best way to achieve what you're looking for is to deploy each model to its own endpoint. Perhaps you could have a more complex configuration where most of your traffic goes to the combined endpoint, but you also have separate model endpoints that you can use for these exception cases.
