### ISSUE TITLE
Working dependencies are not fully specified

### ISSUE THREAD

**Issue by judahrand** [googleapis/python-aiplatform#830]
`proto-plus>=1.19.7` breaks `google-api-core<2.x.x` compatibility by
requiring `protobuf>=1.19.0`. The compatibility break is detailed here:
googleapis/python-api-core#276 and so results in a broken set of
dependencies which many dependency managers cannot resolve.

**Comment by busunkim96** [comment]
Hey @judahrand,

Thank you for the report. I'll release another version of google-api-core 1.x.x that allows `protobuf>3.18.0` for `python>=3.6` which I believe will resolve this.

**Comment by busunkim96** [comment]
The latest release of google-api-core v1 (1.31.4) should have resolved this specific conflict (`proto-plus` wanting `protobuf>=3.19.0` vs. `google-api-core` 1.x versions wanting `protobuf<3.18.0`.

If you're still seeing this issue please re-open this or file a new issue.

Thanks!
