### ISSUE TITLE
API for creating and managing Vertex AI labeling tasks

### ISSUE THREAD

**Issue by ivanzvonkov** [googleapis/python-aiplatform#858]
**Is your feature request related to a problem? Please describe.**
Using the Google Cloud Console to create Vertex AI Labeling tasks is tedious, especially inputting labels each time.

 **Describe the solution you'd like**
An API to create and manage these labeling tasks. 

I see what looks like a potential placeholder here: https://github.com/googleapis/python-aiplatform/blob/b613b264524aaab2cb65e63a5487770736faa7c8/google/cloud/aiplatform/jobs.py#L947

Is there a timeline for when it will be implemented?

 **Describe alternatives you've considered**
Creating the labeling task through the console is the only alternative I am aware of.

 **Additional context**
Vertex AI Labeling task creation in the console for context
![image](https://user-images.githubusercontent.com/25067660/142932732-9106b690-3153-4bba-ae3c-08880fa809dc.png)

**Comment by vinnysenthil** [comment]
Hi @ivanzvonkov - we don't have immediate plans to add to this class. For programmatic use of the data labelling service, you can alternatively use the lower-level `JobServiceClient`:
https://github.com/googleapis/python-aiplatform/blob/1d81783b2f914dd7606ee884ca31c1a594e5135f/samples/snippets/job_service/create_data_labeling_job_specialist_pool_sample.py#L32-L58

You can find several more samples [in this directory](https://github.com/googleapis/python-aiplatform/tree/main/samples/snippets/job_service). Hope this helps!
