### ISSUE TITLE
CustomContainerTrainingJob documentation is littered with references to TrainingPipeline

### ISSUE THREAD

**Issue by jasonbrancazio** [googleapis/python-aiplatform#875]
Here is an example. 
https://github.com/googleapis/python-aiplatform/blob/91dd3c0d5de72fac5b1dc8a9bc23d6cb431061a4/google/cloud/aiplatform/training_jobs.py#L2406

There are many such ambiguous references to TrainingPipeline in training_jobs.py. 

I'm getting started with the python client library. I have a custom container that I'd like to run as a job. I might also like to run it as a training pipeline. After a first glance in the docs, I found it difficult to determine when to choose a CustomJob and when to choose a CustomContainerTrainingJob.  

It seems the functionality of the CustomContainerTrainingJob class corresponds to "Training Pipelines" in the Vertex AI web UI, for example because it specifies parameters for model serving after the job completes. Would it make sense, therefore, to rename the CustomContainerTrainingJob class to TrainingPipeline?

Alternatively, someone should read the comments and docstrings in training_jobs.py and consider what all references to TrainingPipeline in the CustomContainerTrainingJob class really should refer to.

**Comment by nayaknishant** [comment]
Hi @jasonbrancazio, thanks for the suggestion and it's something we'll keep in mind. CustomContainerTrainingJob and TrainingPipeline go hand-in-hand, but CustomContainerTrainingJob was the name chosen to follow our naming convention.
