### ISSUE TITLE
FailedPrecondition: 400 The Cloud Storage bucket of `gs://model_metadata_prod/aiplatform-custom-job-2021-12-05-10:15:22.264` is in location `us`. It must be in the same regional location as the service location `us-central1`.

### ISSUE THREAD

**Issue by yunruili** [googleapis/python-aiplatform#885]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
 **Describe the solution you'd like**
 **Describe alternatives you've considered**
 **Additional context**

**Comment by vinnysenthil** [comment]
Hi @yunruili - Vertex AI is a regionalized service and requires that you use buckets within the same region. For example, a model trained on Vertex AI in `us-east1` must use a Cloud Storage bucket in region `us-east1`.

Please [see the documentation](https://cloud.google.com/vertex-ai/docs/general/locations#choosing_your_location) here for more details.
