### ISSUE TITLE
Duplicate generated 'dataset_path' / 'parse_dataset_path' static methods

### ISSUE THREAD

**Issue by tseaver** [googleapis/python-aiplatform#897]
See: https://github.com/googleapis/python-aiplatform/blob/37ee0a1dc6e0105e19aca18f44995a352bfc40cb/google/cloud/aiplatform_v1/services/migration_service/client.py#L185-L228

There are *three* definitions each for `dataset_path` / `parse_dataset_path`, each with different signatures:  only the last one is actually in effect.  `gapic-generator-python` is capable of regenerating them in different orders (see PR #895), which is a breaking change.

**Comment by sasha-gitg** [comment]
@tseaver Can we close this or do we have another remediation?

**Comment by vinnysenthil** [comment]
Closing out, please re-open if this needs to be addressed.

**Comment by tseaver** [comment]
This issue remains in the code as of today (04618e0563b8588eec2ccd8342c6085ca08b5adb).

**Comment by morgandu** [comment]
@ivanmkc May need to discuss with team responsive for the generation. This can not be fixed manually.

**Comment by ivanmkc** [comment]
@tseaver I agree that the shadowed methods should be removed. 

Does the solution of keeping the last definition and removing the preceding ones work?

**Comment by ivanmkc** [comment]
@busunkim96 What is the correct way to modify that file. I've heard that it is autogenerated.

**Comment by ivanmkc** [comment]
Ongoing discussion is here: https://github.com/googleapis/gapic-generator-python/issues/1060
