### ISSUE TITLE
Invalid Annotation Schema URI Issue

### ISSUE THREAD

**Issue by pactera-song** [googleapis/python-aiplatform#927]
First I create a dataset with import_schema_uri:

    aiplatform.init(project=project, location=location)

    ds = aiplatform.TextDataset.create(
        display_name=display_name,
        gcs_source=src_uris,
        # import_schema_uri=aiplatform.schema.dataset.ioformat.text.extraction,
        import_schema_uri='gs://google-cloud-aiplatform/schema/dataset/ioformat/text_extraction_io_format_1.0.0.yaml',
        sync=sync,
    )

    ds.wait()

    print(ds.display_name)
    print(ds.resource_name)
    return ds

Then i try to run a CustomContainerTrainingJob like this:

    import google.cloud.aiplatform as aip

    aip.init(project='758485374127', location='us-central1', staging_bucket=BUCKET_NAME)

    dataset_id = 'projects/758485374127/locations/us-central1/datasets/674981392198664192'
    # dataset_id = 'projects/fr-dev-piiworker/locations/us-central1/datasets/test-01'
    dataset = aip.TextDataset(dataset_id)
    print(dataset.metadata_schema_uri)

    job = aip.CustomContainerTrainingJob(
        display_name='pipeline_test_1223',
        container_uri='us-central1-docker.pkg.dev/fr-dev-piiworker/ml-training/test_01_image:latest'
    )

    job.run(dataset, annotation_schema_uri='gs://google-cloud- 
    aiplatform/schema/dataset/ioformat/text_extraction_io_format_1.0.0.yaml')

    
but i met an error:
`
InvalidArgument: 400 List of found errors:	1.Field: training_pipeline.input_data_config.annotation_schema_uri; Message: Invalid annotation schema uri.	 [field_violations {
  field: "training_pipeline.input_data_config.annotation_schema_uri"
  description: "Invalid annotation schema uri."
}
]
`

i have also tried some other annotation_schema_uri but all failed.

Please help to find a solution.
Thanks!

**Comment by pactera-song** [comment]
all the logs:

======================================================================================

---------------------------------------------------------------------------
_InactiveRpcError                         Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/google/api_core/grpc_helpers.py in error_remapped_callable(*args, **kwargs)
     65     def error_remapped_callable(*args, **kwargs):
---> 66         try:
     67             return callable_(*args, **kwargs)

/opt/conda/lib/python3.7/site-packages/grpc/_channel.py in __call__(self, request, timeout, metadata, credentials, wait_for_ready, compression)
    945                                       wait_for_ready, compression)
--> 946         return _end_unary_response_blocking(state, call, False, None)
    947 

/opt/conda/lib/python3.7/site-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    848     else:
--> 849         raise _InactiveRpcError(state)
    850 

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "List of found errors:	1.Field: training_pipeline.input_data_config.annotation_schema_uri; Message: Invalid annotation schema uri.	"
	debug_error_string = "{"created":"@1640241494.533476326","description":"Error received from peer ipv4:74.125.195.95:443","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"List of found errors:\t1.Field: training_pipeline.input_data_config.annotation_schema_uri; Message: Invalid annotation schema uri.\t","grpc_status":3}"
>

The above exception was the direct cause of the following exception:

InvalidArgument                           Traceback (most recent call last)
/tmp/ipykernel_9914/2114271546.py in <module>
     13 )
     14 
---> 15 job.run(dataset, annotation_schema_uri='gs://google-cloud-aiplatform/schema/dataset/ioformat/text_extraction_io_format_1.0.0.yaml')

/opt/conda/lib/python3.7/site-packages/google/cloud/aiplatform/training_jobs.py in run(self, dataset, annotation_schema_uri, model_display_name, model_labels, base_output_dir, service_account, network, bigquery_destination, args, environment_variables, replica_count, machine_type, accelerator_type, accelerator_count, boot_disk_type, boot_disk_size_gb, reduction_server_replica_count, reduction_server_machine_type, reduction_server_container_uri, training_fraction_split, validation_fraction_split, test_fraction_split, training_filter_split, validation_filter_split, test_filter_split, predefined_split_column_name, timestamp_split_column_name, enable_web_access, tensorboard, sync)
   2887             if reduction_server_replica_count > 0
   2888             else None,
-> 2889             sync=sync,
   2890         )
   2891 

/opt/conda/lib/python3.7/site-packages/google/cloud/aiplatform/base.py in wrapper(*args, **kwargs)
    673                 if self:
    674                     VertexAiResourceNounWithFutureManager.wait(self)
--> 675                 return method(*args, **kwargs)
    676 
    677             # callbacks to call within the Future (in same Thread)

/opt/conda/lib/python3.7/site-packages/google/cloud/aiplatform/training_jobs.py in _run(self, dataset, annotation_schema_uri, worker_pool_specs, managed_model, args, environment_variables, base_output_dir, service_account, network, bigquery_destination, training_fraction_split, validation_fraction_split, test_fraction_split, training_filter_split, validation_filter_split, test_filter_split, predefined_split_column_name, timestamp_split_column_name, enable_web_access, tensorboard, reduction_server_container_uri, sync)
   3119             model=managed_model,
   3120             gcs_destination_uri_prefix=base_output_dir,
-> 3121             bigquery_destination=bigquery_destination,
   3122         )
   3123 

/opt/conda/lib/python3.7/site-packages/google/cloud/aiplatform/training_jobs.py in _run_job(self, training_task_definition, training_task_inputs, dataset, training_fraction_split, validation_fraction_split, test_fraction_split, training_filter_split, validation_filter_split, test_filter_split, predefined_split_column_name, timestamp_split_column_name, annotation_schema_uri, model, gcs_destination_uri_prefix, bigquery_destination)
    742                 self.project, self.location
    743             ),
--> 744             training_pipeline=training_pipeline,
    745         )
    746 

/opt/conda/lib/python3.7/site-packages/google/cloud/aiplatform_v1/services/pipeline_service/client.py in create_training_pipeline(self, request, parent, training_pipeline, retry, timeout, metadata)
    594         # Wrap the RPC method; this adds retry and timeout information,
    595         # and friendly error handling.
--> 596         rpc = self._transport._wrapped_methods[self._transport.create_training_pipeline]
    597 
    598         # Certain fields should be provided within the metadata header;

/opt/conda/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py in __call__(self, timeout, retry, *args, **kwargs)
    152     client_info=client_info.DEFAULT_CLIENT_INFO,
    153 ):
--> 154     """Wrap an RPC method with common behavior.
    155 
    156     This applies common error wrapping, retry, and timeout behavior a function.

/opt/conda/lib/python3.7/site-packages/google/api_core/grpc_helpers.py in error_remapped_callable(*args, **kwargs)
     66         try:
     67             return callable_(*args, **kwargs)
---> 68         except grpc.RpcError as exc:
     69             six.raise_from(exceptions.from_grpc_error(exc), exc)
     70 

InvalidArgument: 400 List of found errors:	1.Field: training_pipeline.input_data_config.annotation_schema_uri; Message: Invalid annotation schema uri.	 [field_violations {
  field: "training_pipeline.input_data_config.annotation_schema_uri"
  description: "Invalid annotation schema uri."
}
]

**Comment by andrewferlitsch** [comment]
You input to run() is the I/O input schema. You need to use the annotation schema.

aip.schema.dataset.annotation.text.extraction

**Comment by pactera-song** [comment]
@andrewferlitsch Thanks for help and this has fixed my problem.
