### ISSUE TITLE
CustomContainerTrainingJob - unable to use without serving uri

### ISSUE THREAD

**Issue by terekete** [googleapis/python-aiplatform#931]
Hi Folks,

Looking to create a custom container training  job using the sdk, have the model exported to either GCS or BQ. When using the SDK I am running into an error asking for the model serving uri to be set. 

Looking at the class for CustomContainerTrainingJob, it has a parent _CustomTrainingJob that has a condition defined to exception on the model container uri not being defined.

```
# if args needed for model is incomplete
        if model_display_name and not self._managed_model.container_spec.image_uri:
            raise RuntimeError(
                """model_display_name was provided but
                model_serving_container_image_uri was not provided when this
                custom pipeline was constructed.
                """
            )
```

In the documentation of the SDK, appears to indicate that defining the serving model container is **optional**.

```
# Usage without Dataset:

job.run(replica_count=1, model_display_name="my-trained-model")

```

#### Steps to reproduce
1. Create a simple training code and add to custom container via Dockerfile. Build to GCR
```
FROM gcr.io/deeplearning-platform-release/tf2-cpu.2-3

WORKDIR /

COPY trainer /trainer

ENTRYPOINT ["python", "-m", "trainer.train"]
```
2.  Run the code below based on the container.

#### Code to reproduce
```
from google.cloud import aiplatform

aiplatform.init(
    project='project-name-1234',
    location='northamerica-northeast1',
    staging_bucket='gs://custom-vertex-test',
    experiment='custom-test',
    experiment_description='custom-test'
)

job = aiplatform.CustomContainerTrainingJob(
    display_name='custom-train',
    container_uri='gcr.io/project-name-1234/trainer'
)

job.run(
    replica_count=1,
    model_display_name='custom-model',
    base_output_dir='gs://custom-vertex-test/custom-train'
)
```

#### Environment details

  - OS type and version: Linux
  - Python version: `python --version` 3.8
  - pip version: `pip --version`  20.0.2
  - `google-cloud-aiplatform` version: `pip show google-cloud-aiplatform` 1.8.1

#### Stack trace
```
Traceback (most recent call last):
  File "aiplatform_test.py", line 42, in <module>
    job.run(
  File "/home/terekete/.local/lib/python3.8/site-packages/google/cloud/aiplatform/training_jobs.py", line 2852, in run
    worker_pool_specs, managed_model = self._prepare_and_validate_run(
  File "/home/terekete/.local/lib/python3.8/site-packages/google/cloud/aiplatform/training_jobs.py", line 1345, in _prepare_and_validate_run
    raise RuntimeError(
RuntimeError: model_display_name was provided but
                model_serving_container_image_uri was not provided when this
                custom pipeline was constructed.
```

Any help is appreciated. If the training is meant to run without the need for model container uri to be defined, the fix might be to alter the _CustomTrainingJob exception to handle CustomContainerTrainingJob vs CustomTrainingJob differently.

Thank you!

**Comment by ErraticO** [comment]
feeling that vertex AI does not isolate the functional units of ML, and its coupling is high. Each function cannot be used alone. I hope it can be improved in the future. The ideal state should be pipeline, job and models. APIs do not need to be interdependent and can be used alone, but can be related to each other in a simple way, because sometimes we only need jobs, but we need to build API images.

**Comment by sasha-gitg** [comment]
`CustomContainerTrainingJob` can be configured to export a model to Vertex[1]. Vertex requires a serving container when exporting the model.

`model_display_name` is the display name of that exported model. If the intention is to export the model then, at minimum, `model_serving_container_image_uri` must be provided. If the intention is to not export the model then do not provide any exported model specific arguments like `model_display_name`.   


1. https://cloud.google.com/vertex-ai/docs/training/exporting-model-artifacts
