### ISSUE TITLE
Changing dataItem labels from SDK

### ISSUE THREAD

**Issue by saichandrapandraju** [googleapis/python-aiplatform#932]
Hi,

If I want to change labels (annotations) for my dataItem, I found only one way i.e, through console. 
What if I have an updated input csv file..? Is there a way to change dataItem labels through SDK ?

**Comment by sararob** [comment]
Hi,

If you're referring to updating the csv file associated with a managed dataset, the SDK doesn't support that. The [update method](https://github.com/googleapis/python-aiplatform/blob/main/google/cloud/aiplatform/datasets/dataset.py#L601) supports updating the display name, labels, or description for a dataset, so you'd need to create a new dataset and specify the new csv file as the source.

If you're referring to updating the key/value labels associated with a dataset, you can do that using the SDK with the following (this example uses `TabularDataset` but it will work for any managed dataset):

```
dataset = aiplatform.TabularDataset.create(
    gcs_source="gs://my-bucket/my-dataset.csv"
)

dataset.update(labels={"new_label_key": "new_label_value"})
```

I'll close this issue but if you're having trouble updating the key/value labels on a dataset feel free to re-open.
