### ISSUE TITLE
Error in example script for Training pipeline

### ISSUE THREAD

**Issue by wardVD** [googleapis/python-aiplatform#944]
The following [code snippet](https://github.com/googleapis/python-aiplatform/blob/HEAD/samples/model-builder/create_training_pipeline_custom_job_sample.py) results in the following error:

`FailedPrecondition: 400 'annotation_schema_uri' should be set in the TrainingPipeline.input_data_config for custom training or hyperparameter tuning with managed dataset.`

Also, [this doc](https://github.com/googleapis/python-aiplatform/blob/b72067bd6b7013fbd3a00f9178644320300f96c0/google/cloud/aiplatform/training_jobs.py#L2673) is confusing as there is not parameter `annotations_filter`

**Comment by gireocto** [comment]
Hello, did someone find a way to resolve this issue ?

**Comment by gireocto** [comment]
Also, I agree with @wardVD the doc for what is a annotation_schema_uri is really confusing, I can't get a clear example of how to use it on my own Vertex Dataset, does someone have a clearer way to explain this ?

**Comment by meredithslota** [comment]
Assigning to the sample author to fix. Thanks for reporting!
