### ISSUE TITLE
Is pull request for Vertex AI Pipeline scheduling is acceptable in this project?

### ISSUE THREAD

**Issue by toshitanian** [googleapis/python-aiplatform#946]
**Is your feature request related to a problem? Please describe.**

In kfp, Vertex AI Pipeline features are removed and migrated to this repository. At that time, the feature equivalent to `AIPlatformClient.create_schedule_from_job_spec` is lost. 
I understand that it's not a feature of Vertex AI itself and should be built by ourselves using Cloud Functions and Cloud Scheduler.
https://cloud.google.com/vertex-ai/docs/pipelines/schedule-cloud-scheduler

 **Describe the solution you'd like**
Now we are writing the code that mounts the same feature of `AIPlatformClient.create_schedule_from_job_spec` using python google-cloud SDK. 
If this repository accepts it as extra feature, I'd like to implement it inside this repository as like `contrib` for future maintenance and other user's benefits.

 **Describe alternatives you've considered**

We can manage it in our repository. 

 **Additional context**

**Comment by sasha-gitg** [comment]
We don't intend to support PipelineJob scheduling in the SDK at this time. We will reopen in the future on re-evaluation. Thanks!
