### ISSUE TITLE
Add class labels to ImageDataSet using import_data

### ISSUE THREAD

**Issue by jweiss-ocurate** [googleapis/python-aiplatform#961]
Hello,

I am building a multi-class label dataset. I would like to add labels with import_data, but the labels are not being applied. Does someone have an example on how to use data_item_labels?

```
import_schema_uri = aiplatform.schema.dataset.ioformat.image.multi_label_classification
dataset_id = "123456"

ds = aiplatform.ImageDataset(dataset_id)
class_labels = {'foo': 'bar'}
ds.import_data(gcs_source=files[0], data_item_labels=class_labels, import_schema_uri=aiplatform.schema.dataset.ioformat.image.multi_label_classification)
```

Thanks,
Jacob

**Comment by jweiss-ocurate** [comment]
Hey @ivanmkc ,

After running the code, the photos get sent to Vertex AI without a problem.

However, the labelling didn't get applied:
![image](https://user-images.githubusercontent.com/96882240/150830904-1c088b99-3c93-4bde-81a4-453997f39222.png)

Thanks,
Jacob

**Comment by ivanmkc** [comment]
Thanks, I'll take a look.

**Comment by ivanmkc** [comment]
Those class labels should be set in your gcs_source file (like a CSV).

Here's some sample code to illustrate the point:

```
import google.cloud.aiplatform as aiplatform


import_schema_uri = aiplatform.schema.dataset.ioformat.image.multi_label_classification

aiplatform.init(project="<YOUR_PROJECT>")
ds = aiplatform.ImageDataset.create("datalabels_test")

ds.import_data(
    gcs_source="gs://cloud-samples-data/vision/automl_classification/flowers/all_data_v2.csv",
    import_schema_uri=aiplatform.schema.dataset.ioformat.image.multi_label_classification,
)
```

Does that help?

**Comment by ivanmkc** [comment]
This page is what you need: https://cloud.google.com/vertex-ai/docs/datasets/prepare-image

You should be setting the `classificationAnnotations` in the JSON Lines or CSV file.

**Comment by eddaypandera** [comment]
This does not work for me either. It is importing to an existing dataset that doesn't seem to work.
Ithout I'd be able to do something like:
`class_labels = {'lab1': 'gs://path/to/image/imagefile.jpg'}
ds.import_data(gcs_source=DATASET_PATH, data_item_labels=class_labels, import_schema_uri=aiplatform.schema.dataset.ioformat.image.single_label_classification)`
but it doesn't like the filename in `class_labels`. If I leave it out the new images (defined in `gcs_source=DATASET_PATH` are imported unlabelled).
