### ISSUE TITLE
Matching Engine's Match Service proto spec

### ISSUE THREAD

**Issue by aaaaahaaaaa** [googleapis/python-aiplatform#994]
Is there a specific reason behind not having Matching Engine's Match Service protos (`MatchService`, `MatchRequest`, `BatchMatchRequest`, etc...) as part of the module? The rest of Matching Engine's API is there (`Index`, `IndexEndpoint` specs, etc..), but according to the doc, the protos for the nearest neighbours requests have to be created manually, which seems odd and quite inconvenient.

Protos are shown here (under `Create Online Queries`): https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/matching_engine/matching_engine_for_indexing.ipynb

**Comment by ivanmkc** [comment]
Thanks for bringing this up, we are working on a high-level API that will simplify the creation of the protos. We'll update the notebooks in the next month when that happens.

**Comment by ivanmkc** [comment]
Keep an eye on: https://github.com/googleapis/python-aiplatform/pull/995
